/*
Don't modify this file manually!
*/
var _p = {
    7 : {
        "Hero3" : 21,
        "Equip3" : 3,
        "Hero1" : 19,
        "Hero2" : 20,
        "TeamLv" : 10,
        "Equip1" : 1,
        "RobotID" : 7,
        "Equip2" : 2,
    },
    1 : {
        "Hero3" : 3,
        "Equip3" : 1,
        "Hero1" : 1,
        "Hero2" : 2,
        "TeamLv" : 10,
        "Equip1" : 1,
        "RobotID" : 1,
        "Equip2" : 1,
    },
    2 : {
        "Hero3" : 6,
        "Equip3" : 3,
        "Hero1" : 4,
        "Hero2" : 5,
        "TeamLv" : 10,
        "Equip1" : 1,
        "RobotID" : 2,
        "Equip2" : 2,
    },
    4 : {
        "Hero3" : 12,
        "Equip3" : 3,
        "Hero1" : 10,
        "Hero2" : 11,
        "TeamLv" : 10,
        "Equip1" : 1,
        "RobotID" : 4,
        "Equip2" : 2,
    },
    8 : {
        "Hero3" : 24,
        "Equip3" : 3,
        "Hero1" : 22,
        "Hero2" : 23,
        "TeamLv" : 15,
        "Equip1" : 1,
        "RobotID" : 8,
        "Equip2" : 2,
    },
    9 : {
        "Hero3" : 27,
        "Equip3" : 3,
        "Hero1" : 25,
        "Hero2" : 26,
        "TeamLv" : 15,
        "Equip1" : 1,
        "RobotID" : 9,
        "Equip2" : 2,
    },
    5 : {
        "Hero3" : 15,
        "Equip3" : 3,
        "Hero1" : 13,
        "Hero2" : 14,
        "TeamLv" : 10,
        "Equip1" : 1,
        "RobotID" : 5,
        "Equip2" : 2,
    },
    10 : {
        "Hero3" : 30,
        "Equip3" : 3,
        "Hero1" : 28,
        "Hero2" : 29,
        "TeamLv" : 15,
        "Equip1" : 1,
        "RobotID" : 10,
        "Equip2" : 2,
    },
    3 : {
        "Hero3" : 9,
        "Equip3" : 1,
        "Hero1" : 7,
        "Hero2" : 8,
        "TeamLv" : 10,
        "Equip1" : 1,
        "RobotID" : 3,
        "Equip2" : 1,
    },
    6 : {
        "Hero3" : 18,
        "Equip3" : 3,
        "Hero1" : 16,
        "Hero2" : 17,
        "TeamLv" : 10,
        "Equip1" : 1,
        "RobotID" : 6,
        "Equip2" : 2,
    },
    12 : {
        "Hero3" : 36,
        "Equip3" : 3,
        "Hero1" : 34,
        "Hero2" : 35,
        "TeamLv" : 20,
        "Equip1" : 1,
        "RobotID" : 12,
        "Equip2" : 2,
    },
    11 : {
        "Hero3" : 33,
        "Equip3" : 3,
        "Hero1" : 31,
        "Hero2" : 32,
        "TeamLv" : 15,
        "Equip1" : 1,
        "RobotID" : 11,
        "Equip2" : 2,
    },

};
module.exports = _p;
