/*
Don't modify this file manually!
*/
var _p = {
    27 : {
        "Level" : 13,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 27,
        "HeroId" : 10009,
        "Star" : 1,
        "Quality" : 2,
    },
    2 : {
        "Level" : 2,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 2,
        "HeroId" : 10008,
        "Star" : 1,
        "Quality" : 0,
    },
    3 : {
        "Level" : 3,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 3,
        "HeroId" : 10009,
        "Star" : 1,
        "Quality" : 0,
    },
    4 : {
        "Level" : 5,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 4,
        "HeroId" : 10010,
        "Star" : 1,
        "Quality" : 1,
    },
    5 : {
        "Level" : 5,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 5,
        "HeroId" : 10011,
        "Star" : 1,
        "Quality" : 1,
    },
    6 : {
        "Level" : 5,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 6,
        "HeroId" : 10012,
        "Star" : 1,
        "Quality" : 1,
    },
    7 : {
        "Level" : 6,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 7,
        "HeroId" : 10010,
        "Star" : 1,
        "Quality" : 1,
    },
    8 : {
        "Level" : 6,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 8,
        "HeroId" : 10011,
        "Star" : 1,
        "Quality" : 1,
    },
    10 : {
        "Level" : 7,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 10,
        "HeroId" : 10010,
        "Star" : 1,
        "Quality" : 1,
    },
    12 : {
        "Level" : 7,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 12,
        "HeroId" : 10012,
        "Star" : 1,
        "Quality" : 1,
    },
    14 : {
        "Level" : 8,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 14,
        "HeroId" : 10011,
        "Star" : 1,
        "Quality" : 1,
    },
    16 : {
        "Level" : 9,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 16,
        "HeroId" : 10010,
        "Star" : 1,
        "Quality" : 1,
    },
    20 : {
        "Level" : 10,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 20,
        "HeroId" : 10008,
        "Star" : 1,
        "Quality" : 2,
    },
    24 : {
        "Level" : 11,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 24,
        "HeroId" : 10009,
        "Star" : 1,
        "Quality" : 2,
    },
    28 : {
        "Level" : 15,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 28,
        "HeroId" : 10007,
        "Star" : 1,
        "Quality" : 2,
    },
    32 : {
        "Level" : 18,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 32,
        "HeroId" : 10008,
        "Star" : 1,
        "Quality" : 2,
    },
    33 : {
        "Level" : 18,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 33,
        "HeroId" : 10009,
        "Star" : 1,
        "Quality" : 2,
    },
    17 : {
        "Level" : 9,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 17,
        "HeroId" : 10011,
        "Star" : 1,
        "Quality" : 1,
    },
    21 : {
        "Level" : 10,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 21,
        "HeroId" : 10009,
        "Star" : 1,
        "Quality" : 2,
    },
    25 : {
        "Level" : 13,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 25,
        "HeroId" : 10007,
        "Star" : 1,
        "Quality" : 2,
    },
    29 : {
        "Level" : 15,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 29,
        "HeroId" : 10008,
        "Star" : 1,
        "Quality" : 2,
    },
    34 : {
        "Level" : 20,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 34,
        "HeroId" : 10010,
        "Star" : 1,
        "Quality" : 3,
    },
    9 : {
        "Level" : 6,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 9,
        "HeroId" : 10012,
        "Star" : 1,
        "Quality" : 1,
    },
    11 : {
        "Level" : 7,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 11,
        "HeroId" : 10011,
        "Star" : 1,
        "Quality" : 1,
    },
    13 : {
        "Level" : 8,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 13,
        "HeroId" : 10010,
        "Star" : 1,
        "Quality" : 1,
    },
    15 : {
        "Level" : 8,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 15,
        "HeroId" : 10012,
        "Star" : 1,
        "Quality" : 1,
    },
    18 : {
        "Level" : 9,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 18,
        "HeroId" : 10012,
        "Star" : 1,
        "Quality" : 1,
    },
    22 : {
        "Level" : 11,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 22,
        "HeroId" : 10007,
        "Star" : 1,
        "Quality" : 2,
    },
    26 : {
        "Level" : 13,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 26,
        "HeroId" : 10008,
        "Star" : 1,
        "Quality" : 2,
    },
    30 : {
        "Level" : 15,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 30,
        "HeroId" : 10009,
        "Star" : 1,
        "Quality" : 2,
    },
    36 : {
        "Level" : 20,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 36,
        "HeroId" : 10012,
        "Star" : 1,
        "Quality" : 3,
    },
    35 : {
        "Level" : 20,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 35,
        "HeroId" : 10011,
        "Star" : 1,
        "Quality" : 3,
    },
    1 : {
        "Level" : 1,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 1,
        "HeroId" : 10007,
        "Star" : 1,
        "Quality" : 0,
    },
    19 : {
        "Level" : 10,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 19,
        "HeroId" : 10007,
        "Star" : 1,
        "Quality" : 2,
    },
    23 : {
        "Level" : 11,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 23,
        "HeroId" : 10008,
        "Star" : 1,
        "Quality" : 2,
    },
    31 : {
        "Level" : 18,
        "SkillLv" : {
            1 : 5,
            2 : 5,
            3 : 5,
            4 : 5,
            5 : 5,
            6 : 5,
        },
        "ID" : 31,
        "HeroId" : 10007,
        "Star" : 1,
        "Quality" : 2,
    },

};
module.exports = _p;
