/*
Don't modify this file manually!
*/
var _p = {
    13 : {
        "Pep1" : 1,
        "Teams" : 3,
        "Pep3" : 2,
        "ID" : 13,
        "Odds" : 20,
        "Pep2" : 3,
    },
    7 : {
        "Pep1" : 3,
        "Teams" : 2,
        "Pep3" : 0,
        "ID" : 7,
        "Odds" : 30,
        "Pep2" : 3,
    },
    1 : {
        "Pep1" : 6,
        "Teams" : 1,
        "Pep3" : 0,
        "ID" : 1,
        "Odds" : 10,
        "Pep2" : 0,
    },
    2 : {
        "Pep1" : 5,
        "Teams" : 1,
        "Pep3" : 0,
        "ID" : 2,
        "Odds" : 10,
        "Pep2" : 1,
    },
    4 : {
        "Pep1" : 2,
        "Teams" : 1,
        "Pep3" : 2,
        "ID" : 4,
        "Odds" : 70,
        "Pep2" : 2,
    },
    8 : {
        "Pep1" : 3,
        "Teams" : 2,
        "Pep3" : 1,
        "ID" : 8,
        "Odds" : 30,
        "Pep2" : 2,
    },
    15 : {
        "Pep1" : 1,
        "Teams" : 3,
        "Pep3" : 3,
        "ID" : 15,
        "Odds" : 10,
        "Pep2" : 2,
    },
    9 : {
        "Pep1" : 2,
        "Teams" : 2,
        "Pep3" : 2,
        "ID" : 9,
        "Odds" : 20,
        "Pep2" : 2,
    },
    5 : {
        "Pep1" : 2,
        "Teams" : 2,
        "Pep3" : 1,
        "ID" : 5,
        "Odds" : 10,
        "Pep2" : 3,
    },
    10 : {
        "Pep1" : 2,
        "Teams" : 3,
        "Pep3" : 1,
        "ID" : 10,
        "Odds" : 10,
        "Pep2" : 3,
    },
    14 : {
        "Pep1" : 2,
        "Teams" : 3,
        "Pep3" : 3,
        "ID" : 14,
        "Odds" : 20,
        "Pep2" : 1,
    },
    3 : {
        "Pep1" : 4,
        "Teams" : 1,
        "Pep3" : 1,
        "ID" : 3,
        "Odds" : 10,
        "Pep2" : 1,
    },
    6 : {
        "Pep1" : 1,
        "Teams" : 2,
        "Pep3" : 2,
        "ID" : 6,
        "Odds" : 10,
        "Pep2" : 3,
    },
    12 : {
        "Pep1" : 2,
        "Teams" : 3,
        "Pep3" : 2,
        "ID" : 12,
        "Odds" : 30,
        "Pep2" : 2,
    },
    11 : {
        "Pep1" : 3,
        "Teams" : 3,
        "Pep3" : 1,
        "ID" : 11,
        "Odds" : 10,
        "Pep2" : 2,
    },

};
module.exports = _p;
