-- excel xlstable format (sparse 3d matrix)
--{	[sheet1] = { [row1] = { [col1] = value, [col2] = value, ...},
--					 [row5] = { [col3] = value, }, },
--	[sheet2] = { [row9] = { [col9] = value, }},
--}
-- nameindex table
--{ [sheet,row,col name] = index, .. }
sheetname = {
["Sheet1"] = 1,
};

sheetindex = {
[1] = "Sheet1",
};

local mapinfo = {
[1] = {
	[1] = {
		["MapId"] = 1,
		["MapName"] = "瓦尔王城",
		["ResPath"] = "res/map/01",
		["InfoFile"] = "01.json",
		["InitPos"] = {9,7},
		["BGPic"] = 201,
		["ScenePic"] = 1,
		["PicMapItem"] = "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
		["PicMapName"] = "res/ui/16_mapchoose/16_txt_map_01.png",
		["Exploration"] = 40,
		["AP"] = 500,
		["Time"] = 1,
		["Reward"] = 9999,
	},
	[2] = {
		["MapId"] = 2,
		["MapName"] = "英雄岗",
		["ResPath"] = "res/map/03",
		["InfoFile"] = "03.json",
		["InitPos"] = {5,7},
		["BGPic"] = 201,
		["ScenePic"] = 1,
		["PicMapItem"] = "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
		["PicMapName"] = "res/ui/16_mapchoose/16_txt_map_01.png",
		["Exploration"] = 100,
		["AP"] = 500,
		["Time"] = 1,
		["Reward"] = 9999,
	},
	[3] = {
		["MapId"] = 3,
		["MapName"] = "旅者丘陵",
		["ResPath"] = "res/map/04",
		["InfoFile"] = "04.json",
		["InitPos"] = {3,9},
		["BGPic"] = 201,
		["ScenePic"] = 1,
		["PicMapItem"] = "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
		["PicMapName"] = "res/ui/16_mapchoose/16_txt_map_01.png",
		["Exploration"] = 240,
		["AP"] = 500,
		["Time"] = 1,
		["Reward"] = 9999,
	},
	[4] = {
		["MapId"] = 4,
		["MapName"] = "血色森林",
		["ResPath"] = "res/map/05",
		["InfoFile"] = "05.json",
		["InitPos"] = {23,4},
		["BGPic"] = 201,
		["ScenePic"] = 1,
		["PicMapItem"] = "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
		["PicMapName"] = "res/ui/16_mapchoose/16_txt_map_01.png",
		["Exploration"] = 170,
		["AP"] = 500,
		["Time"] = 1,
		["Reward"] = 9999,
	},
	[5] = {
		["MapId"] = 5,
		["MapName"] = "地图5",
		["ResPath"] = "res/map/05",
		["InfoFile"] = "05.json",
		["InitPos"] = {23,4},
		["BGPic"] = 201,
		["ScenePic"] = 1,
		["PicMapItem"] = "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
		["PicMapName"] = "res/ui/16_mapchoose/16_txt_map_01.png",
		["Exploration"] = 1,
		["AP"] = 500,
		["Time"] = 1,
		["Reward"] = 9999,
	},
	[6] = {
		["MapId"] = 6,
		["MapName"] = "地图6",
		["ResPath"] = "res/map/06",
		["InfoFile"] = "06.json",
		["InitPos"] = {5,18},
		["BGPic"] = 201,
		["ScenePic"] = 1,
		["PicMapItem"] = "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
		["PicMapName"] = "res/ui/16_mapchoose/16_txt_map_01.png",
		["Exploration"] = 1,
		["AP"] = 500,
		["Time"] = 1,
		["Reward"] = 9999,
	},
	[7] = {
		["MapId"] = 7,
		["MapName"] = "地图7",
		["ResPath"] = "res/map/06",
		["InfoFile"] = "06.json",
		["InitPos"] = {5,18},
		["BGPic"] = 201,
		["ScenePic"] = 1,
		["PicMapItem"] = "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
		["PicMapName"] = "res/ui/16_mapchoose/16_txt_map_01.png",
		["Exploration"] = 1,
		["AP"] = 500,
		["Time"] = 1,
		["Reward"] = 9999,
	},
},
};


return mapinfo[1]
