/*
Don't modify this file manually!
*/
var _p = {
    2 : {
        "InitPos" : {
            1 : 23,
            2 : 4,
        },
        "InfoFile" : "05.json",
        "MapId" : 2,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "APCost" : 5,
        "MapName" : "地图5",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "BGPic" : 201,
        "ExitId" : 2449,
        "ResPath" : "res/map/05",
        "Area1" : 2,
        "UnlockCondition3" : 0,
        "UnlockCondition2" : 0,
    },
    3 : {
        "InitPos" : {
            1 : 5,
            2 : 7,
        },
        "InfoFile" : "03.json",
        "MapId" : 3,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "APCost" : 5,
        "MapName" : "地图3",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "BGPic" : 201,
        "ExitId" : 1723,
        "ResPath" : "res/map/03",
        "Area1" : 2,
        "UnlockCondition3" : 0,
        "UnlockCondition2" : 0,
    },
    1 : {
        "InitPos" : {
            1 : 5,
            2 : 7,
        },
        "InfoFile" : "01.json",
        "MapId" : 1,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "APCost" : 5,
        "MapName" : "地图1",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "BGPic" : 201,
        "ExitId" : 1723,
        "ResPath" : "res/map/01",
        "Area1" : 2,
        "UnlockCondition3" : 0,
        "UnlockCondition2" : 0,
    },
    4 : {
        "InitPos" : {
            1 : 3,
            2 : 9,
        },
        "InfoFile" : "04.json",
        "MapId" : 4,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "APCost" : 5,
        "MapName" : "地图4",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "BGPic" : 201,
        "ExitId" : 2023,
        "ResPath" : "res/map/04",
        "Area1" : 2,
        "UnlockCondition3" : 0,
        "UnlockCondition2" : 0,
    },
    5 : {
        "InitPos" : {
            1 : 23,
            2 : 4,
        },
        "InfoFile" : "05.json",
        "MapId" : 5,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "APCost" : 5,
        "MapName" : "地图5",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "BGPic" : 201,
        "ExitId" : 2449,
        "ResPath" : "res/map/05",
        "Area1" : 2,
        "UnlockCondition3" : 0,
        "UnlockCondition2" : 0,
    },

};
module.exports = _p;
