/*
Don't modify this file manually!
*/
var _p = {
    7 : {
        "Num" : 1,
        "Key" : 7,
        "Pro" : 200,
        "Group" : 3,
        "Price" : 100,
        "ItemID" : 16001,
        "PriceType" : 0,
    },
    1 : {
        "Num" : 1,
        "Key" : 1,
        "Pro" : 200,
        "Group" : 1,
        "Price" : 1000,
        "ItemID" : 10101,
        "PriceType" : 0,
    },
    2 : {
        "Num" : 2,
        "Key" : 2,
        "Pro" : 200,
        "Group" : 1,
        "Price" : 1000,
        "ItemID" : 10106,
        "PriceType" : 0,
    },
    4 : {
        "Num" : 1,
        "Key" : 4,
        "Pro" : 600,
        "Group" : 2,
        "Price" : 100,
        "ItemID" : 12003,
        "PriceType" : 0,
    },
    8 : {
        "Num" : 2,
        "Key" : 8,
        "Pro" : 600,
        "Group" : 3,
        "Price" : 100,
        "ItemID" : 16001,
        "PriceType" : 0,
    },
    9 : {
        "Num" : 10,
        "Key" : 9,
        "Pro" : 200,
        "Group" : 3,
        "Price" : 100,
        "ItemID" : 16001,
        "PriceType" : 0,
    },
    5 : {
        "Num" : 2,
        "Key" : 5,
        "Pro" : 200,
        "Group" : 2,
        "Price" : 100,
        "ItemID" : 12003,
        "PriceType" : 0,
    },
    10 : {
        "Num" : 1,
        "Key" : 10,
        "Pro" : 1000,
        "Group" : 4,
        "Price" : 10000,
        "ItemID" : 16005,
        "PriceType" : 0,
    },
    3 : {
        "Num" : 10,
        "Key" : 3,
        "Pro" : 600,
        "Group" : 1,
        "Price" : 1000,
        "ItemID" : 10111,
        "PriceType" : 0,
    },
    6 : {
        "Num" : 10,
        "Key" : 6,
        "Pro" : 200,
        "Group" : 2,
        "Price" : 100,
        "ItemID" : 12003,
        "PriceType" : 0,
    },
    12 : {
        "Num" : 3,
        "Key" : 12,
        "Pro" : 1000,
        "Group" : 6,
        "Price" : 800,
        "ItemID" : 15102,
        "PriceType" : 0,
    },
    11 : {
        "Num" : 3,
        "Key" : 11,
        "Pro" : 1000,
        "Group" : 5,
        "Price" : 500,
        "ItemID" : 15101,
        "PriceType" : 0,
    },

};
module.exports = _p;
