-- excel xlstable format (sparse 3d matrix)
--{	[sheet1] = { [row1] = { [col1] = value, [col2] = value, ...},
--					 [row5] = { [col3] = value, }, },
--	[sheet2] = { [row9] = { [col9] = value, }},
--}
-- nameindex table
--{ [sheet,row,col name] = index, .. }
sheetname = {
["status"] = 1,
};

sheetindex = {
[1] = "status",
};

local status = {
[1] = {
	[60001] = {
		["id"] = 60001,
		["name"] = "大气护盾",
		["icon"] = 0,
		["desc"] = "抵挡少量伤害",
		["triggercondition"] = 0,
		["duration"] = 0,
		["effectivetimes"] = 0,
		["effecttype"] = 2,
		["active"] = 0,
		["arg1"] = 50,
		["arg2"] = 50,
		["arg3"] = 1,
		["arg4"] = 1,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[60002] = {
		["id"] = 60002,
		["name"] = "增幅",
		["icon"] = 0,
		["desc"] = "触发：增加攻击力",
		["triggercondition"] = 9009,
		["duration"] = 0,
		["effectivetimes"] = 0,
		["effecttype"] = 4,
		["active"] = 2,
		["arg1"] = {8001,8005},
		["arg2"] = {80,90},
		["arg3"] = 10,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[60004] = {
		["id"] = 60004,
		["name"] = "力竭",
		["icon"] = 0,
		["desc"] = "攻击力降低",
		["triggercondition"] = 9001,
		["duration"] = 2,
		["effectivetimes"] = 0,
		["effecttype"] = 8,
		["active"] = 2,
		["arg1"] = {8001,8005},
		["arg2"] = {100,100},
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[60005] = {
		["id"] = 60005,
		["name"] = "晕眩",
		["icon"] = 0,
		["desc"] = "无法行动",
		["triggercondition"] = 0,
		["duration"] = 1,
		["effectivetimes"] = 0,
		["effecttype"] = 7,
		["active"] = 0,
		["arg1"] = 0,
		["arg2"] = 0,
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[60006] = {
		["id"] = 60006,
		["name"] = "士气",
		["icon"] = 0,
		["desc"] = "攻击力增加",
		["triggercondition"] = 9004,
		["duration"] = 3,
		["effectivetimes"] = 0,
		["effecttype"] = 4,
		["active"] = 2,
		["arg1"] = {8001,8005},
		["arg2"] = {80,90},
		["arg3"] = 10,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[40010] = {
		["id"] = 40010,
		["name"] = "蛇咬",
		["icon"] = 0,
		["desc"] = "敌全体伤害",
		["triggercondition"] = 9009,
		["duration"] = 0,
		["effectivetimes"] = 0,
		["effecttype"] = 10,
		["active"] = 2,
		["arg1"] = 40012,
		["arg2"] = 0,
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[40020] = {
		["id"] = 40020,
		["name"] = "狂怒",
		["icon"] = 0,
		["desc"] = "增加攻击力",
		["triggercondition"] = 9009,
		["duration"] = 0,
		["effectivetimes"] = 0,
		["effecttype"] = 10,
		["active"] = 2,
		["arg1"] = 40022,
		["arg2"] = 0,
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[40030] = {
		["id"] = 40030,
		["name"] = "飞行",
		["icon"] = 0,
		["desc"] = "直接攻击英雄",
		["triggercondition"] = 0,
		["duration"] = 0,
		["effectivetimes"] = 0,
		["effecttype"] = 1,
		["active"] = 2,
		["arg1"] = 0,
		["arg2"] = 0,
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[40040] = {
		["id"] = 40040,
		["name"] = "灵魂震击",
		["icon"] = 0,
		["desc"] = "晕眩敌人",
		["triggercondition"] = 9010,
		["duration"] = 0,
		["effectivetimes"] = 0,
		["effecttype"] = 10,
		["active"] = 2,
		["arg1"] = 40042,
		["arg2"] = 0,
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[60007] = {
		["id"] = 60007,
		["name"] = "嘲讽",
		["icon"] = 0,
		["desc"] = "吸引所有的敌人攻击自己",
		["triggercondition"] = 0,
		["duration"] = 0,
		["effectivetimes"] = 0,
		["effecttype"] = 3,
		["active"] = 2,
		["arg1"] = 0,
		["arg2"] = 0,
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[60008] = {
		["id"] = 60008,
		["name"] = "圣盾",
		["icon"] = 0,
		["desc"] = "在敌人攻击时免疫一次伤害",
		["triggercondition"] = 0,
		["duration"] = 0,
		["effectivetimes"] = 1,
		["effecttype"] = 5,
		["active"] = 0,
		["arg1"] = 0,
		["arg2"] = 0,
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[60009] = {
		["id"] = 60009,
		["name"] = "放逐",
		["icon"] = 0,
		["desc"] = "让敌人脱离这个世界，无法被选中也无法移动",
		["triggercondition"] = 0,
		["duration"] = 0,
		["effectivetimes"] = 1,
		["effecttype"] = 6,
		["active"] = 2,
		["arg1"] = 0,
		["arg2"] = 0,
		["arg3"] = 0,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
	[60010] = {
		["id"] = 60010,
		["name"] = "放血",
		["icon"] = 0,
		["desc"] = "每回合受到伤害",
		["triggercondition"] = 9002,
		["duration"] = 0,
		["effectivetimes"] = 3,
		["effecttype"] = 9,
		["active"] = 0,
		["arg1"] = 10,
		["arg2"] = 50,
		["arg3"] = 0.10000000,
		["arg4"] = 0,
		["arg5"] = 0,
		["arg6"] = 0,
		["arg7"] = 0,
	},
},
};


return status[1]
