/*
Don't modify this file manually!
*/
var _p = {
    "200301_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "i0_dz11001",
        "Genre" : 1,
        "Desc1" : 201003011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200301_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 201003011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100301_i",
    },
    10122 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10122,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "经验宝箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10122,
    },
    10123 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10123,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "金钱宝箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10123,
    },
    "201001_b" : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 32,
                4 : 64,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : "b0_0111002",
        "Genre" : 1,
        "Desc1" : 201010011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "201001_b",
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "卷轴宝箱",
        "Desc2" : 201010011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20101001_b",
    },
    10124 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 103,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10124,
        "GetInto" : 0,
        "IfWindows" : 1,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "高级宝箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10124,
    },
    10125 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 11,
                4 : 69,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 1801,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10125,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "神秘木箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10125,
    },
    "100201_b" : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 32,
                4 : 64,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : "b0_0111001",
        "Genre" : 1,
        "Desc1" : 101002011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "100201_b",
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "普通宝箱",
        "Desc2" : 101002011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "10100201_b",
    },
    "200801_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "i0_dz11001",
        "Genre" : 1,
        "Desc1" : 201008011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200801_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 201008011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100801_i",
    },
    "200501_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "i0_dz11001",
        "Genre" : 1,
        "Desc1" : 201005011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200501_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 201005011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100501_i",
    },
    "100301_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "e0_wq11001",
        "Genre" : 1,
        "Desc1" : 101003011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "100301_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "武器",
        "Desc2" : 101003011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "10100301_i",
    },
    "300201_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "p0_kt11001",
        "Genre" : 1,
        "Desc1" : 301002011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "300201_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "卡特琳娜碎片",
        "Desc2" : 301002011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "30100201_i",
    },
    10130 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 10,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3514,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10130,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10130,
    },
    "300401_i" : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 32,
                4 : 64,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : "p0_kt11001",
        "Genre" : 1,
        "Desc1" : 301002011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "300401_i",
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "卡特琳娜碎片",
        "Desc2" : 301002011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "30100401_i",
    },
    10131 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 10,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3514,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10131,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10131,
    },
    "100401_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "e0_yf11001",
        "Genre" : 1,
        "Desc1" : 101004011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "100401_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "衣服",
        "Desc2" : 101004011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "10100401_i",
    },
    10132 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 0,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3520,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10132,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "戒指卷（蓝）",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10132,
    },
    10101 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 101,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10101,
        "GetInto" : 0,
        "IfWindows" : 1,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "普通宝箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10101,
    },
    10133 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 10,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3515,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10133,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "银矿石",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10133,
    },
    10134 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 0,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3521,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10134,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "项链卷（蓝）",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10134,
    },
    10135 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 10,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3515,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10135,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "银矿石",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10135,
    },
    10104 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 101,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10104,
        "GetInto" : 0,
        "IfWindows" : 1,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "普通宝箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10104,
    },
    10136 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 10,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3515,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10136,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "银矿石",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10136,
    },
    10105 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3501,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10105,
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "武器",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10105,
    },
    "100101_b" : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 32,
                4 : 64,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : "b0_0111001",
        "Genre" : 1,
        "Desc1" : 101001011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "100101_b",
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "普通宝箱",
        "Desc2" : 101001011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "10100101_b",
    },
    "300101_b" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "b0_0111001",
        "Genre" : 1,
        "Desc1" : 301001011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "300101_b",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "普通宝箱",
        "Desc2" : 301001011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "30100101_b",
    },
    10107 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3552,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10107,
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "卡特琳娜碎片",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10107,
    },
    10108 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 103,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10108,
        "GetInto" : 0,
        "IfWindows" : 1,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "特殊宝箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10108,
    },
    10109 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3551,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10109,
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "兰斯洛特碎片",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10109,
    },
    10110 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10110,
        "GetInto" : 0,
        "IfWindows" : 1,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "中级宝箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10110,
    },
    10114 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 0,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3518,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10114,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "盔甲卷（紫）",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10114,
    },
    "300301_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "p0_kt11001",
        "Genre" : 1,
        "Desc1" : 301002011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "300301_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "卡特琳娜碎片",
        "Desc2" : 301002011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "30100301_i",
    },
    10115 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 104,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10115,
        "IfWindows" : 1,
        "GetInto" : 0,
        "RestrictLose" : 1,
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 2,
            },
        },
        "IfFloat" : 0,
        "Name" : "上锁的宝箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10115,
    },
    "200901_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "i0_dz11001",
        "Genre" : 1,
        "Desc1" : 201009011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200901_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 201009011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100901_i",
    },
    10116 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 10,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3514,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10116,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10116,
    },
    "200701_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "i0_dz11001",
        "Genre" : 1,
        "Desc1" : 201007011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200701_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 201007011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100701_i",
    },
    10117 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 10,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3515,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10117,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "银矿石",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10117,
    },
    "200101_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "e0_jz11001",
        "Genre" : 1,
        "Desc1" : 201001011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200101_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "戒指",
        "Desc2" : 201001011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100101_i",
    },
    10118 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 10,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3515,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10118,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "银矿石",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10118,
    },
    "200601_b" : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 32,
                4 : 64,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : "b0_0111002",
        "Genre" : 1,
        "Desc1" : 201006011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200601_b",
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "卷轴宝箱",
        "Desc2" : 201006011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100601_b",
    },
    10119 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 11,
                4 : 69,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 1801,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10119,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 0,
        "Name" : "神秘木箱",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10119,
    },
    "200401_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "i0_dz11001",
        "Genre" : 1,
        "Desc1" : 201004011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200401_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "铁矿石",
        "Desc2" : 201004011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100401_i",
    },
    10120 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 0,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 1,
        "Pic1" : 3520,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : 10120,
        "GetInto" : 0,
        "IfWindows" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "戒指卷（紫）",
        "Desc2" : 1,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : 10120,
    },
    "200201_i" : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : "e0_xl11001",
        "Genre" : 1,
        "Desc1" : 201002011,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 0,
        "RestrictStep" : 1,
        "Id" : "200201_i",
        "GetInto" : 0,
        "RestrictLose" : 1,
        "IfFloat" : 1,
        "Name" : "项链",
        "Desc2" : 201002011,
        "Resetting" : 1,
        "RestrictSuc" : 1,
        "Obstacle" : 0,
        "Reward" : "20100201_i",
    },

};
module.exports = _p;
