/*
Don't modify this file manually!
*/
var _p = {
    10010 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10010,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "空沼泽",
        "Speed" : 1,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10003 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10003,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽3",
        "Effect1" : {
            1 : 60072,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3213,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10011 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10011,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "2沼泽单格",
        "Effect1" : {
            1 : 60073,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3221,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10004 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10004,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽4",
        "Effect1" : {
            1 : 60071,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3214,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10012 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10012,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽2",
        "Effect1" : {
            1 : 60074,
            2 : 100,
            3 : 5,
            4 : 50,
        },
        "Speed" : 1,
        "Pic" : 3222,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 2,
        },
    },
    10020 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10020,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "空沼泽",
        "Speed" : 1,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10005 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10005,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽5",
        "Effect1" : {
            1 : 60070,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3215,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10013 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10013,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽3",
        "Effect1" : {
            1 : 60075,
            2 : 100,
            3 : -15,
            4 : 45,
        },
        "Speed" : 1,
        "Pic" : 3223,
        "ElementType" : 30,
        "Area" : {
            1 : 2,
            2 : 1,
        },
    },
    10006 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10006,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽6",
        "Effect1" : {
            1 : 60071,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3216,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10014 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10014,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽4",
        "Effect1" : {
            1 : 60073,
            2 : 100,
            3 : -5,
            4 : 20,
        },
        "Speed" : 1,
        "Pic" : 3224,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10007 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10007,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽7",
        "Effect1" : {
            1 : 60070,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3217,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    500101 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 500101,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "蜘蛛网",
        "Speed" : 1,
        "Pic" : "s2_3011001",
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10008 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10008,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽8",
        "Effect1" : {
            1 : 60071,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3218,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10001 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10001,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "1沼泽单格",
        "Effect1" : {
            1 : 60070,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3211,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10009 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10009,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽9",
        "Effect1" : {
            1 : 60072,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3219,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    100201 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 100201,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "土丘土",
        "Speed" : 1,
        "Pic" : "s1_3011012",
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10002 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10002,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽2",
        "Effect1" : {
            1 : 60070,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Speed" : 1,
        "Pic" : 3212,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    100101 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 100101,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "土丘草",
        "Speed" : 1,
        "Pic" : "s1_3011011",
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },

};
module.exports = _p;
