/*
Don't modify this file manually!
*/
var _p = {
    8001 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 49,
                5 : 1,
            },
        },
        "ElementType" : 8,
        "Pic1" : 800,
        "Genre" : 3,
        "Desc1" : 800,
        "Value" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : {
            1 : 1,
            2 : 1,
            3 : 1,
            4 : 1,
            5 : 1,
            6 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : 800,
        "Id" : 8001,
        "Obstacle" : 1,
        "GetInto" : 1,
        "Floors" : 5,
        "RestrictLose" : 0,
        "RestrictStep" : 0,
        "Name" : "锁妖塔",
        "Desc2" : 801,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "Resetting" : 0,
        "Reward" : 10017,
    },
    8002 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 49,
                5 : 1,
            },
        },
        "ElementType" : 8,
        "Pic1" : 801,
        "Genre" : 3,
        "Desc1" : 800,
        "Value" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : {
            1 : 1010,
            2 : 1011,
            3 : 1012,
            4 : 1013,
            5 : 1014,
        },
        "PickupLived" : 1,
        "Pic2" : 801,
        "Id" : 8002,
        "Obstacle" : 1,
        "GetInto" : 1,
        "Floors" : 5,
        "RestrictLose" : 0,
        "RestrictStep" : 0,
        "Name" : "锁妖塔",
        "Desc2" : 801,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "Resetting" : 0,
        "Reward" : 10017,
    },

};
module.exports = _p;
