-- excel xlstable format (sparse 3d matrix)
--{	[sheet1] = { [row1] = { [col1] = value, [col2] = value, ...},
--					 [row5] = { [col3] = value, }, },
--	[sheet2] = { [row9] = { [col9] = value, }},
--}
-- nameindex table
--{ [sheet,row,col name] = index, .. }
sheetname = {
["Sheet1"] = 1,
};

sheetindex = {
[1] = "Sheet1",
};

local effect = {
[1] = {
	["10001"] = {
		["effectid"] = 10001,
		["effectname"] = "贞德攻击",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skillstart_attack_01",
		["effectpath"] = "res/ANI/effect/effect_skillstart_attack_01/effect_skillstart_attack_01.ExportJson",
	},
	["10002"] = {
		["effectid"] = 10002,
		["effectname"] = "召唤发动1",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skillstart_summon_01",
		["effectpath"] = "res/ANI/effect/effect_skillstart_summon_01/effect_skillstart_summon_01.ExportJson",
	},
	["10003"] = {
		["effectid"] = 10003,
		["effectname"] = "多重施法特效",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skillstart_multi_01",
		["effectpath"] = "res/ANI/effect/effect_skillstart_multi_01/effect_skillstart_multi_01.ExportJson",
	},
	["10004"] = {
		["effectid"] = 10004,
		["effectname"] = "加状态特效",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skillstart_state_01",
		["effectpath"] = "res/ANI/effect/effect_skillstart_state_01/effect_skillstart_state_01.ExportJson",
	},
	["10005"] = {
		["effectid"] = 10005,
		["effectname"] = "召唤发动2",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skill_summon_01",
		["effectpath"] = "res/ANI/effect/effect_skill_summon_01/effect_skill_summon_01.ExportJson",
	},
	["10006"] = {
		["effectid"] = 10006,
		["effectname"] = "消失特效",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skill_disappear_01",
		["effectpath"] = "res/ANI/effect/effect_skill_disappear_01/effect_skill_disappear_01.ExportJson",
	},
	["10007"] = {
		["effectid"] = 10007,
		["effectname"] = "狮鹫普通攻击特效",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skillstart_attack_02",
		["effectpath"] = "res/ANI/effect/effect_skillstart_attack_02/effect_skillstart_attack_02.ExportJson",
	},
	["10008"] = {
		["effectid"] = 10008,
		["effectname"] = "圣系发动大特效",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_holy_03",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["10009"] = {
		["effectid"] = 10009,
		["effectname"] = "暗杀发动特效",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_assination_01",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["10010"] = {
		["effectid"] = 10010,
		["effectname"] = "雷神之锤发动",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_godhammer_01",
		["armature"] = "effect_skill_nature",
		["effectpath"] = "res/ANI/effect/effect_skill_nature/effect_skill_nature.ExportJson",
	},
	["10011"] = {
		["effectid"] = 10011,
		["effectname"] = "勇气护盾发动特效",
		["None"] = "torso",
		["audio"] = 3012,
		["mov"] = "effect_skillstart_holyshield_01",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["10012"] = {
		["effectid"] = 10012,
		["effectname"] = "压制攻击发动特效",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_strike_01",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["10013"] = {
		["effectid"] = 10013,
		["effectname"] = "圣系发动特效01",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_holy_01",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["10014"] = {
		["effectid"] = 10014,
		["effectname"] = "圣系发动特效02",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_holy_02",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["10015"] = {
		["effectid"] = 10015,
		["effectname"] = "暗系发动特效02",
		["None"] = "hip",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_dark_02",
		["armature"] = "effect_skill_dark",
		["effectpath"] = "res/ANI/effect/effect_skill_dark/effect_skill_dark.ExportJson",
	},
	["10016"] = {
		["effectid"] = 10016,
		["effectname"] = "暗系发动特效01",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_dark_01",
		["armature"] = "effect_skill_dark",
		["effectpath"] = "res/ANI/effect/effect_skill_dark/effect_skill_dark.ExportJson",
	},
	["10017"] = {
		["effectid"] = 10017,
		["effectname"] = "物理系发动特效02",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_strike_02",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["10018"] = {
		["effectid"] = 10018,
		["effectname"] = "自然系发动01",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_nature_01",
		["armature"] = "effect_skill_nature",
		["effectpath"] = "res/ANI/effect/effect_skill_nature/effect_skill_nature.ExportJson",
	},
	["10019"] = {
		["effectid"] = 10019,
		["effectname"] = "火系发起特效01",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_fire_01",
		["armature"] = "effect_skill_fire",
		["effectpath"] = "res/ANI/effect/effect_skill_fire/effect_skill_fire.ExportJson",
	},
	["10020"] = {
		["effectid"] = 10020,
		["effectname"] = "火系发起特效02",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_fire_02",
		["armature"] = "effect_skill_fire",
		["effectpath"] = "res/ANI/effect/effect_skill_fire/effect_skill_fire.ExportJson",
	},
	["10021"] = {
		["effectid"] = 10021,
		["effectname"] = "水系施法1",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "effect_skillstart_water_01",
		["armature"] = "effect_skill_water",
		["effectpath"] = "res/ANI/effect/effect_skill_water/effect_skill_water.ExportJson",
	},
	["20001"] = {
		["effectid"] = 20001,
		["effectname"] = "触发特效触发",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_state_mark_01",
		["effectpath"] = "res/ANI/effect/effect_state_mark_01/effect_state_mark_01.ExportJson",
	},
	["20002"] = {
		["effectid"] = 20002,
		["effectname"] = "多重施法主效果",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skill_multi_01",
		["effectpath"] = "res/ANI/effect/effect_skill_multi_01/effect_skill_multi_01.ExportJson",
	},
	["20003"] = {
		["effectid"] = 20003,
		["effectname"] = "战吼效果",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_state_battlecry_01",
		["effectpath"] = "res/ANI/effect/effect_state_battlecry_01/effect_state_battlecry_01.ExportJson",
	},
	["20004"] = {
		["effectid"] = 20004,
		["effectname"] = "死亡特效",
		["None"] = "hip",
		["audio"] = 3017,
		["mov"] = "Animation1",
		["armature"] = "effect_state_death_01",
		["effectpath"] = "res/ANI/effect/effect_state_death_01/effect_state_death_01.ExportJson",
	},
	["20005"] = {
		["effectid"] = 20005,
		["effectname"] = "暗杀主特效",
		["None"] = "root",
		["audio"] = 3002,
		["mov"] = "effect_skill_assination_01",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["20006"] = {
		["effectid"] = 20006,
		["effectname"] = "雷神之锤主特效",
		["None"] = "root",
		["audio"] = 3008,
		["mov"] = "effect_skill_godhammer_01",
		["armature"] = "effect_skill_nature",
		["effectpath"] = "res/ANI/effect/effect_skill_nature/effect_skill_nature.ExportJson",
	},
	["20007"] = {
		["effectid"] = 20007,
		["effectname"] = "勇气护盾主特效",
		["None"] = "torso",
		["audio"] = 3017,
		["mov"] = "effect_skill_holyshield_01",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["20008"] = {
		["effectid"] = 20008,
		["effectname"] = "压制攻击主特效",
		["None"] = "hip",
		["audio"] = 3017,
		["mov"] = "effect_skill_strike_01",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["20009"] = {
		["effectid"] = 20009,
		["effectname"] = "末日烈焰主特效",
		["None"] = "root",
		["audio"] = 3005,
		["mov"] = "effect_skill_doomfire_01",
		["armature"] = "effect_skill_fire",
		["effectpath"] = "res/ANI/effect/effect_skill_fire/effect_skill_fire.ExportJson",
	},
	["20010"] = {
		["effectid"] = 20010,
		["effectname"] = "血腥风暴主特效",
		["None"] = "hip",
		["audio"] = 3003,
		["mov"] = "effect_skill_bloodstorm_01",
		["armature"] = "effect_skill_dark",
		["effectpath"] = "res/ANI/effect/effect_skill_dark/effect_skill_dark.ExportJson",
	},
	["20011"] = {
		["effectid"] = 20011,
		["effectname"] = "物理系主特效02",
		["None"] = "torso",
		["audio"] = 3015,
		["mov"] = "effect_skill_strike_02",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["20012"] = {
		["effectid"] = 20012,
		["effectname"] = "物理系主特效03",
		["None"] = "root",
		["audio"] = 3016,
		["mov"] = "effect_skill_strike_03",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["20013"] = {
		["effectid"] = 20013,
		["effectname"] = "物理系主特效04",
		["None"] = "root",
		["audio"] = 3017,
		["mov"] = "effect_skill_strike_04",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["20014"] = {
		["effectid"] = 20014,
		["effectname"] = "圣系主特效01",
		["None"] = "root",
		["audio"] = 3009,
		["mov"] = "effect_skill_holy_01",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["20015"] = {
		["effectid"] = 20015,
		["effectname"] = "圣系主特效02",
		["None"] = "root",
		["audio"] = 3010,
		["mov"] = "effect_skill_holy_02",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["20016"] = {
		["effectid"] = 20016,
		["effectname"] = "圣系主特效03",
		["None"] = "root",
		["audio"] = 3011,
		["mov"] = "effect_skill_holy_03",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["20017"] = {
		["effectid"] = 20017,
		["effectname"] = "暗系主特效02",
		["None"] = "hip",
		["audio"] = 3004,
		["mov"] = "effect_skill_dark_02",
		["armature"] = "effect_skill_dark",
		["effectpath"] = "res/ANI/effect/effect_skill_dark/effect_skill_dark.ExportJson",
	},
	["20018"] = {
		["effectid"] = 20018,
		["effectname"] = "暗系主特效03",
		["None"] = "torso",
		["audio"] = 3003,
		["mov"] = "effect_skill_dark_03",
		["armature"] = "effect_skill_dark",
		["effectpath"] = "res/ANI/effect/effect_skill_dark/effect_skill_dark.ExportJson",
	},
	["20019"] = {
		["effectid"] = 20019,
		["effectname"] = "物理系主特效05",
		["None"] = "root",
		["audio"] = 3016,
		["mov"] = "effect_skill_strike_05",
		["armature"] = "effect_skill_physical",
		["effectpath"] = "res/ANI/effect/effect_skill_physical/effect_skill_physical.ExportJson",
	},
	["20020"] = {
		["effectid"] = 20020,
		["effectname"] = "自然系主特效01",
		["None"] = "fly",
		["audio"] = 3017,
		["mov"] = "effect_skill_nature_01",
		["armature"] = "effect_skill_nature",
		["effectpath"] = "res/ANI/effect/effect_skill_nature/effect_skill_nature.ExportJson",
	},
	["20021"] = {
		["effectid"] = 20021,
		["effectname"] = "自然系主特效02",
		["None"] = "root",
		["audio"] = 3008,
		["mov"] = "effect_skill_nature_02",
		["armature"] = "effect_skill_nature",
		["effectpath"] = "res/ANI/effect/effect_skill_nature/effect_skill_nature.ExportJson",
	},
	["20022"] = {
		["effectid"] = 20022,
		["effectname"] = "自然系主特效03",
		["None"] = "torso",
		["audio"] = 3013,
		["mov"] = "effect_skill_nature_03",
		["armature"] = "effect_skill_nature",
		["effectpath"] = "res/ANI/effect/effect_skill_nature/effect_skill_nature.ExportJson",
	},
	["20023"] = {
		["effectid"] = 20023,
		["effectname"] = "自然系主特效04",
		["None"] = "head",
		["audio"] = 3014,
		["mov"] = "effect_skill_nature_04",
		["armature"] = "effect_skill_nature",
		["effectpath"] = "res/ANI/effect/effect_skill_nature/effect_skill_nature.ExportJson",
	},
	["20024"] = {
		["effectid"] = 20024,
		["effectname"] = "火系主特效01",
		["None"] = "fly",
		["audio"] = 3006,
		["mov"] = "effect_skill_fire_01",
		["armature"] = "effect_skill_fire",
		["effectpath"] = "res/ANI/effect/effect_skill_fire/effect_skill_fire.ExportJson",
	},
	["20025"] = {
		["effectid"] = 20025,
		["effectname"] = "火系主特效02",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "effect_skill_fire_02",
		["armature"] = "effect_skill_fire",
		["effectpath"] = "res/ANI/effect/effect_skill_fire/effect_skill_fire.ExportJson",
	},
	["20026"] = {
		["effectid"] = 20026,
		["effectname"] = "暗系主特效01",
		["None"] = "torso",
		["audio"] = 3004,
		["mov"] = "effect_skill_dark_01",
		["armature"] = "effect_skill_dark",
		["effectpath"] = "res/ANI/effect/effect_skill_dark/effect_skill_dark.ExportJson",
	},
	["20027"] = {
		["effectid"] = 20027,
		["effectname"] = "火系主特效03",
		["None"] = "root",
		["audio"] = 3006,
		["mov"] = "effect_skill_fire_03",
		["armature"] = "effect_skill_fire",
		["effectpath"] = "res/ANI/effect/effect_skill_fire/effect_skill_fire.ExportJson",
	},
	["20028"] = {
		["effectid"] = 20028,
		["effectname"] = "群星坠落主特效",
		["None"] = "root",
		["audio"] = 3018,
		["mov"] = "effect_skill_starfall_01",
		["armature"] = "effect_skill_water",
		["effectpath"] = "res/ANI/effect/effect_skill_water/effect_skill_water.ExportJson",
	},
	["20029"] = {
		["effectid"] = 20029,
		["effectname"] = "水系命中1",
		["None"] = "root",
		["audio"] = 3018,
		["mov"] = "effect_skill_water_01",
		["armature"] = "effect_skill_water",
		["effectpath"] = "res/ANI/effect/effect_skill_water/effect_skill_water.ExportJson",
	},
	["20030"] = {
		["effectid"] = 20030,
		["effectname"] = "水系命中2(冰)",
		["None"] = "root",
		["audio"] = 3018,
		["mov"] = "effect_skill_water_02",
		["armature"] = "effect_skill_water",
		["effectpath"] = "res/ANI/effect/effect_skill_water/effect_skill_water.ExportJson",
	},
	["20031"] = {
		["effectid"] = 20031,
		["effectname"] = "水系命中3（冰）",
		["None"] = "root",
		["audio"] = 3018,
		["mov"] = "effect_skill_water_03",
		["armature"] = "effect_skill_water",
		["effectpath"] = "res/ANI/effect/effect_skill_water/effect_skill_water.ExportJson",
	},
	["20032"] = {
		["effectid"] = 20032,
		["effectname"] = "水系命中4",
		["None"] = "fly",
		["audio"] = 3018,
		["mov"] = "effect_skill_water_04",
		["armature"] = "effect_skill_water",
		["effectpath"] = "res/ANI/effect/effect_skill_water/effect_skill_water.ExportJson",
	},
	["40001"] = {
		["effectid"] = 40001,
		["effectname"] = "物理攻击受击1",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skillend_attack_01",
		["effectpath"] = "res/ANI/effect/effect_skillend_attack_01/effect_skillend_attack_01.ExportJson",
	},
	["40002"] = {
		["effectid"] = 40002,
		["effectname"] = "狮鹫攻击受击",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skillend_attack_02",
		["effectpath"] = "res/ANI/effect/effect_skillend_attack_02/effect_skillend_attack_02.ExportJson",
	},
	["40003"] = {
		["effectid"] = 40003,
		["effectname"] = "毒攻击受击1",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_skillend_poison_01",
		["effectpath"] = "res/ANI/effect/effect_skillend_poison_01/effect_skillend_poison_01.ExportJson",
	},
	["40004"] = {
		["effectid"] = 40004,
		["effectname"] = "受到治疗1",
		["None"] = "torso",
		["audio"] = 3012,
		["mov"] = "Animation1",
		["armature"] = "effect_skillstart_recover_01",
		["effectpath"] = "res/ANI/effect/effect_skillstart_recover_01/effect_skillstart_recover_01.ExportJson",
	},
	["40005"] = {
		["effectid"] = 40005,
		["effectname"] = "多重施法命中",
		["None"] = "torso",
		["audio"] = 3012,
		["mov"] = "Animation1",
		["armature"] = "effect_skillend_multi_01",
		["effectpath"] = "res/ANI/effect/effect_skillend_multi_01/effect_skillend_multi_01.ExportJson",
	},
	["40006"] = {
		["effectid"] = 40006,
		["effectname"] = "神之怒受击特效",
		["None"] = "root",
		["audio"] = 3007,
		["mov"] = "effect_skillend_godanger_01",
		["armature"] = "effect_skill_holy",
		["effectpath"] = "res/ANI/effect/effect_skill_holy/effect_skill_holy.ExportJson",
	},
	["40007"] = {
		["effectid"] = 40007,
		["effectname"] = "怪物攻击受击特效",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "attack01",
		["armature"] = "effect_skillend_attack_03",
		["effectpath"] = "res/ANI/effect/effect_skillend_attack_03/effect_skillend_attack_03.ExportJson",
	},
	["40008"] = {
		["effectid"] = 40008,
		["effectname"] = "普通攻击lv2",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "attack02",
		["armature"] = "effect_skillend_attack_03",
		["effectpath"] = "res/ANI/effect/effect_skillend_attack_03/effect_skillend_attack_03.ExportJson",
	},
	["40009"] = {
		["effectid"] = 40009,
		["effectname"] = "普通攻击lv3",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "attack03",
		["armature"] = "effect_skillend_attack_03",
		["effectpath"] = "res/ANI/effect/effect_skillend_attack_03/effect_skillend_attack_03.ExportJson",
	},
	["50001"] = {
		["effectid"] = 50001,
		["effectname"] = "护盾",
		["None"] = "torso",
		["audio"] = 3012,
		["mov"] = "Animation1",
		["armature"] = "effect_state_shield_01",
		["effectpath"] = "res/ANI/effect/effect_state_shield_01/effect_state_shield_01.ExportJson",
	},
	["50002"] = {
		["effectid"] = 50002,
		["effectname"] = "增益buff",
		["None"] = "root",
		["audio"] = 2004,
		["mov"] = "Animation1",
		["armature"] = "effect_state_buff_01",
		["effectpath"] = "res/ANI/effect/effect_state_buff_01/effect_state_buff_01.ExportJson",
	},
	["50003"] = {
		["effectid"] = 50003,
		["effectname"] = "减益buff",
		["None"] = "root",
		["audio"] = 2001,
		["mov"] = "Animation1",
		["armature"] = "effect_state_debuff_01",
		["effectpath"] = "res/ANI/effect/effect_state_debuff_01/effect_state_debuff_01.ExportJson",
	},
	["50004"] = {
		["effectid"] = 50004,
		["effectname"] = "昏迷",
		["None"] = "head",
		["audio"] = 3017,
		["mov"] = "Animation1",
		["armature"] = "effect_state_coma_01",
		["effectpath"] = "res/ANI/effect/effect_state_coma_01/effect_state_coma_01.ExportJson",
	},
	["50006"] = {
		["effectid"] = 50006,
		["effectname"] = "冰护盾状态",
		["None"] = "hip",
		["audio"] = 3017,
		["mov"] = "Animation1",
		["armature"] = "effect_state_iceshield_01",
		["effectpath"] = "res/ANI/effect/effect_state_iceshield_01/effect_state_iceshield_01.ExportJson",
	},
	["50007"] = {
		["effectid"] = 50007,
		["effectname"] = "嘲讽状态",
		["None"] = "head",
		["audio"] = 3017,
		["mov"] = "Animation1",
		["armature"] = "effect_state_turnt_01",
		["effectpath"] = "res/ANI/effect/effect_state_turnt_01/effect_state_turnt_01.ExportJson",
	},
	["50008"] = {
		["effectid"] = 50008,
		["effectname"] = "被冰冻状态",
		["None"] = "root",
		["audio"] = 3017,
		["mov"] = "Animation1",
		["armature"] = "effect_state_frozen_01",
		["effectpath"] = "res/ANI/effect/effect_state_frozen_01/effect_state_frozen_01.ExportJson",
	},
	["50009"] = {
		["effectid"] = 50009,
		["effectname"] = "魔法护盾",
		["None"] = "hip",
		["audio"] = 3017,
		["mov"] = "Animation1",
		["armature"] = "effect_state_magiclmmune_01",
		["effectpath"] = "res/ANI/effect/effect_state_magiclmmune_01/effect_state_magiclmmune_01.ExportJson",
	},
	["60001"] = {
		["effectid"] = 60001,
		["effectname"] = "水晶增加",
		["None"] = "special",
		["audio"] = 2001,
		["mov"] = "add",
		["armature"] = "effect_crystal_01",
		["effectpath"] = "res/ANI/effect/effect_crystal_01/effect_crystal_01.ExportJson",
	},
	["60002"] = {
		["effectid"] = 60002,
		["effectname"] = "水晶消耗",
		["None"] = "special",
		["mov"] = "use",
		["armature"] = "effect_crystal_01",
		["effectpath"] = "res/ANI/effect/effect_crystal_01/effect_crystal_01.ExportJson",
	},
	["60003"] = {
		["effectid"] = 60003,
		["effectname"] = "水晶填满",
		["None"] = "special",
		["mov"] = "full",
		["armature"] = "effect_crystal_01",
		["effectpath"] = "res/ANI/effect/effect_crystal_01/effect_crystal_01.ExportJson",
	},
	["60004"] = {
		["effectid"] = 60004,
		["effectname"] = "连携主特效",
		["None"] = "special",
		["audio"] = 3001,
		["mov"] = "Animation1",
		["armature"] = "effect_combo_01",
		["effectpath"] = "res/ANI/effect/effect_combo_01/effect_combo_01.ExportJson",
	},
	["60005"] = {
		["effectid"] = 60005,
		["effectname"] = "连携角色特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_combo_role_01",
		["effectpath"] = "res/ANI/effect/effect_combo_role_01/effect_combo_role_01.ExportJson",
	},
	["60006"] = {
		["effectid"] = 60006,
		["effectname"] = "升级特效",
		["None"] = "root",
		["mov"] = "Animation1",
		["armature"] = "effect_upgrade_01",
		["effectpath"] = "res/ANI/effect/effect_upgrade_01/effect_upgrade_01.ExportJson",
	},
	["60007"] = {
		["effectid"] = 60007,
		["effectname"] = "打造装备飞入背包效果",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_iteminbag_01",
		["effectpath"] = "res/ANI/effect/effect_iteminbag_01/effect_iteminbag_01.ExportJson",
	},
	["60008"] = {
		["effectid"] = 60008,
		["effectname"] = "装备飞散时的炼成爆炸效果",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_foundry_equipbgexplode_01",
		["effectpath"] = "res/ANI/effect/effect_foundry_equipbgexplode_01/effect_foundry_equipbgexplode_01.ExportJson",
	},
	["60009"] = {
		["effectid"] = 60009,
		["effectname"] = "装备飞散前装备上特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_foundry_equipbg_01",
		["effectpath"] = "res/ANI/effect/effect_foundry_equipbg_01/effect_foundry_equipbg_01.ExportJson",
	},
	["60010"] = {
		["effectid"] = 60010,
		["effectname"] = "橙色装备被点开时特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_open_orangecard_01",
		["effectpath"] = "res/ANI/effect/effect_open_orangecard_01/effect_open_orangecard_01.ExportJson",
	},
	["60011"] = {
		["effectid"] = 60011,
		["effectname"] = "装备背景特效（需要程序上色）",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_bg_whitecard_01",
		["effectpath"] = "res/ANI/effect/effect_bg_whitecard_01/effect_bg_whitecard_01.ExportJson",
	},
	["60012"] = {
		["effectid"] = 60012,
		["effectname"] = "橙色装备背景特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_bg_orangecard_01",
		["effectpath"] = "res/ANI/effect/effect_bg_orangecard_01/effect_bg_orangecard_01.ExportJson",
	},
	["60013"] = {
		["effectid"] = 60013,
		["effectname"] = "打造界面配方外发光",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_bg_formulaout_01",
		["effectpath"] = "res/ANI/effect/effect_bg_formulaout_01/effect_bg_formulaout_01.ExportJson",
	},
	["60014"] = {
		["effectid"] = 60014,
		["effectname"] = "4个材料的配方打造效果",
		["None"] = "special",
		["mov"] = "foundry4element",
		["armature"] = "effect_foundry_start_01",
		["effectpath"] = "res/ANI/effect/effect_foundry_start_01/effect_foundry_start_01.ExportJson",
	},
	["60015"] = {
		["effectid"] = 60015,
		["effectname"] = "3个材料的配方打造效果",
		["None"] = "special",
		["mov"] = "foundry3element",
		["armature"] = "effect_foundry_start_01",
		["effectpath"] = "res/ANI/effect/effect_foundry_start_01/effect_foundry_start_01.ExportJson",
	},
	["60016"] = {
		["effectid"] = 60016,
		["effectname"] = "2个材料的配方打造效果",
		["None"] = "special",
		["mov"] = "foundry3element",
		["armature"] = "effect_foundry_start_01",
		["effectpath"] = "res/ANI/effect/effect_foundry_start_01/effect_foundry_start_01.ExportJson",
	},
	["60017"] = {
		["effectid"] = 60017,
		["effectname"] = "淬炼界面合成时爆炸效果",
		["None"] = "special",
		["mov"] = "pickupexplode",
		["armature"] = "effect_foundry_start_01",
		["effectpath"] = "res/ANI/effect/effect_foundry_start_01/effect_foundry_start_01.ExportJson",
	},
	["60018"] = {
		["effectid"] = 60018,
		["effectname"] = "淬炼主装备的外边框",
		["None"] = "special",
		["mov"] = "mainequip",
		["armature"] = "effect_pickup_equip_01",
		["effectpath"] = "res/ANI/effect/effect_pickup_equip_01/effect_pickup_equip_01.ExportJson",
	},
	["60019"] = {
		["effectid"] = 60019,
		["effectname"] = "淬炼被消耗装备的外边框",
		["None"] = "special",
		["mov"] = "pickequip",
		["armature"] = "effect_pickup_equip_01",
		["effectpath"] = "res/ANI/effect/effect_pickup_equip_01/effect_pickup_equip_01.ExportJson",
	},
	["60020"] = {
		["effectid"] = 60020,
		["effectname"] = "装备普通升星成功",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_equipupgrade_success_01",
		["effectpath"] = "res/ANI/effect/effect_equipupgrade_success_01/effect_equipupgrade_success_01.ExportJson",
	},
	["60021"] = {
		["effectid"] = 60021,
		["effectname"] = "装备普通升星失败",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_equipupgrade_fail_01",
		["effectpath"] = "res/ANI/effect/effect_equipupgrade_fail_01/effect_equipupgrade_fail_01.ExportJson",
	},
	["60022"] = {
		["effectid"] = 60022,
		["effectname"] = "装备5星升星材料光爆",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_equipupgrade_lv5me_01",
		["effectpath"] = "res/ANI/effect/effect_equipupgrade_lv5me_01/effect_equipupgrade_lv5me_01.ExportJson",
	},
	["60023"] = {
		["effectid"] = 60023,
		["effectname"] = "装备5星升星材料初始闪烁",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_equipupgrade_lv5ml_01",
		["effectpath"] = "res/ANI/effect/effect_equipupgrade_lv5ml_01/effect_equipupgrade_lv5ml_01.ExportJson",
	},
	["60024"] = {
		["effectid"] = 60024,
		["effectname"] = "装备5星升星背景成功光效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_equipupgrade_bgs_01",
		["effectpath"] = "res/ANI/effect/effect_equipupgrade_bgs_01/effect_equipupgrade_bgs_01.ExportJson",
	},
	["60025"] = {
		["effectid"] = 60025,
		["effectname"] = "装备5星升星背景失败光效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_equipupgrade_bgf_01",
		["effectpath"] = "res/ANI/effect/effect_equipupgrade_bgf_01/effect_equipupgrade_bgf_01.ExportJson",
	},
	["60026"] = {
		["effectid"] = 60026,
		["effectname"] = "装备5星升星材料边框",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_equipupgrade_lv5mb_01",
		["effectpath"] = "res/ANI/effect/effect_equipupgrade_lv5mb_01/effect_equipupgrade_lv5mb_01.ExportJson",
	},
	["60027"] = {
		["effectid"] = 60027,
		["effectname"] = "可以消除障碍标志",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_grid_01",
		["effectpath"] = "res/ANI/effect/effect_map_grid_01effect_map_grid_01.ExportJson",
	},
	["60028"] = {
		["effectid"] = 60028,
		["effectname"] = "传送门蓝色大门",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_portal_01",
		["effectpath"] = "res/ANI/effect/effect_map_portal_01/effect_map_portal_01.ExportJson",
	},
	["60029"] = {
		["effectid"] = 60029,
		["effectname"] = "传送门橘色地面",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_portal_02",
		["effectpath"] = "res/ANI/effect/effect_map_portal_02/effect_map_portal_02.ExportJson",
	},
	["60030"] = {
		["effectid"] = 60030,
		["effectname"] = "障碍物消失",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_blockdisappear_01",
		["effectpath"] = "res/ANI/effect/effect_map_blockdisappear_01/effect_map_blockdisappear_01.ExportJson",
	},
	["60031"] = {
		["effectid"] = 60031,
		["effectname"] = "沼泽地块特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_swamp_01",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_01/effect_map_swamp_01.ExportJson",
	},
	["60032"] = {
		["effectid"] = 60032,
		["effectname"] = "挂机特效1",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_hangup_01",
		["effectpath"] = "res/ANI/effect/effect_map_hangup_01/effect_map_hangup_01.ExportJson",
	},
	["60033"] = {
		["effectid"] = 60033,
		["effectname"] = "挂机特效2",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_hangup_02",
		["effectpath"] = "res/ANI/effect/effect_map_hangup_02/effect_map_hangup_02.ExportJson",
	},
	["60034"] = {
		["effectid"] = 60034,
		["effectname"] = "角色高级升品主要特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_cha_main_quliaty_01",
		["effectpath"] = "res/ANI/effect/effect_cha_main_quliaty_01/effect_cha_main_quliaty_01.ExportJson",
	},
	["60035"] = {
		["effectid"] = 60035,
		["effectname"] = "角色升星的主要特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_cha_main_upgrade_01",
		["effectpath"] = "res/ANI/effect/effect_cha_main_upgrade_01/effect_cha_main_upgrade_01.ExportJson",
	},
	["60036"] = {
		["effectid"] = 60036,
		["effectname"] = "角色普通升品特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_cha_single_quliaty_01",
		["effectpath"] = "res/ANI/effect/effect_cha_single_quliaty_01/effect_cha_single_quliaty_01.ExportJson",
	},
	["60037"] = {
		["effectid"] = 60037,
		["effectname"] = "道具获得特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_item_get_01",
		["effectpath"] = "res/ANI/effect/effect_item_get_01/effect_item_get_01.ExportJson",
	},
	["60038"] = {
		["effectid"] = 60038,
		["effectname"] = "角色召唤",
		["None"] = "root",
		["mov"] = "Animation1",
		["armature"] = "effect_cha_summon_01",
		["effectpath"] = "res/ANI/effect/effect_cha_summon_01/effect_cha_summon_01.ExportJson",
	},
	["60039"] = {
		["effectid"] = 60039,
		["effectname"] = "道具选中效果",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_item_select_01",
		["effectpath"] = "res/ANI/effect/effect_item_select_01/effect_item_select_01.ExportJson",
	},
	["60040"] = {
		["effectid"] = 60040,
		["effectname"] = "合体技特效上层",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_uniteskill_up_01",
		["effectpath"] = "res/ANI/effect/effect_uniteskill_up_01/effect_uniteskill_up_01.ExportJson",
	},
	["60041"] = {
		["effectid"] = 60041,
		["effectname"] = "合体技特效下层",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_uniteskill_down_01",
		["effectpath"] = "res/ANI/effect/effect_uniteskill_down_01/effect_uniteskill_down_01.ExportJson",
	},
	["60042"] = {
		["effectid"] = 60042,
		["effectname"] = "金钱增加",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_add_money_01",
		["effectpath"] = "res/ANI/effect/effect_add_money_01/effect_add_money_01.ExportJson",
	},
	["60043"] = {
		["effectid"] = 60043,
		["effectname"] = "经验增加光点",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_add_exppoint_01",
		["effectpath"] = "res/ANI/effect/effect_add_exppoint_01/effect_add_exppoint_01.ExportJson",
	},
	["60044"] = {
		["effectid"] = 60044,
		["effectname"] = "经验增加刷光",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_add_exp_01",
		["effectpath"] = "res/ANI/effect/effect_add_exp_01/effect_add_exp_01.ExportJson",
	},
	["60047"] = {
		["effectid"] = 60047,
		["effectname"] = "建筑特效1瞭望塔",
		["None"] = "0,92",
		["mov"] = "Animation1",
		["armature"] = "effect_building_01_01",
		["effectpath"] = "res/ANI/effect/effect_building_01_01/effect_building_01_01.ExportJson",
	},
	["60048"] = {
		["effectid"] = 60048,
		["effectname"] = "建筑特效2商店",
		["None"] = "-17.5,109.5",
		["mov"] = "Animation1",
		["armature"] = "effect_building_01_02",
		["effectpath"] = "res/ANI/effect/effect_building_01_02/effect_building_01_02.ExportJson",
	},
	["60049"] = {
		["effectid"] = 60049,
		["effectname"] = "建筑特效3buff点",
		["None"] = "0,49",
		["mov"] = "Animation1",
		["armature"] = "effect_building_01_03",
		["effectpath"] = "res/ANI/effect/effect_building_01_03/effect_building_01_03.ExportJson",
	},
	["60050"] = {
		["effectid"] = 60050,
		["effectname"] = "建筑特效4",
		["None"] = 9110.50000000,
		["mov"] = "Animation1",
		["armature"] = "effect_building_02_01",
		["effectpath"] = "res/ANI/effect/effect_building_02_01/effect_building_02_01.ExportJson",
	},
	["60051"] = {
		["effectid"] = 60051,
		["effectname"] = "建筑特效5",
		["None"] = 100110,
		["mov"] = "Animation1",
		["armature"] = "effect_building_02_02",
		["effectpath"] = "res/ANI/effect/effect_building_02_02/effect_building_02_02.ExportJson",
	},
	["60052"] = {
		["effectid"] = 60052,
		["effectname"] = "建筑特效6",
		["None"] = "0,101",
		["mov"] = "Animation1",
		["armature"] = "effect_building_02_03",
		["effectpath"] = "res/ANI/effect/effect_building_02_03/effect_building_02_03.ExportJson",
	},
	["60053"] = {
		["effectid"] = 60053,
		["effectname"] = "建筑特效7",
		["None"] = "0,83",
		["mov"] = "Animation1",
		["armature"] = "effect_building_02_05",
		["effectpath"] = "res/ANI/effect/effect_building_02_05/effect_building_02_05.ExportJson",
	},
	["60054"] = {
		["effectid"] = 60054,
		["effectname"] = "建筑特效8",
		["None"] = "0,151",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_01",
		["effectpath"] = "res/ANI/effect/effect_building_03_01/effect_building_03_01.ExportJson",
	},
	["60055"] = {
		["effectid"] = 60055,
		["effectname"] = "建筑特效9",
		["None"] = "0,131",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_02",
		["effectpath"] = "res/ANI/effect/effect_building_03_02/effect_building_03_02.ExportJson",
	},
	["60056"] = {
		["effectid"] = 60056,
		["effectname"] = "建筑特效10",
		["None"] = "0,104.5",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_03",
		["effectpath"] = "res/ANI/effect/effect_building_03_03/effect_building_03_03.ExportJson",
	},
	["60057"] = {
		["effectid"] = 60057,
		["effectname"] = "建筑特效11",
		["None"] = "0,156.5",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_04",
		["effectpath"] = "res/ANI/effect/effect_building_03_04/effect_building_03_04.ExportJson",
	},
	["60058"] = {
		["effectid"] = 60058,
		["effectname"] = "建筑特效12",
		["None"] = "0,171",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_05",
		["effectpath"] = "res/ANI/effect/effect_building_03_05/effect_building_03_05.ExportJson",
	},
	["60059"] = {
		["effectid"] = 60059,
		["effectname"] = "建筑特效13",
		["None"] = "0,113",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_06",
		["effectpath"] = "res/ANI/effect/effect_building_03_06/effect_building_03_06.ExportJson",
	},
	["60060"] = {
		["effectid"] = 60060,
		["effectname"] = "建筑特效14",
		["None"] = "0,113",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_07",
		["effectpath"] = "res/ANI/effect/effect_building_03_07/effect_building_03_07.ExportJson",
	},
	["60061"] = {
		["effectid"] = 60061,
		["effectname"] = "建筑特效15",
		["None"] = "0,117",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_08",
		["effectpath"] = "res/ANI/effect/effect_building_03_08/effect_building_03_08.ExportJson",
	},
	["60062"] = {
		["effectid"] = 60062,
		["effectname"] = "宝箱特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_building_03_09",
		["effectpath"] = "res/ANI/effect/effect_building_03_09/effect_building_03_09.ExportJson",
	},
	["60063"] = {
		["effectid"] = 60063,
		["effectname"] = "地图npc对话1",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_npc_01",
		["effectpath"] = "res/ANI/effect/effect_map_npc_01/effect_map_npc_01.ExportJson",
	},
	["60064"] = {
		["effectid"] = 60064,
		["effectname"] = "地图npc对话2",
		["None"] = "special",
		["mov"] = "Animation2",
		["armature"] = "effect_map_npc_01",
		["effectpath"] = "res/ANI/effect/effect_map_npc_01/effect_map_npc_01.ExportJson",
	},
	["60065"] = {
		["effectid"] = 60065,
		["effectname"] = "地图怪物对话1",
		["None"] = "special",
		["mov"] = "Animation3",
		["armature"] = "effect_map_npc_01",
		["effectpath"] = "res/ANI/effect/effect_map_npc_01/effect_map_npc_01.ExportJson",
	},
	["60066"] = {
		["effectid"] = 60066,
		["effectname"] = "地图怪物对话2",
		["None"] = "special",
		["mov"] = "Animation4",
		["armature"] = "effect_map_npc_01",
		["effectpath"] = "res/ANI/effect/effect_map_npc_01/effect_map_npc_01.ExportJson",
	},
	["60067"] = {
		["effectid"] = 60067,
		["effectname"] = "挂机宝箱可以打开特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_rewardcage_canopen_01",
		["effectpath"] = "res/ANI/effect/effect_rewardcage_canopen_01/effect_rewardcage_canopen_01.ExportJson",
	},
	["60068"] = {
		["effectid"] = 60068,
		["effectname"] = "挂机宝箱打开特效",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_rewardcage_open_01",
		["effectpath"] = "res/ANI/effect/effect_rewardcage_open_01/effect_rewardcage_open_01.ExportJson",
	},
	["60069"] = {
		["effectid"] = 60069,
		["effectname"] = "建筑特效16",
		["None"] = "0,142",
		["mov"] = "Animation1",
		["armature"] = "effect_building_01_04",
		["effectpath"] = "res/ANI/effect/effect_building_01_04/effect_building_01_04.ExportJson",
	},
	["60070"] = {
		["effectid"] = 60070,
		["effectname"] = "沼泽特效1绿",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_map_swamp_02",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_02/effect_map_swamp_02.ExportJson",
	},
	["60071"] = {
		["effectid"] = 60071,
		["effectname"] = "沼泽特效2绿",
		["None"] = "special",
		["mov"] = "Animation2",
		["armature"] = "effect_map_swamp_02",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_02/effect_map_swamp_02.ExportJson",
	},
	["60072"] = {
		["effectid"] = 60072,
		["effectname"] = "沼泽特效3绿",
		["None"] = "special",
		["mov"] = "Animation3",
		["armature"] = "effect_map_swamp_02",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_02/effect_map_swamp_02.ExportJson",
	},
	["60073"] = {
		["effectid"] = 60073,
		["effectname"] = "沼泽特效4蓝",
		["None"] = "special",
		["mov"] = "Animation4",
		["armature"] = "effect_map_swamp_02",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_02/effect_map_swamp_02.ExportJson",
	},
	["60074"] = {
		["effectid"] = 60074,
		["effectname"] = "沼泽特效5蓝",
		["None"] = "special",
		["mov"] = "Animation5",
		["armature"] = "effect_map_swamp_02",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_02/effect_map_swamp_02.ExportJson",
	},
	["60075"] = {
		["effectid"] = 60075,
		["effectname"] = "沼泽特效6蓝",
		["None"] = "special",
		["mov"] = "Animation6",
		["armature"] = "effect_map_swamp_02",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_02/effect_map_swamp_02.ExportJson",
	},
	["60076"] = {
		["effectid"] = 60076,
		["effectname"] = "沼泽特效7蓝左",
		["None"] = "special",
		["mov"] = "Animation7",
		["armature"] = "effect_map_swamp_02",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_02/effect_map_swamp_02.ExportJson",
	},
	["60077"] = {
		["effectid"] = 60077,
		["effectname"] = "沼泽特效8蓝左",
		["None"] = "special",
		["mov"] = "Animation8",
		["armature"] = "effect_map_swamp_02",
		["effectpath"] = "res/ANI/effect/effect_map_swamp_02/effect_map_swamp_02.ExportJson",
	},
	["60078"] = {
		["effectid"] = 60078,
		["effectname"] = "宝箱白",
		["None"] = " 5，31.5",
		["mov"] = "Animation1",
		["armature"] = "effect_building_rewardbox_01",
		["effectpath"] = "res/ANI/effect/effect_building_rewardbox_01/effect_building_rewardbox_01.ExportJson",
	},
	["60079"] = {
		["effectid"] = 60079,
		["effectname"] = "宝箱金",
		["None"] = "0,36.5",
		["mov"] = "Animation1",
		["armature"] = "effect_building_rewardbox_02",
		["effectpath"] = "res/ANI/effect/effect_building_rewardbox_02/effect_building_rewardbox_02.ExportJson",
	},
	["60080"] = {
		["effectid"] = 60080,
		["effectname"] = "宝箱蓝",
		["None"] = "0,41",
		["mov"] = "Animation1",
		["armature"] = "effect_building_rewardbox_03",
		["effectpath"] = "res/ANI/effect/effect_building_rewardbox_03/effect_building_rewardbox_03.ExportJson",
	},
	["60081"] = {
		["effectid"] = 60081,
		["effectname"] = "宝箱紫",
		["None"] = "0,38",
		["mov"] = "Animation1",
		["armature"] = "effect_building_rewardbox_04",
		["effectpath"] = "res/ANI/effect/effect_building_rewardbox_04/effect_building_rewardbox_04.ExportJson",
	},
	["60082"] = {
		["effectid"] = 60082,
		["effectname"] = "宝箱白金",
		["None"] = "0,33.5",
		["mov"] = "Animation1",
		["armature"] = "effect_building_rewardbox_05",
		["effectpath"] = "res/ANI/effect/effect_building_rewardbox_05/effect_building_rewardbox_05.ExportJson",
	},
	["60083"] = {
		["effectid"] = 60083,
		["effectname"] = "战斗界面主按钮召唤",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_ui_mainbuttonup_01",
		["effectpath"] = "res/ANI/effect/effect_ui_mainbuttonup_01/effect_ui_mainbuttonup_01.ExportJson",
	},
	["60084"] = {
		["effectid"] = 60084,
		["effectname"] = "技能获得刷光",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_skill_get_01",
		["effectpath"] = "res/ANI/effect/effect_skill_get_01/effect_skill_get_01.ExportJson",
	},
	["60085"] = {
		["effectid"] = 60085,
		["effectname"] = "地图npc对话3",
		["None"] = "special",
		["mov"] = "Animation5",
		["armature"] = "effect_map_npc_01",
		["effectpath"] = "res/ANI/effect/effect_map_npc_01/effect_map_npc_01.ExportJson",
	},
	["60086"] = {
		["effectid"] = 60086,
		["effectname"] = "新手引导光圈",
		["None"] = "special",
		["mov"] = "Animation1",
		["armature"] = "effect_beginnerguide_01",
		["effectpath"] = "res/ANI/effect/effect_beginnerguide_01/effect_beginnerguide_01.ExportJson",
	},
	["60087"] = {
		["effectid"] = 60087,
		["effectname"] = "战斗卡牌选中光效",
		["None"] = "special",
		["mov"] = "normal",
		["armature"] = "effect_fight_skillcard_01",
		["effectpath"] = "res/ANI/effect/effect_fight_skillcard_01/effect_fight_skillcard_01.ExportJson",
	},
	["60088"] = {
		["effectid"] = 60088,
		["effectname"] = "战斗卡牌飞行光效",
		["None"] = "special",
		["mov"] = "fly",
		["armature"] = "effect_fight_skillcard_01",
		["effectpath"] = "res/ANI/effect/effect_fight_skillcard_01/effect_fight_skillcard_01.ExportJson",
	},
	["70001"] = {
		["effectid"] = 70001,
		["effectname"] = "临时攻击特效1",
		["None"] = "torso",
		["audio"] = 3006,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_01",
		["effectpath"] = "res/ANI/effect/effect_temp_01/effect_temp_01.ExportJson",
	},
	["70002"] = {
		["effectid"] = 70002,
		["effectname"] = "临时受击特效1",
		["None"] = "torso",
		["audio"] = 3007,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_02",
		["effectpath"] = "res/ANI/effect/effect_temp_02/effect_temp_02.ExportJson",
	},
	["70003"] = {
		["effectid"] = 70003,
		["effectname"] = "临时受击特效2",
		["None"] = "torso",
		["audio"] = 3008,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_03",
		["effectpath"] = "res/ANI/effect/effect_temp_03/effect_temp_03.ExportJson",
	},
	["70004"] = {
		["effectid"] = 70004,
		["effectname"] = "临时中毒特效",
		["None"] = "torso",
		["audio"] = 3009,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_04",
		["effectpath"] = "res/ANI/effect/effect_temp_04/effect_temp_04.ExportJson",
	},
	["70005"] = {
		["effectid"] = 70005,
		["effectname"] = "临时召唤特效1",
		["None"] = "torso",
		["audio"] = 3010,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_05",
		["effectpath"] = "res/ANI/effect/effect_temp_05/effect_temp_05.ExportJson",
	},
	["70006"] = {
		["effectid"] = 70006,
		["effectname"] = "临时治疗特效1",
		["None"] = "torso",
		["audio"] = 3011,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_06",
		["effectpath"] = "res/ANI/effect/effect_temp_06/effect_temp_06.ExportJson",
	},
	["70007"] = {
		["effectid"] = 70007,
		["effectname"] = "临时飞行特效",
		["None"] = "torso",
		["audio"] = 3012,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_07",
		["effectpath"] = "res/ANI/effect/effect_temp_07/effect_temp_07.ExportJson",
	},
	["70008"] = {
		["effectid"] = 70008,
		["effectname"] = "临时闪电击中",
		["None"] = "torso",
		["audio"] = 3013,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_08",
		["effectpath"] = "res/ANI/effect/effect_temp_08/effect_temp_08.ExportJson",
	},
	["70009"] = {
		["effectid"] = 70009,
		["effectname"] = "临时闪电发动",
		["None"] = "torso",
		["audio"] = 3014,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_09",
		["effectpath"] = "res/ANI/effect/effect_temp_09/effect_temp_09.ExportJson",
	},
	["70010"] = {
		["effectid"] = 70010,
		["effectname"] = "闪电小combo",
		["None"] = "torso",
		["audio"] = 3015,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_10",
		["effectpath"] = "res/ANI/effect/effect_temp_10/effect_temp_10.ExportJson",
	},
	["70011"] = {
		["effectid"] = 70011,
		["effectname"] = "闪电大combo",
		["None"] = "torso",
		["audio"] = 3016,
		["mov"] = "Animation1",
		["armature"] = "effect_temp_11",
		["effectpath"] = "res/ANI/effect/effect_temp_11/effect_temp_11.ExportJson",
	},
	["70014"] = {
		["effectid"] = 70014,
		["effectname"] = "飞行状态添加",
		["None"] = "root",
		["mov"] = "Animation1",
		["armature"] = "effect_temp_14",
		["effectpath"] = "res/ANI/effect/effect_temp_14/effect_temp_14.ExportJson",
	},
},
};


return effect[1]
