--[[
Don't modify this file manually!
]]
local _p = {
    [2000] = {
        ["rspid"] = { "2001" },
        ["keys"] = { "time" },
        ["target"] = { "conn" },
        ["func"] = { "heartBeat" },
        ["types"] = { "i" },
    },
    [8000] = {
        ["rspid"] = { "8001" },
        ["keys"] = { "sellgroup" },
        ["target"] = { "loc" },
        ["func"] = { "sellItemGroup" },
        ["types"] = { "s" },
    },
    [8001] = {
        ["keys"] = { "cost" },
        ["types"] = { "i" },
    },
    [8002] = {
        ["rspid"] = { "8003" },
        ["keys"] = { "item", "num", "composeid" },
        ["target"] = { "loc" },
        ["func"] = { "compose" },
        ["types"] = { "i", "i", "i" },
    },
    [8003] = {
        ["keys"] = { "target", "num", "costings" },
        ["types"] = { "i", "i", "s" },
    },
    [2001] = {
        ["keys"] = { "time" },
        ["types"] = { "i" },
    },
    [8004] = {
        ["rspid"] = { "8005" },
        ["keys"] = { "item" },
        ["target"] = { "loc" },
        ["func"] = { "useItem" },
        ["types"] = { "i" },
    },
    [8005] = {
        ["keys"] = { "item", "baseinfo", "bagitem" },
        ["types"] = { "i", "s", "s" },
    },
    [2002] = {
        ["rspid"] = { "2003" },
        ["keys"] = { "itemid" },
        ["target"] = { "loc" },
        ["func"] = { "test_addItem" },
        ["types"] = { "i" },
    },
    [11000] = {
        ["rspid"] = { "11001" },
        ["keys"] = { "mapId", "pointId" },
        ["target"] = { "loc" },
        ["func"] = { "switchPoint" },
        ["types"] = { "i", "i" },
    },
    [11001] = {
        ["keys"] = { "mapId", "pointId" },
        ["types"] = { "i", "i" },
    },
    [11002] = {
        ["rspid"] = { "11003" },
        ["keys"] = { "mapId", "pointId" },
        ["target"] = { "loc" },
        ["func"] = { "onlineProfit" },
        ["types"] = { "i", "i" },
    },
    [3005] = {
        ["keys"] = { "uuid", "host", "port" },
        ["types"] = { "s", "s", "i" },
    },
    [11004] = {
        ["rspid"] = { "11005" },
        ["keys"] = { "uuid", "area" },
        ["target"] = { "loc" },
        ["func"] = { "offlineProfit" },
        ["types"] = { "s", "i" },
    },
    [11005] = {
        ["keys"] = { "bagitem", "playerInfo", "gold", "exp", "time" },
        ["types"] = { "s", "s", "i", "i", "i" },
    },
    [2003] = {
        ["keys"] = { "item" },
        ["types"] = { "s" },
    },
    [3006] = {
        ["rspid"] = { "3007" },
        ["keys"] = { "uuid", "area" },
        ["target"] = { "conn" },
        ["func"] = { "loginGame" },
        ["types"] = { "s", "i" },
    },
    [3007] = {
        ["keys"] = { "loginState", "playerInfo" },
        ["types"] = { "i", "s" },
    },
    [2004] = {
        ["rspid"] = { "2005" },
        ["keys"] = { "type", "value" },
        ["target"] = { "loc" },
        ["func"] = { "test_addValue" },
        ["types"] = { "i", "i" },
    },
    [3008] = {
        ["rspid"] = { "3009" },
        ["keys"] = { "uuid", "area", "userName" },
        ["target"] = { "loc" },
        ["func"] = { "createPlayerInfo" },
        ["types"] = { "s", "i", "s" },
    },
    [7001] = {
        ["rspid"] = { "7002" },
        ["keys"] = { "uuid", "area", "sign", "seq", "id1", "id2", "id3", "id4", "id5", "id6" },
        ["target"] = { "loc" },
        ["func"] = { "changeEquip" },
        ["types"] = { "s", "i", "i", "i", "s", "s", "s", "s", "s", "s" },
    },
    [3009] = {
        ["keys"] = { "loginState", "playerInfo" },
        ["types"] = { "i", "s" },
    },
    [7003] = {
        ["rspid"] = { "7004" },
        ["keys"] = { "uuid", "area", "equipId", "id1", "id2", "id3", "id4", "id5" },
        ["target"] = { "loc" },
        ["func"] = { "upgradeEquipStar" },
        ["types"] = { "s", "i", "s", "i", "i", "i", "i", "i" },
    },
    [2005] = {
        ["keys"] = { "type", "value" },
        ["types"] = { "i", "i" },
    },
    [7004] = {
        ["keys"] = { "equip" },
        ["types"] = { "s" },
    },
    [7005] = {
        ["rspid"] = { "7006" },
        ["keys"] = { "uuid", "area", "equipIdList" },
        ["target"] = { "loc" },
        ["func"] = { "splitEquip" },
        ["types"] = { "s", "i", "s" },
    },
    [3011] = {
        ["rspid"] = { "3012" },
        ["keys"] = { "uuid", "area" },
        ["target"] = { "conn" },
        ["func"] = { "loginGame" },
        ["types"] = { "s", "i" },
    },
    [7007] = {
        ["rspid"] = { "7008" },
        ["keys"] = { "uuid", "area", "lequipId", "requipId", "attr" },
        ["target"] = { "loc" },
        ["func"] = { "meltingEquip" },
        ["types"] = { "s", "i", "s", "s", "i" },
    },
    [7008] = {
        ["keys"] = { "equip", "splitList", "gold" },
        ["types"] = { "s", "s", "i" },
    },
    [7009] = {
        ["rspid"] = { "7010" },
        ["keys"] = { "uuid", "area", "equipId", "diamond" },
        ["target"] = { "loc" },
        ["func"] = { "rvmeltingEquip" },
        ["types"] = { "s", "i", "s", "i" },
    },
    [7010] = {
        ["keys"] = { "equip" },
        ["types"] = { "s" },
    },
    [7011] = {
        ["rspid"] = { "7012" },
        ["keys"] = { "scrollList" },
        ["target"] = { "loc" },
        ["func"] = { "makeEquip" },
        ["types"] = { "s" },
    },
    [7012] = {
        ["keys"] = { "equipList" },
        ["types"] = { "s" },
    },
    [7013] = {
        ["rspid"] = { "7014" },
        ["keys"] = { "heroId", "pos", "itemId", "diamond" },
        ["target"] = { "loc" },
        ["func"] = { "washHeroCloths" },
        ["types"] = { "i", "i", "i", "i" },
    },
    [7014] = {
        ["keys"] = { "heroInfo" },
        ["types"] = { "s" },
    },
    [1000] = {
        ["rspid"] = { "1001" },
        ["target"] = { "loc" },
        ["keys"] = { "name", "life" },
        ["func"] = { "getHero" },
        ["types"] = { "s", ",", "i" },
    },
    [4000] = {
        ["rspid"] = { "4001" },
        ["keys"] = { "uuid", "enemyid" },
        ["target"] = { "loc" },
        ["func"] = { "fightEnemy" },
        ["types"] = { "s", "s" },
    },
    [6000] = {
        ["rspid"] = { "6001" },
        ["keys"] = { "mapid" },
        ["target"] = { "loc" },
        ["func"] = { "enterMap" },
        ["types"] = { "i" },
    },
    [6001] = {
        ["keys"] = { "mapid", "x", "y", "uidlist", "sign" },
        ["types"] = { "i", "i", "i", "s", "s" },
    },
    [4001] = {
        ["keys"] = { "seed", "enemy", "result" },
        ["types"] = { "i", "s", "i" },
    },
    [6002] = {
        ["rspid"] = { "6003" },
        ["keys"] = { "mapid", "uid", "path" },
        ["target"] = { "loc" },
        ["func"] = { "walkPath" },
        ["types"] = { "i", "i", "s" },
    },
    [6003] = {
        ["keys"] = { "mapid", "x", "y", "cost", "buff" },
        ["types"] = { "i", "i", "i", "i", "s" },
    },
    [6004] = {
        ["rspid"] = { "6005" },
        ["keys"] = { "mapid", "uid", "nextstate", "args" },
        ["target"] = { "loc" },
        ["func"] = { "changeState" },
        ["types"] = { "i", "i", "i", "s" },
    },
    [6005] = {
        ["keys"] = { "mapid", "uid", "state", "args" },
        ["types"] = { "i", "i", "i", "s" },
    },
    [6006] = {
        ["rspid"] = { "6007" },
        ["keys"] = { "mapid", "uid", "key" },
        ["target"] = { "loc" },
        ["func"] = { "mapBuy" },
        ["types"] = { "i", "i", "i" },
    },
    [1001] = {
        ["keys"] = { "life" },
        ["types"] = { "i" },
    },
    [6008] = {
        ["rspid"] = { "6009" },
        ["keys"] = { "ok" },
        ["target"] = { "loc" },
        ["func"] = { "getMapInfo" },
        ["types"] = { "i" },
    },
    [6009] = {
        ["keys"] = { "mapinfo" },
        ["types"] = { "s" },
    },
    [5001] = {
        ["rspid"] = { "5002" },
        ["keys"] = { "uuid", "area" },
        ["target"] = { "loc" },
        ["func"] = { "getHeroInfoList" },
        ["types"] = { "s", "i" },
    },
    [5002] = {
        ["keys"] = { "heroInfoList" },
        ["types"] = { "s" },
    },
    [5003] = {
        ["rspid"] = { "5004" },
        ["keys"] = { "uuid", "area", "heroId" },
        ["target"] = { "loc" },
        ["func"] = { "createHero" },
        ["types"] = { "s", "i", "i" },
    },
    [7002] = {
        ["keys"] = { "equipList" },
        ["types"] = { "s" },
    },
    [5004] = {
        ["keys"] = { "heroInfo" },
        ["types"] = { "s" },
    },
    [13002] = {
        ["keys"] = { "ret" },
        ["types"] = { "i" },
    },
    [5005] = {
        ["rspid"] = { "5006" },
        ["keys"] = { "uuid", "area", "heroId", "expPlayer", "exp" },
        ["target"] = { "loc" },
        ["func"] = { "upgradeHeroLevel" },
        ["types"] = { "s", "i", "i", "i", "i" },
    },
    [3012] = {
        ["keys"] = { "loginState", "playerInfo" },
        ["types"] = { "i", "s" },
    },
    [5006] = {
        ["keys"] = { "playerInfo", "heroInfo" },
        ["types"] = { "s", "s" },
    },
    [11003] = {
        ["keys"] = { "bagitem", "playerInfo", "gold", "exp" },
        ["types"] = { "s", "s", "i", "i" },
    },
    [5007] = {
        ["rspid"] = { "5008" },
        ["keys"] = { "heroId", "slotId" },
        ["target"] = { "loc" },
        ["func"] = { "upgradeSkillSlot" },
        ["types"] = { "i", "i" },
    },
    [6007] = {
        ["keys"] = { "mapid", "uid", "key" },
        ["types"] = { "i", "i", "i" },
    },
    [5008] = {
        ["keys"] = { "heroInfo" },
        ["types"] = { "s" },
    },
    [13001] = {
        ["rspid"] = { "13002" },
        ["keys"] = { "uuid", "area", "type", "msg" },
        ["target"] = { "chat" },
        ["func"] = { "sendMsg" },
        ["types"] = { "s", "i", "i", "s" },
    },
    [5009] = {
        ["rspid"] = { "5010" },
        ["keys"] = { "heroId", "slotId", "skillId" },
        ["target"] = { "loc" },
        ["func"] = { "adapterSkillSlot" },
        ["types"] = { "i", "i", "i" },
    },
    [13003] = {
        ["keys"] = { "uuid", "area", "type", "msg" },
        ["types"] = { "s", "i", "i", "s" },
    },
    [5010] = {
        ["keys"] = { "heroInfo" },
        ["types"] = { "s" },
    },
    [7016] = {
        ["keys"] = { "max" },
        ["types"] = { "i" },
    },
    [7015] = {
        ["rspid"] = { "7016" },
        ["keys"] = { "uuid", "area" },
        ["target"] = { "loc" },
        ["func"] = { "unlockBag" },
        ["types"] = { "s", "i" },
    },
    [3000] = {
        ["rspid"] = { "3005" },
        ["keys"] = { "uuid", "area" },
        ["target"] = { "gate" },
        ["func"] = { "getAvgConnServerLoadNums" },
        ["types"] = { "s", "i" },
    },
    [7006] = {
        ["keys"] = { "splitList", "gold" },
        ["types"] = { "s", "i" },
    },
}
return _p

