/*
Don't modify this file manually!
*/
var _p = {
    3203311 : {
        "defense" : 300,
        "atk" : 1100,
        "cost" : 1,
        "id" : 3203311,
        "penetrationlevel" : 0,
        "hp" : 1500,
        "modelid" : 2004,
        "conskillid" : {
            1 : 3202113,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "舰队石像鬼",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    3203211 : {
        "defense" : 200,
        "atk" : 800,
        "cost" : 1,
        "id" : 3203211,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "modelid" : 2025,
        "conskillid" : {
            1 : 3202113,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "亡灵海贼",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    20001 : {
        "defense" : 30,
        "atk" : 180,
        "cost" : 1,
        "id" : 20001,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2002,
        "conskillid" : {
            1 : 40003,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "狮鹫骑士",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    20002 : {
        "defense" : 50,
        "atk" : 150,
        "cost" : 3,
        "id" : 20002,
        "penetrationlevel" : 0,
        "hp" : 350,
        "modelid" : 2001,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "狮鹫兽",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20003 : {
        "defense" : 0,
        "atk" : 100,
        "cost" : 4,
        "id" : 20003,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2004,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "石像鬼",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20004 : {
        "defense" : 0,
        "atk" : 150,
        "cost" : 4,
        "id" : 20004,
        "penetrationlevel" : 0,
        "hp" : 380,
        "modelid" : 2004,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "恶魔",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20005 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20005,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2003,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "狮鹫兽",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20006 : {
        "defense" : 30,
        "atk" : 180,
        "cost" : 1,
        "id" : 20006,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2002,
        "conskillid" : {
            1 : 40003,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "狮鹫兽",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    20007 : {
        "defense" : 50,
        "atk" : 150,
        "cost" : 3,
        "id" : 20007,
        "penetrationlevel" : 0,
        "hp" : 350,
        "modelid" : 2003,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "美杜莎",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20008 : {
        "defense" : 0,
        "atk" : 100,
        "cost" : 4,
        "id" : 20008,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2004,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "石像鬼",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20009 : {
        "defense" : 0,
        "atk" : 150,
        "cost" : 4,
        "id" : 20009,
        "penetrationlevel" : 0,
        "hp" : 380,
        "modelid" : 2005,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "火蜥蜴",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20010 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20010,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2006,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "巨虎",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20011 : {
        "defense" : 30,
        "atk" : 180,
        "cost" : 1,
        "id" : 20011,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2007,
        "conskillid" : {
            1 : 40003,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "蘑菇军团",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    20012 : {
        "defense" : 50,
        "atk" : 150,
        "cost" : 3,
        "id" : 20012,
        "penetrationlevel" : 0,
        "hp" : 350,
        "modelid" : 2008,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "火焰虎",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20013 : {
        "defense" : 0,
        "atk" : 100,
        "cost" : 4,
        "id" : 20013,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2009,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "巨蜥",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20014 : {
        "defense" : 0,
        "atk" : 150,
        "cost" : 4,
        "id" : 20014,
        "penetrationlevel" : 0,
        "hp" : 380,
        "modelid" : 2010,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "狮人",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20015 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20015,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2011,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "食人花",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20016 : {
        "defense" : 30,
        "atk" : 180,
        "cost" : 1,
        "id" : 20016,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2012,
        "conskillid" : {
            1 : 40003,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "火元素",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    20017 : {
        "defense" : 50,
        "atk" : 150,
        "cost" : 3,
        "id" : 20017,
        "penetrationlevel" : 0,
        "hp" : 350,
        "modelid" : 2013,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "水元素",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20018 : {
        "defense" : 0,
        "atk" : 100,
        "cost" : 4,
        "id" : 20018,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2014,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "树精卫士",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20019 : {
        "defense" : 0,
        "atk" : 150,
        "cost" : 4,
        "id" : 20019,
        "penetrationlevel" : 0,
        "hp" : 380,
        "modelid" : 2015,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "地狱犬",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20020 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20020,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2016,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "熔岩巨人",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20021 : {
        "defense" : 30,
        "atk" : 180,
        "cost" : 1,
        "id" : 20021,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2017,
        "conskillid" : {
            1 : 40003,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "伊芙利特",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    20022 : {
        "defense" : 50,
        "atk" : 150,
        "cost" : 3,
        "id" : 20022,
        "penetrationlevel" : 0,
        "hp" : 350,
        "modelid" : 2018,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "石巨人",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20023 : {
        "defense" : 0,
        "atk" : 100,
        "cost" : 4,
        "id" : 20023,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2019,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "天空龙",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20024 : {
        "defense" : 0,
        "atk" : 150,
        "cost" : 4,
        "id" : 20024,
        "penetrationlevel" : 0,
        "hp" : 380,
        "modelid" : 2020,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "死亡骑士",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20025 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20025,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2021,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "凤凰",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20026 : {
        "defense" : 30,
        "atk" : 180,
        "cost" : 1,
        "id" : 20026,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2022,
        "conskillid" : {
            1 : 40003,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "恶魔领主",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    20027 : {
        "defense" : 50,
        "atk" : 150,
        "cost" : 3,
        "id" : 20027,
        "penetrationlevel" : 0,
        "hp" : 350,
        "modelid" : 2023,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "光灵",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20028 : {
        "defense" : 0,
        "atk" : 100,
        "cost" : 4,
        "id" : 20028,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2024,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "史莱姆",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20029 : {
        "defense" : 0,
        "atk" : 150,
        "cost" : 4,
        "id" : 20029,
        "penetrationlevel" : 0,
        "hp" : 380,
        "modelid" : 2025,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "骷髅兵",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20030 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20030,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2026,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "血魔花",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20031 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20031,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2027,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "独角兽",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20032 : {
        "defense" : 30,
        "atk" : 550,
        "cost" : 1,
        "id" : 20032,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "modelid" : 2028,
        "conskillid" : {
            1 : 40003,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "小火龙",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    20033 : {
        "defense" : 50,
        "atk" : 150,
        "cost" : 3,
        "id" : 20033,
        "penetrationlevel" : 0,
        "hp" : 350,
        "modelid" : 2029,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "鲛人",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20034 : {
        "defense" : 0,
        "atk" : 100,
        "cost" : 4,
        "id" : 20034,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2030,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "光元素",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20035 : {
        "defense" : 0,
        "atk" : 150,
        "cost" : 4,
        "id" : 20035,
        "penetrationlevel" : 0,
        "hp" : 380,
        "modelid" : 2031,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "食尸鬼",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20036 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20036,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2032,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "斯芬克斯",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20037 : {
        "defense" : 50,
        "atk" : 600,
        "cost" : 3,
        "id" : 20037,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "modelid" : 2033,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "九头蛇",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20038 : {
        "defense" : 0,
        "atk" : 1000,
        "cost" : 4,
        "id" : 20038,
        "penetrationlevel" : 0,
        "hp" : 2000,
        "modelid" : 2034,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "炽天使",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20039 : {
        "defense" : 0,
        "atk" : 150,
        "cost" : 4,
        "id" : 20039,
        "penetrationlevel" : 0,
        "hp" : 380,
        "modelid" : 2035,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "麒麟",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20040 : {
        "defense" : 50,
        "atk" : 200,
        "cost" : 2,
        "id" : 20040,
        "penetrationlevel" : 0,
        "hp" : 250,
        "modelid" : 2036,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "比蒙巨兽",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20041 : {
        "defense" : 50,
        "atk" : 800,
        "cost" : 2,
        "id" : 20041,
        "penetrationlevel" : 0,
        "hp" : 900,
        "modelid" : 2037,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "古龙",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20042 : {
        "defense" : 0,
        "atk" : 650,
        "cost" : 3,
        "id" : 20042,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "modelid" : 2033,
        "conskillid" : {
            1 : 40002,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "九头蛇",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 0,
    },
    20043 : {
        "defense" : 0,
        "atk" : 450,
        "cost" : 4,
        "id" : 20043,
        "penetrationlevel" : 0,
        "hp" : 750,
        "modelid" : 2031,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "食尸鬼",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20044 : {
        "defense" : 0,
        "atk" : 700,
        "cost" : 4,
        "id" : 20044,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "modelid" : 2020,
        "conskillid" : {
            1 : 40001,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "死亡骑士",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 10,
    },
    20045 : {
        "defense" : 30,
        "atk" : 180,
        "cost" : 1,
        "id" : 20045,
        "penetrationlevel" : 0,
        "hp" : 200,
        "modelid" : 2022,
        "conskillid" : {
            1 : 40003,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "恶魔领主",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    3203111 : {
        "defense" : 150,
        "atk" : 320,
        "cost" : 1,
        "id" : 3203111,
        "penetrationlevel" : 0,
        "hp" : 700,
        "modelid" : 2023,
        "conskillid" : {
            1 : 3202113,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "光之海盗",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    3202211 : {
        "defense" : 200,
        "atk" : 700,
        "cost" : 1,
        "id" : 3202211,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "modelid" : 2002,
        "conskillid" : {
            1 : 3202113,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "装甲狮鹫",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },
    3202111 : {
        "defense" : 100,
        "atk" : 450,
        "cost" : 1,
        "id" : 3202111,
        "penetrationlevel" : 0,
        "hp" : 750,
        "modelid" : 2024,
        "conskillid" : {
            1 : 3202113,
            2 : 0,
        },
        "skillid" : {
            1 : 40005,
            2 : 0,
        },
        "name" : "湖之精灵",
        "critlevel" : 0,
        "hitlevel" : 0,
        "tenacitylevel" : 0,
        "dodgelevel" : 0,
        "reducehurt" : 20,
    },

};
module.exports = _p;
