/*
Don't modify this file manually!
*/
var _p = {
    7 : {
        "EffectArg" : 100,
        "Effecttype" : 1,
        "BuffId" : 7,
        "Desc" : "每次行走的步数消耗减少100%",
        "TimeArg" : 20,
        "Name" : "行走不消耗步数",
        "SpeedUp" : 50,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10001,
    },
    1 : {
        "EffectArg" : 30,
        "Effecttype" : 1,
        "BuffId" : 1,
        "Desc" : "每次行走的步数消耗减少30%",
        "TimeArg" : 30,
        "Name" : "减少步耗（百分比）",
        "SpeedUp" : 30,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10000,
    },
    2 : {
        "EffectArg" : 2,
        "Effecttype" : 2,
        "BuffId" : 2,
        "Desc" : "每次行走的步数消耗减少2",
        "TimeArg" : 30,
        "Name" : "减少步耗（数值）",
        "SpeedUp" : 30,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10000,
    },
    4 : {
        "EffectArg" : 100,
        "Effecttype" : 1,
        "BuffId" : 4,
        "Desc" : "每次行走的步数消耗减少100%",
        "TimeArg" : 20,
        "Name" : "行走不消耗步数",
        "SpeedUp" : 50,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10001,
    },
    8 : {
        "EffectArg" : 100,
        "Effecttype" : 1,
        "BuffId" : 8,
        "Desc" : "每次行走的步数消耗减少100%",
        "TimeArg" : 20,
        "Name" : "行走不消耗步数",
        "SpeedUp" : 50,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10001,
    },
    9 : {
        "EffectArg" : 100,
        "Effecttype" : 1,
        "BuffId" : 9,
        "Desc" : "每次行走的步数消耗减少100%",
        "TimeArg" : 15,
        "Name" : "行走不消耗步数",
        "SpeedUp" : 50,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10001,
    },
    5 : {
        "EffectArg" : 100,
        "Effecttype" : 1,
        "BuffId" : 5,
        "Desc" : "每次行走的步数消耗减少100%",
        "TimeArg" : 12,
        "Name" : "行走不消耗步数",
        "SpeedUp" : 50,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10001,
    },
    10 : {
        "EffectArg" : 20,
        "Effecttype" : 5,
        "BuffId" : 10,
        "Desc" : "每次获得的金钱奖励加成20%",
        "TimeArg" : 5,
        "Name" : "金钱奖励加成",
        "SpeedUp" : 0,
        "BuffType" : 2,
        "EffectID" : 0,
        "Pic" : 10002,
    },
    20 : {
        "EffectArg" : 30,
        "Effecttype" : 6,
        "BuffId" : 20,
        "Desc" : "商店道具单价降低30%",
        "TimeArg" : 86400,
        "Name" : "降价",
        "SpeedUp" : 0,
        "BuffType" : 2,
        "EffectID" : 0,
        "Pic" : 10002,
    },
    3 : {
        "EffectArg" : 30,
        "Effecttype" : 3,
        "BuffId" : 3,
        "Desc" : "每次行走的步数消耗增加30%",
        "TimeArg" : 30,
        "Name" : "增加步耗（百分比）",
        "SpeedUp" : 30,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10000,
    },
    6 : {
        "EffectArg" : 100,
        "Effecttype" : 1,
        "BuffId" : 6,
        "Desc" : "每次行走的步数消耗减少100%",
        "TimeArg" : 20,
        "Name" : "行走不消耗步数",
        "SpeedUp" : 50,
        "BuffType" : 1,
        "EffectID" : 0,
        "Pic" : 10001,
    },

};
module.exports = _p;
