/*
Don't modify this file manually!
*/
var _p = {
    27 : {
        "Exploration" : 10,
        "UId" : 2479,
        "Key" : 27,
        "MapId" : 3,
    },
    2 : {
        "Exploration" : 10,
        "UId" : 2451,
        "Key" : 2,
        "MapId" : 1,
    },
    38 : {
        "Exploration" : 10,
        "UId" : 2511,
        "Key" : 38,
        "MapId" : 3,
    },
    3 : {
        "Exploration" : 10,
        "UId" : 2453,
        "Key" : 3,
        "MapId" : 1,
    },
    54 : {
        "Exploration" : 10,
        "UId" : 3073,
        "Key" : 54,
        "MapId" : 4,
    },
    4 : {
        "Exploration" : 10,
        "UId" : 2457,
        "Key" : 4,
        "MapId" : 1,
    },
    5 : {
        "Exploration" : 10,
        "UId" : 1713,
        "Key" : 5,
        "MapId" : 2,
    },
    6 : {
        "Exploration" : 10,
        "UId" : 1715,
        "Key" : 6,
        "MapId" : 2,
    },
    7 : {
        "Exploration" : 10,
        "UId" : 1914,
        "Key" : 7,
        "MapId" : 2,
    },
    8 : {
        "Exploration" : 10,
        "UId" : 1942,
        "Key" : 8,
        "MapId" : 2,
    },
    10 : {
        "Exploration" : 10,
        "UId" : 1949,
        "Key" : 10,
        "MapId" : 2,
    },
    12 : {
        "Exploration" : 10,
        "UId" : 1954,
        "Key" : 12,
        "MapId" : 2,
    },
    14 : {
        "Exploration" : 10,
        "UId" : 1974,
        "Key" : 14,
        "MapId" : 2,
    },
    16 : {
        "Exploration" : 10,
        "UId" : 1982,
        "Key" : 16,
        "MapId" : 3,
    },
    20 : {
        "Exploration" : 10,
        "UId" : 2423,
        "Key" : 20,
        "MapId" : 3,
    },
    24 : {
        "Exploration" : 10,
        "UId" : 2468,
        "Key" : 24,
        "MapId" : 3,
    },
    28 : {
        "Exploration" : 10,
        "UId" : 2480,
        "Key" : 28,
        "MapId" : 3,
    },
    32 : {
        "Exploration" : 10,
        "UId" : 2505,
        "Key" : 32,
        "MapId" : 3,
    },
    40 : {
        "Exploration" : 10,
        "UId" : 2467,
        "Key" : 40,
        "MapId" : 4,
    },
    48 : {
        "Exploration" : 10,
        "UId" : 3050,
        "Key" : 48,
        "MapId" : 4,
    },
    33 : {
        "Exploration" : 10,
        "UId" : 2506,
        "Key" : 33,
        "MapId" : 3,
    },
    41 : {
        "Exploration" : 10,
        "UId" : 2655,
        "Key" : 41,
        "MapId" : 4,
    },
    49 : {
        "Exploration" : 10,
        "UId" : 3055,
        "Key" : 49,
        "MapId" : 4,
    },
    17 : {
        "Exploration" : 10,
        "UId" : 2285,
        "Key" : 17,
        "MapId" : 3,
    },
    21 : {
        "Exploration" : 10,
        "UId" : 2443,
        "Key" : 21,
        "MapId" : 3,
    },
    25 : {
        "Exploration" : 10,
        "UId" : 2475,
        "Key" : 25,
        "MapId" : 3,
    },
    29 : {
        "Exploration" : 10,
        "UId" : 2501,
        "Key" : 29,
        "MapId" : 3,
    },
    34 : {
        "Exploration" : 10,
        "UId" : 2507,
        "Key" : 34,
        "MapId" : 3,
    },
    42 : {
        "Exploration" : 10,
        "UId" : 2682,
        "Key" : 42,
        "MapId" : 4,
    },
    50 : {
        "Exploration" : 10,
        "UId" : 3058,
        "Key" : 50,
        "MapId" : 4,
    },
    55 : {
        "Exploration" : 10,
        "UId" : 3085,
        "Key" : 55,
        "MapId" : 4,
    },
    35 : {
        "Exploration" : 10,
        "UId" : 2508,
        "Key" : 35,
        "MapId" : 3,
    },
    9 : {
        "Exploration" : 10,
        "UId" : 1946,
        "Key" : 9,
        "MapId" : 2,
    },
    11 : {
        "Exploration" : 10,
        "UId" : 1953,
        "Key" : 11,
        "MapId" : 2,
    },
    13 : {
        "Exploration" : 10,
        "UId" : 1973,
        "Key" : 13,
        "MapId" : 2,
    },
    15 : {
        "Exploration" : 10,
        "UId" : 1978,
        "Key" : 15,
        "MapId" : 3,
    },
    18 : {
        "Exploration" : 10,
        "UId" : 2356,
        "Key" : 18,
        "MapId" : 3,
    },
    22 : {
        "Exploration" : 10,
        "UId" : 2447,
        "Key" : 22,
        "MapId" : 3,
    },
    26 : {
        "Exploration" : 10,
        "UId" : 2477,
        "Key" : 26,
        "MapId" : 3,
    },
    30 : {
        "Exploration" : 10,
        "UId" : 2502,
        "Key" : 30,
        "MapId" : 3,
    },
    36 : {
        "Exploration" : 10,
        "UId" : 2509,
        "Key" : 36,
        "MapId" : 3,
    },
    44 : {
        "Exploration" : 10,
        "UId" : 2698,
        "Key" : 44,
        "MapId" : 4,
    },
    52 : {
        "Exploration" : 10,
        "UId" : 3062,
        "Key" : 52,
        "MapId" : 4,
    },
    51 : {
        "Exploration" : 10,
        "UId" : 3060,
        "Key" : 51,
        "MapId" : 4,
    },
    47 : {
        "Exploration" : 10,
        "UId" : 3047,
        "Key" : 47,
        "MapId" : 4,
    },
    46 : {
        "Exploration" : 10,
        "UId" : 3045,
        "Key" : 46,
        "MapId" : 4,
    },
    39 : {
        "Exploration" : 10,
        "UId" : 2307,
        "Key" : 39,
        "MapId" : 4,
    },
    43 : {
        "Exploration" : 10,
        "UId" : 2688,
        "Key" : 43,
        "MapId" : 4,
    },
    37 : {
        "Exploration" : 10,
        "UId" : 2510,
        "Key" : 37,
        "MapId" : 3,
    },
    45 : {
        "Exploration" : 10,
        "UId" : 3030,
        "Key" : 45,
        "MapId" : 4,
    },
    53 : {
        "Exploration" : 10,
        "UId" : 3071,
        "Key" : 53,
        "MapId" : 4,
    },
    1 : {
        "Exploration" : 10,
        "UId" : 2220,
        "Key" : 1,
        "MapId" : 1,
    },
    19 : {
        "Exploration" : 10,
        "UId" : 2359,
        "Key" : 19,
        "MapId" : 3,
    },
    23 : {
        "Exploration" : 10,
        "UId" : 2467,
        "Key" : 23,
        "MapId" : 3,
    },
    31 : {
        "Exploration" : 10,
        "UId" : 2504,
        "Key" : 31,
        "MapId" : 3,
    },

};
module.exports = _p;
