/*
Don't modify this file manually!
*/
var _p = {
    6 : {
        "InitPos" : {
            1 : 5,
            2 : 18,
        },
        "InfoFile" : "06.json",
        "MapId" : 6,
        "MapName" : "地图6",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "Exploration" : 1,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/06",
        "Time" : 1,
        "AP" : 500,
        "Reward" : 9999,
    },
    2 : {
        "InitPos" : {
            1 : 5,
            2 : 7,
        },
        "InfoFile" : "03.json",
        "MapId" : 2,
        "MapName" : "英雄岗",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "Exploration" : 100,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/03",
        "Time" : 1,
        "AP" : 500,
        "Reward" : 9999,
    },
    3 : {
        "InitPos" : {
            1 : 3,
            2 : 9,
        },
        "InfoFile" : "04.json",
        "MapId" : 3,
        "MapName" : "旅者丘陵",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "Exploration" : 240,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/04",
        "Time" : 1,
        "AP" : 500,
        "Reward" : 9999,
    },
    1 : {
        "InitPos" : {
            1 : 9,
            2 : 7,
        },
        "InfoFile" : "01.json",
        "MapId" : 1,
        "MapName" : "瓦尔王城",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "Exploration" : 40,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/01",
        "Time" : 1,
        "AP" : 500,
        "Reward" : 9999,
    },
    4 : {
        "InitPos" : {
            1 : 23,
            2 : 4,
        },
        "InfoFile" : "05.json",
        "MapId" : 4,
        "MapName" : "血色森林",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "Exploration" : 170,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/05",
        "Time" : 1,
        "AP" : 500,
        "Reward" : 9999,
    },
    5 : {
        "InitPos" : {
            1 : 23,
            2 : 4,
        },
        "InfoFile" : "05.json",
        "MapId" : 5,
        "MapName" : "地图5",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "Exploration" : 1,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/05",
        "Time" : 1,
        "AP" : 500,
        "Reward" : 9999,
    },
    7 : {
        "InitPos" : {
            1 : 5,
            2 : 18,
        },
        "InfoFile" : "06.json",
        "MapId" : 7,
        "MapName" : "地图7",
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "Exploration" : 1,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/06",
        "Time" : 1,
        "AP" : 500,
        "Reward" : 9999,
    },

};
module.exports = _p;
