/*
Don't modify this file manually!
*/
var _p = {
    12002 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 2,
        "ElementType" : 12,
        "Pic1" : 1200,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1201,
        "Id" : 12002,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12004 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 1,
        "ElementType" : 12,
        "Pic1" : 1202,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1202,
        "Id" : 12004,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12006 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 3,
        "ElementType" : 12,
        "Pic1" : 1202,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1202,
        "Id" : 12006,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12008 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 7,
        "ElementType" : 12,
        "Pic1" : 1202,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1202,
        "Id" : 12008,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "4圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12010 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 5,
        "ElementType" : 12,
        "Pic1" : 1203,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1203,
        "Id" : 12010,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "2圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12001 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 1,
        "ElementType" : 12,
        "Pic1" : 1200,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1201,
        "Id" : 12001,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12003 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 3,
        "ElementType" : 12,
        "Pic1" : 1200,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1201,
        "Id" : 12003,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12005 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 2,
        "ElementType" : 12,
        "Pic1" : 1202,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1202,
        "Id" : 12005,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12007 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 4,
        "ElementType" : 12,
        "Pic1" : 1203,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1203,
        "Id" : 12007,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "2圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12009 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 8,
        "ElementType" : 12,
        "Pic1" : 1202,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1202,
        "Id" : 12009,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "4圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },
    12011 : {
        "Effect2" : {
            1 : {
                1 : 60049,
                2 : 100,
                3 : 0,
                4 : 110,
                5 : 1,
            },
        },
        "Buff" : 6,
        "ElementType" : 12,
        "Pic1" : 1203,
        "Genre" : 4,
        "Desc1" : 1200,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 0,
        "Pic2" : 1203,
        "Id" : 12011,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Name" : "3圣泉",
        "Desc2" : 1201,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "RestrictStep" : 0,
        "PickupLived" : 1,
    },

};
module.exports = _p;
