/*
Don't modify this file manually!
*/
var _p = {
    2007 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 12,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 2,
        "Pic1" : 201,
        "Genre" : 1,
        "Obstacle" : 0,
        "Desc1" : 206,
        "Resetting" : 0,
        "Value" : 0,
        "Probability2" : 100,
        "Reward2" : 10187,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Show1" : 0,
        "PickupLived" : 0,
        "Pic2" : 201,
        "RestrictStep" : 0,
        "Id" : 2007,
        "GetInto" : 0,
        "Show2" : 0,
        "Color1" : 1,
        "Color2" : 1,
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 2,
            },
        },
        "Name" : "上锁的宝箱",
        "Desc2" : 207,
        "Probability1" : 100,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward1" : 10186,
    },
    2011 : {
        "ElementType" : 2,
        "Probability1" : 100,
        "Genre" : 1,
        "Desc1" : 208,
        "Obstacle" : 0,
        "Value" : 0,
        "Probability2" : 100,
        "Resetting" : 0,
        "Reward1" : 10188,
        "Reward2" : 10189,
        "PickupLived" : 0,
        "Pic2" : 3624,
        "GetInto" : 0,
        "Id" : 2011,
        "RestrictStep" : 0,
        "Show2" : 0,
        "Color1" : 1,
        "Color2" : 1,
        "RestrictLose" : 0,
        "Name" : "测试抉择资源前置条件",
        "Desc2" : 209,
        "Show1" : 0,
        "RestrictSuc" : 0,
        "Pic1" : 3624,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    2008 : {
        "Effect2" : {
            1 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 92,
                5 : 1,
            },
        },
        "ElementType" : 2,
        "Pic1" : 3634,
        "Genre" : 1,
        "Desc1" : 208,
        "Obstacle" : 0,
        "Value" : 0,
        "Probability2" : 100,
        "Resetting" : 0,
        "Reward1" : 10188,
        "Reward2" : 10189,
        "PickupLived" : 1,
        "Pic2" : 3634,
        "Show1" : 0,
        "Id" : 2008,
        "RestrictStep" : 0,
        "Show2" : 0,
        "Color1" : 1,
        "Color2" : 1,
        "RestrictLose" : 0,
        "Name" : "小仙子",
        "Desc2" : 209,
        "GetInto" : 0,
        "RestrictSuc" : 0,
        "Probability1" : 100,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    2001 : {
        "ElementType" : 2,
        "Probability1" : 100,
        "Genre" : 1,
        "Desc1" : 200,
        "Obstacle" : 0,
        "Value" : 0,
        "Probability2" : 100,
        "Resetting" : 0,
        "Reward1" : 10011,
        "Reward2" : 10012,
        "PickupLived" : 0,
        "Pic2" : 201,
        "GetInto" : 0,
        "Id" : 2001,
        "RestrictStep" : 0,
        "Show2" : 0,
        "Color1" : 0,
        "Color2" : 0,
        "RestrictLose" : 0,
        "Name" : "抉择资源1",
        "Desc2" : 201,
        "Show1" : 0,
        "RestrictSuc" : 0,
        "Pic1" : 201,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    2005 : {
        "Effect2" : {
            1 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 92,
                5 : 1,
            },
        },
        "ElementType" : 2,
        "Pic1" : 3634,
        "Genre" : 1,
        "Desc1" : 202,
        "Obstacle" : 0,
        "Value" : 0,
        "Probability2" : 60,
        "Resetting" : 0,
        "Reward1" : 10182,
        "Reward2" : 10183,
        "PickupLived" : 1,
        "Pic2" : 3634,
        "Show1" : 0,
        "Id" : 2005,
        "RestrictStep" : 0,
        "Show2" : 1,
        "Color1" : 1,
        "Color2" : 1,
        "RestrictLose" : 0,
        "Name" : "采魔晶的小光灵",
        "Desc2" : 203,
        "GetInto" : 0,
        "RestrictSuc" : 0,
        "Probability1" : 100,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    2009 : {
        "Effect2" : {
            1 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 92,
                5 : 1,
            },
        },
        "ElementType" : 2,
        "Pic1" : 3643,
        "Genre" : 1,
        "Desc1" : 210,
        "Obstacle" : 0,
        "Value" : 0,
        "Probability2" : 100,
        "Resetting" : 0,
        "Reward1" : 10190,
        "Reward2" : 10191,
        "PickupLived" : 0,
        "Pic2" : 3643,
        "Show1" : 0,
        "Id" : 2009,
        "RestrictStep" : 0,
        "Show2" : 0,
        "Color1" : 1,
        "Color2" : 1,
        "RestrictLose" : 0,
        "Name" : "尼莫",
        "Desc2" : 211,
        "GetInto" : 0,
        "RestrictSuc" : 0,
        "Probability1" : 100,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    2002 : {
        "ElementType" : 2,
        "Probability1" : 100,
        "Genre" : 1,
        "Desc1" : 200,
        "Obstacle" : 0,
        "Value" : 0,
        "Probability2" : 50,
        "Resetting" : 0,
        "Reward1" : 10014,
        "Reward2" : 10013,
        "PickupLived" : 0,
        "Pic2" : 201,
        "GetInto" : 0,
        "Id" : 2002,
        "RestrictStep" : 0,
        "Show2" : 1,
        "Color1" : 0,
        "Color2" : 1,
        "RestrictLose" : 0,
        "Name" : "抉择资源2",
        "Desc2" : 201,
        "Show1" : 0,
        "RestrictSuc" : 0,
        "Pic1" : 201,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    2006 : {
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 12,
                4 : 32,
                5 : 1,
            },
        },
        "ElementType" : 2,
        "Pic1" : 201,
        "Genre" : 1,
        "Desc1" : 204,
        "Obstacle" : 0,
        "Value" : 0,
        "Probability2" : 100,
        "Resetting" : 0,
        "Reward1" : 10184,
        "Reward2" : 10185,
        "PickupLived" : 0,
        "Pic2" : 201,
        "Show1" : 0,
        "Id" : 2006,
        "RestrictStep" : 0,
        "Show2" : 0,
        "Color1" : 1,
        "Color2" : 1,
        "RestrictLose" : 0,
        "Name" : "聚宝盆",
        "Desc2" : 205,
        "GetInto" : 0,
        "RestrictSuc" : 0,
        "Probability1" : 100,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    2010 : {
        "ElementType" : 2,
        "Pic1" : 105,
        "Genre" : 1,
        "Obstacle" : 0,
        "Desc1" : 206,
        "Resetting" : 0,
        "Value" : 0,
        "Probability2" : 100,
        "RestrictLose" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Show1" : 0,
        "PickupLived" : 0,
        "Pic2" : 105,
        "RestrictStep" : 0,
        "Id" : 2010,
        "GetInto" : 0,
        "Show2" : 0,
        "Color1" : 1,
        "Color2" : 1,
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 2,
            },
        },
        "Name" : "测试抉择资源前置条件",
        "Desc2" : 207,
        "Reward2" : 10187,
        "RestrictSuc" : 0,
        "Probability1" : 100,
        "Reward1" : 10186,
    },
    2003 : {
        "ElementType" : 2,
        "Probability1" : 60,
        "Genre" : 1,
        "Desc1" : 200,
        "Obstacle" : 0,
        "Value" : 0,
        "Probability2" : 60,
        "Resetting" : 0,
        "Reward1" : 10015,
        "Reward2" : 10016,
        "PickupLived" : 0,
        "Pic2" : 201,
        "GetInto" : 0,
        "Id" : 2003,
        "RestrictStep" : 0,
        "Show2" : 0,
        "Color1" : 0,
        "Color2" : 1,
        "RestrictLose" : 0,
        "Name" : "抉择资源3",
        "Desc2" : 201,
        "Show1" : 0,
        "RestrictSuc" : 0,
        "Pic1" : 201,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },

};
module.exports = _p;
