/*
Don't modify this file manually!
*/
var _p = {
    1013 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 105,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 105,
        "RestrictStep" : 1,
        "Id" : 1013,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 1,
            },
        },
        "Name" : "条件等级",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10007,
    },
    1015 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 105,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 105,
        "RestrictStep" : 1,
        "Id" : 1015,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 1,
            },
        },
        "Name" : "条件标记",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10009,
    },
    1017 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 105,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 105,
        "RestrictStep" : 1,
        "Id" : 1017,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 1,
            },
            2 : {
                1 : 2,
                2 : 20,
            },
            3 : {
                1 : 3,
                2 : 1,
            },
        },
        "Name" : "三种",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10008,
    },
    10122 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 102,
        "Id" : 10122,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "新手宝箱-中",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10122,
    },
    10123 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 102,
        "Id" : 10123,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "新手宝箱-中",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10123,
    },
    10124 : {
        "IfWindows" : 1,
        "ElementType" : 1,
        "Pic1" : 103,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 103,
        "Id" : 10124,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "高级宝箱",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10124,
    },
    10126 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3501,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3501,
        "Id" : 10126,
        "GetInto" : 0,
        "Name" : "武器",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10126,
    },
    10127 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3505,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3505,
        "Id" : 10127,
        "GetInto" : 0,
        "Name" : "戒指",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10127,
    },
    10101 : {
        "IfWindows" : 1,
        "ElementType" : 1,
        "Pic1" : 101,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 101,
        "Id" : 10101,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "新手宝箱1",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10101,
    },
    1002 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 199,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 199,
        "Id" : 1002,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "上帝盒子",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10008,
    },
    1004 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 1,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 1,
        "RestrictStep" : 1,
        "Id" : 1004,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 1,
            },
        },
        "Name" : "初级宝箱",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10007,
    },
    10103 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3506,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3506,
        "Id" : 10103,
        "GetInto" : 0,
        "Name" : "项链",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10103,
    },
    1008 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 102,
        "Id" : 1008,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "B宝箱",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10008,
    },
    1010 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 104,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 104,
        "Id" : 1010,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "D宝箱",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10007,
    },
    1012 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 106,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 106,
        "Id" : 1012,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "宝袋",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    1014 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 105,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 105,
        "RestrictStep" : 1,
        "Id" : 1014,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 2,
                2 : 20,
            },
        },
        "Name" : "条件战斗力",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10008,
    },
    1016 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 105,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 105,
        "RestrictStep" : 1,
        "Id" : 1016,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 1,
            },
            2 : {
                1 : 2,
                2 : 20,
            },
        },
        "Name" : "等级战斗力",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10007,
    },
    1018 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 102,
        "RestrictStep" : 1,
        "Id" : 1018,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 3,
            },
            2 : {
                1 : 2,
                2 : 50,
            },
        },
        "Name" : "掉落标记的宝箱",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10018,
    },
    10107 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3560,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3560,
        "Id" : 10107,
        "GetInto" : 0,
        "Name" : "曹操碎片",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10107,
    },
    10108 : {
        "IfWindows" : 1,
        "ElementType" : 1,
        "Pic1" : 103,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 103,
        "Id" : 10108,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "新手宝箱-装备",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10108,
    },
    10109 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 103,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 103,
        "Id" : 10109,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "新手宝箱-装备",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10109,
    },
    10110 : {
        "IfWindows" : 1,
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 102,
        "Id" : 10110,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "新手宝箱-中",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10110,
    },
    10104 : {
        "IfWindows" : 1,
        "ElementType" : 1,
        "Pic1" : 101,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 101,
        "Id" : 10104,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "新手宝箱2",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10104,
    },
    1011 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 105,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 105,
        "Id" : 1011,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "E宝箱",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10008,
    },
    10121 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3515,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3515,
        "Id" : 10121,
        "GetInto" : 0,
        "Name" : "铁矿石（二阶）",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10121,
    },
    1007 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 101,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 101,
        "Id" : 1007,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "A宝箱",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10007,
    },
    10114 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3519,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3519,
        "Id" : 10114,
        "GetInto" : 0,
        "Name" : "一阶鞋子卷轴",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10114,
    },
    1006 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 201,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 201,
        "RestrictStep" : 1,
        "Id" : 1006,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 1,
            },
        },
        "Name" : "高级宝箱",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10009,
    },
    10115 : {
        "IfWindows" : 1,
        "ElementType" : 1,
        "Pic1" : 104,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 104,
        "RestrictStep" : 1,
        "Id" : 10115,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 2,
            },
        },
        "Name" : "上锁的宝箱",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10187,
    },
    1003 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 199,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 199,
        "Id" : 1003,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "上帝盒子",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    10116 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3514,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3514,
        "Id" : 10116,
        "GetInto" : 0,
        "Name" : "铁矿石（一阶）",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10116,
    },
    1019 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 102,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 102,
        "RestrictStep" : 1,
        "Id" : 1019,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 3,
            },
            2 : {
                1 : 2,
                2 : 50,
            },
        },
        "Name" : "掉落魔力铲的宝箱",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10015,
    },
    10117 : {
        "IfWindows" : 1,
        "ElementType" : 1,
        "Pic1" : 103,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 103,
        "Id" : 10117,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "大宝箱",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10117,
    },
    1001 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 199,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 199,
        "Id" : 1001,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "上帝盒子",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10007,
    },
    10118 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3514,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3514,
        "Id" : 10118,
        "GetInto" : 0,
        "Name" : "铁矿石（一阶）",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10118,
    },
    1005 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 1,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 1,
        "RestrictStep" : 1,
        "Id" : 1005,
        "Obstacle" : 0,
        "GetInto" : 0,
        "PickupLived" : 0,
        "Resetting" : 1,
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 1,
            },
        },
        "Name" : "中级宝箱",
        "Desc2" : 1,
        "IfFloat" : 0,
        "RestrictSuc" : 1,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "Reward" : 10008,
    },
    10119 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 1800,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 1800,
        "Id" : 10119,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "神秘木箱",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10119,
    },
    1009 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 103,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 103,
        "Id" : 1009,
        "Effect2" : {
            1 : {
                1 : 60062,
                2 : 100,
                3 : 16,
                4 : 32,
                5 : 1,
            },
        },
        "GetInto" : 0,
        "Obstacle" : 0,
        "Name" : "C宝箱",
        "IfFloat" : 0,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    10120 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3521,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3521,
        "Id" : 10120,
        "GetInto" : 0,
        "Name" : "一阶项链卷轴",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10120,
    },
    10106 : {
        "IfWindows" : 0,
        "ElementType" : 1,
        "Pic1" : 3552,
        "Genre" : 1,
        "Desc1" : 1,
        "Value" : 1,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "RestrictLose" : 1,
        "Pic2" : 3552,
        "Id" : 10106,
        "GetInto" : 0,
        "Name" : "卡特琳娜碎片",
        "Obstacle" : 0,
        "IfFloat" : 1,
        "Resetting" : 1,
        "Desc2" : 1,
        "RestrictStep" : 1,
        "RestrictSuc" : 1,
        "PickupLived" : 0,
        "Reward" : 10106,
    },

};
module.exports = _p;
