/*
Don't modify this file manually!
*/
var _p = {
    10005 : {
        "Effect2" : {
            1 : {
                1 : 60028,
                2 : 70,
                3 : 0,
                4 : 70,
                5 : 2,
            },
        },
        "ElementType" : 10,
        "Pic1" : 1702,
        "Genre" : 3,
        "Desc1" : 1004,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Map" : 4,
        "RestrictLose" : 0,
        "Pic2" : 1702,
        "RestrictStep" : 0,
        "Id" : 10005,
        "PicType" : "1,2,0,0；1",
        "GetInto" : 1,
        "Resetting" : 0,
        "Monster" : 10306,
        "Name" : "出口",
        "Obstacle" : 1,
        "Desc2" : 1005,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10151,
    },
    10002 : {
        "Effect2" : {
            1 : {
                1 : 60028,
                2 : 70,
                3 : 0,
                4 : 70,
                5 : 2,
            },
        },
        "ElementType" : 10,
        "Pic1" : 1001,
        "Genre" : 3,
        "Desc1" : 1000,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Map" : 1,
        "RestrictLose" : 0,
        "Pic2" : 600,
        "RestrictStep" : 0,
        "Id" : 10002,
        "PicType" : "1,2,0,0；1",
        "GetInto" : 1,
        "Resetting" : 0,
        "Monster" : 1006,
        "Name" : "出口",
        "Obstacle" : 1,
        "Desc2" : 1001,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10003,
    },
    10006 : {
        "Effect2" : {
            1 : {
                1 : 60028,
                2 : 70,
                3 : 0,
                4 : 70,
                5 : 2,
            },
        },
        "ElementType" : 10,
        "Pic1" : 1701,
        "Genre" : 3,
        "Desc1" : 1006,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Map" : 1,
        "RestrictLose" : 0,
        "Pic2" : 1701,
        "RestrictStep" : 0,
        "Id" : 10006,
        "PicType" : "1,2,0,0；1",
        "GetInto" : 1,
        "Resetting" : 0,
        "Monster" : 10409,
        "Name" : "出口",
        "Obstacle" : 1,
        "Desc2" : 1007,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10160,
    },
    10003 : {
        "Effect2" : {
            1 : {
                1 : 60028,
                2 : 70,
                3 : 0,
                4 : 70,
                5 : 2,
            },
        },
        "ElementType" : 10,
        "Pic1" : 1701,
        "Genre" : 3,
        "Desc1" : 1000,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Map" : 2,
        "RestrictLose" : 0,
        "Pic2" : 1701,
        "RestrictStep" : 0,
        "Id" : 10003,
        "PicType" : "1,2,0,0；1",
        "GetInto" : 1,
        "Resetting" : 0,
        "Monster" : 10101,
        "Name" : "出口",
        "Obstacle" : 1,
        "Desc2" : 1001,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10140,
    },
    10004 : {
        "Effect2" : {
            1 : {
                1 : 60028,
                2 : 70,
                3 : 0,
                4 : 70,
                5 : 2,
            },
        },
        "ElementType" : 10,
        "Pic1" : 1702,
        "Genre" : 3,
        "Desc1" : 1002,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Map" : 3,
        "RestrictLose" : 0,
        "Pic2" : 1702,
        "RestrictStep" : 0,
        "Id" : 10004,
        "PicType" : "1,2,0,0；1",
        "GetInto" : 1,
        "Resetting" : 0,
        "Monster" : 10205,
        "Name" : "出口",
        "Obstacle" : 1,
        "Desc2" : 1003,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10145,
    },
    10001 : {
        "Effect2" : {
            1 : {
                1 : 60028,
                2 : 70,
                3 : 0,
                4 : 70,
                5 : 2,
            },
        },
        "ElementType" : 10,
        "Pic1" : 1700,
        "Genre" : 3,
        "Desc1" : 1000,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Map" : 1,
        "RestrictLose" : 0,
        "Pic2" : 600,
        "RestrictStep" : 0,
        "Id" : 10001,
        "PicType" : "1,2,0,0；1",
        "GetInto" : 1,
        "Resetting" : 0,
        "Monster" : 1006,
        "Name" : "出口",
        "Obstacle" : 1,
        "Desc2" : 1001,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10002,
    },

};
module.exports = _p;
