/*
Don't modify this file manually!
*/
var _p = {
    30080 : {
        "ElementType" : 3,
        "Pic1" : 1002,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10303,
        "Desc1" : {
            1 : 316,
            2 : 317,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Value" : 0,
        "PickupLived" : 1,
        "Pic2" : 1002,
        "Effect1" : {
            1 : 60029,
            2 : 100,
            3 : -10,
            4 : 160,
        },
        "Id" : 30080,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "恶魔营地（魔窟）",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 318,
            2 : 319,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10099,
    },
    3001 : {
        "ElementType" : 3,
        "Pic1" : 300,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 1006,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "Pic2" : 1000,
        "Id" : 3001,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "据点",
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Effect3AddType" : 1,
    },
    3003 : {
        "ElementType" : 3,
        "Pic1" : 300,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 1006,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "Pic2" : 1000,
        "Id" : 3003,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "据点",
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Effect3AddType" : 1,
    },
    3098 : {
        "ElementType" : 3,
        "Pic1" : 106,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "Pic2" : 106,
        "Id" : 3098,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "挂机点奖励2",
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Effect3AddType" : 1,
    },
    3007 : {
        "ElementType" : 3,
        "Pic1" : 301,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10201,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Effect3AddType" : 1,
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "Resetting" : 0,
        "PickupLived" : 1,
        "Pic2" : 1000,
        "Effect1" : {
            1 : 60069,
            2 : 100,
            3 : 0,
            4 : 142,
        },
        "Id" : 3007,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "RestrictStep" : 0,
        "Name" : "林间营地（魔窟）",
        "Precondition" : {
            1 : {
                1 : 2,
                2 : 100,
            },
        },
        "Obstacle" : 0,
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10099,
    },
    4001 : {
        "ElementType" : 4,
        "Pic1" : 401,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Time" : 1800000,
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Obstacle" : 0,
        "RestrictLose" : 0,
        "Pic2" : 1000,
        "Resetting" : 0,
        "Id" : 4001,
        "PicType" : "1；1,2,x,y",
        "GetInto" : 1,
        "PickupLived" : 1,
        "RestrictStep" : 0,
        "Precondition" : {
            1 : {
                1 : 2,
                2 : 10,
            },
        },
        "Name" : "限时挂机点(普通）",
        "Desc2" : {
            1 : 402,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "Desc1" : {
            1 : 400,
            2 : 401,
        },
        "Value" : 0,
    },
    3011 : {
        "ElementType" : 3,
        "Pic1" : 1002,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 316,
            2 : 317,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Value" : 0,
        "PickupLived" : 1,
        "Pic2" : 1002,
        "Effect1" : {
            1 : 60029,
            2 : 100,
            3 : -10,
            4 : 160,
        },
        "Id" : 3011,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "死亡营地（魔窟）",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 318,
            2 : 319,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10097,
    },
    3013 : {
        "ElementType" : 3,
        "Pic1" : 907,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 324,
            2 : 325,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Value" : 0,
        "PickupLived" : 1,
        "Pic2" : 907,
        "Effect1" : {
            1 : 60055,
            2 : 100,
            3 : 0,
            4 : 131,
        },
        "Id" : 3013,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "风之祭坛(魔窟)",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 326,
            2 : 327,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10097,
    },
    9006 : {
        "ElementType" : 3,
        "Pic1" : 301,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "Value" : 0,
        "PickupLived" : 1,
        "Pic2" : 1000,
        "Resetting" : 0,
        "Id" : 9006,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "RestrictStep" : 0,
        "Name" : "时空漩涡",
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 1,
            },
        },
        "Obstacle" : 0,
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10099,
    },
    30100 : {
        "ElementType" : 3,
        "Pic1" : 902,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10303,
        "Desc1" : {
            1 : 304,
            2 : 305,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Value" : 0,
        "PickupLived" : 1,
        "Pic2" : 902,
        "Effect1" : {
            1 : 60050,
            2 : 100,
            3 : -11,
            4 : 110,
        },
        "Id" : 30100,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "魔鬼之门（魔窟）",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 306,
            2 : 307,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10099,
    },
    30130 : {
        "ElementType" : 3,
        "Pic1" : 910,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 400,
            2 : 401,
        },
        "Effect3AddType" : 1,
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "Resetting" : 0,
        "PickupLived" : 1,
        "Pic2" : 910,
        "Effect1" : {
            1 : 60058,
            2 : 100,
            3 : 20,
            4 : 131,
        },
        "Id" : 30130,
        "PicType" : "1；1,2,x,y",
        "GetInto" : 1,
        "RestrictStep" : 0,
        "Name" : "地狱树屋(魔窟)",
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 17,
            },
        },
        "Obstacle" : 0,
        "Desc2" : {
            1 : 402,
            2 : 402,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10095,
    },
    3014 : {
        "ElementType" : 3,
        "Pic1" : 401,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 328,
            2 : 329,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "PickupLived" : 1,
        "Pic2" : 401,
        "Value" : 0,
        "Id" : 3014,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "练武场（魔窟）",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 330,
            2 : 331,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10099,
    },
    3009 : {
        "ElementType" : 3,
        "Pic1" : 904,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10303,
        "Desc1" : {
            1 : 308,
            2 : 309,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "Value" : 0,
        "PickupLived" : 1,
        "Pic2" : 904,
        "Effect1" : {
            1 : 60052,
            2 : 100,
            3 : 0,
            4 : 101,
        },
        "Id" : 3009,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "幽暗墓地（魔窟）",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 310,
            2 : 311,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10099,
    },
    30120 : {
        "ElementType" : 3,
        "Pic1" : 401,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 400,
            2 : 401,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "PickupLived" : 1,
        "Pic2" : 1000,
        "Value" : 0,
        "Id" : 30120,
        "PicType" : "1；1,2,x,y",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "练武场",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 402,
            2 : 402,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10097,
    },
    3010 : {
        "ElementType" : 3,
        "Pic1" : 904,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 312,
            2 : 313,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "Value" : 0,
        "PickupLived" : 1,
        "Pic2" : 904,
        "Effect1" : {
            1 : 60052,
            2 : 100,
            3 : 0,
            4 : 101,
        },
        "Id" : 3010,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "神秘城堡（魔窟）",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 314,
            2 : 315,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10097,
    },
    3004 : {
        "ElementType" : 3,
        "Pic1" : 301,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 1006,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "Pic2" : 1000,
        "Obstacle" : 0,
        "Id" : 3004,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Precondition" : {
            1 : {
                1 : 2,
                2 : 1,
            },
        },
        "Name" : "常态挂机点1",
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Value" : 0,
    },
    3002 : {
        "ElementType" : 3,
        "Pic1" : 300,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 1006,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "Pic2" : 1000,
        "Id" : 3002,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "据点",
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Effect3AddType" : 1,
    },
    3097 : {
        "ElementType" : 3,
        "Pic1" : 106,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "Pic2" : 106,
        "Id" : 3097,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "挂机点奖励3",
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Effect3AddType" : 1,
    },
    3099 : {
        "ElementType" : 3,
        "Pic1" : 106,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "Pic2" : 106,
        "Id" : 3099,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "挂机点奖励1",
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Effect3AddType" : 1,
    },
    3008 : {
        "ElementType" : 3,
        "Pic1" : 902,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10303,
        "Desc1" : {
            1 : 304,
            2 : 305,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Value" : 0,
        "PickupLived" : 1,
        "Pic2" : 902,
        "Effect1" : {
            1 : 60050,
            2 : 100,
            3 : -11,
            4 : 110,
        },
        "Id" : 3008,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "地狱之门（魔窟）",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 306,
            2 : 307,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10099,
    },
    4002 : {
        "ElementType" : 4,
        "Pic1" : 401,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Time" : 1800000,
        "Effect3AddType" : 1,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Obstacle" : 0,
        "RestrictLose" : 0,
        "Pic2" : 1000,
        "Resetting" : 0,
        "Id" : 4002,
        "PicType" : "1；1,2,x,y",
        "GetInto" : 1,
        "PickupLived" : 1,
        "RestrictStep" : 0,
        "Precondition" : {
            1 : {
                1 : 2,
                2 : 10,
            },
        },
        "Name" : "练武场",
        "Desc2" : {
            1 : 402,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "Desc1" : {
            1 : 400,
            2 : 401,
        },
        "Value" : 0,
    },
    3012 : {
        "ElementType" : 3,
        "Pic1" : 909,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 10403,
        "Desc1" : {
            1 : 320,
            2 : 321,
        },
        "Effect3AddType" : 1,
        "Value" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "Resetting" : 0,
        "PickupLived" : 1,
        "Pic2" : 909,
        "Effect1" : {
            1 : 60057,
            2 : 100,
            3 : 0,
            4 : 156,
        },
        "Id" : 3012,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "RestrictStep" : 0,
        "Name" : "被污染的工厂(魔窟)",
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 3,
            },
        },
        "Obstacle" : 0,
        "Desc2" : {
            1 : 322,
            2 : 323,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10096,
    },
    5001 : {
        "ElementType" : 5,
        "Pic1" : 401,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Time" : 1800000,
        "Value" : 0,
        "BossLimit" : 1021,
        "Resetting" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Desc1" : {
            1 : 500,
            2 : 501,
        },
        "PickupLived" : 1,
        "Pic2" : 401,
        "RestrictLose" : 0,
        "Id" : 5001,
        "PicType" : "1；1,2,x,y",
        "GetInto" : 1,
        "RestrictStep" : 0,
        "Name" : "1限挂(立即）",
        "Precondition" : {
            1 : {
                1 : 2,
                2 : 10,
            },
        },
        "Obstacle" : 0,
        "Desc2" : {
            1 : 502,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "Effect3AddType" : 1,
        "Reward" : 10098,
    },
    4003 : {
        "ElementType" : 4,
        "Pic1" : 910,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Time" : 1800000,
        "Effect3AddType" : 1,
        "Value" : 0,
        "Resetting" : 0,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "PickupLived" : 1,
        "Pic2" : 910,
        "Effect1" : {
            1 : 60058,
            2 : 100,
            3 : 20,
            4 : 131,
        },
        "Id" : 4003,
        "PicType" : "1；1,2,x,y",
        "GetInto" : 1,
        "RestrictStep" : 0,
        "Name" : "地狱树屋(魔窟)",
        "Precondition" : {
            1 : {
                1 : 1,
                2 : 17,
            },
        },
        "Obstacle" : 0,
        "Desc2" : {
            1 : 402,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "Desc1" : {
            1 : 400,
            2 : 401,
        },
        "Reward" : 10095,
    },
    3005 : {
        "ElementType" : 3,
        "Pic1" : 301,
        "Genre" : 2,
        "Effect3" : {
            1 : 60033,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 1,
        },
        "Boss" : 1006,
        "Desc1" : {
            1 : 300,
            2 : 301,
        },
        "Effect3AddType" : 1,
        "Area" : {
            1 : 3,
            2 : 3,
        },
        "RestrictLose" : 0,
        "Pic2" : 1000,
        "Obstacle" : 0,
        "Id" : 3005,
        "PicType" : "1；1,2,0,0",
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Precondition" : {
            1 : {
                1 : 2,
                2 : 5,
            },
        },
        "Name" : "常态挂机点2",
        "Desc2" : {
            1 : 302,
            2 : 303,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Value" : 0,
    },

};
module.exports = _p;
