/*
Don't modify this file manually!
*/
var _p = {
    10010 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10010,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "空沼泽",
        "Speed" : 1,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10003 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60072,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10003,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽3",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3213,
    },
    10011 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60073,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10011,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "2沼泽单格",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3221,
    },
    10004 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60071,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10004,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽4",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3214,
    },
    10012 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60074,
            2 : 100,
            3 : 5,
            4 : 50,
        },
        "Id" : 10012,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽2",
        "Area" : {
            1 : 1,
            2 : 2,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3222,
    },
    10020 : {
        "Direction" : 0,
        "LandType" : 1,
        "Id" : 10020,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "空沼泽",
        "Speed" : 1,
        "ElementType" : 30,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    10005 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60070,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10005,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽5",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3215,
    },
    10013 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60075,
            2 : 100,
            3 : -15,
            4 : 45,
        },
        "Id" : 10013,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽3",
        "Area" : {
            1 : 2,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3223,
    },
    10006 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60071,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10006,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽6",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3216,
    },
    10014 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60073,
            2 : 100,
            3 : -5,
            4 : 20,
        },
        "Id" : 10014,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽4",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3224,
    },
    10007 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60070,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10007,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽7",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3217,
    },
    10008 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60071,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10008,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽8",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3218,
    },
    20001 : {
        "Direction" : 2,
        "LandType" : 2,
        "Id" : 20001,
        "Genre" : 10,
        "Name" : "大风右",
        "Speed" : 0.4,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "ElementType" : 31,
        "Pic" : 0,
    },
    10001 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60070,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10001,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "1沼泽单格",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3211,
    },
    20002 : {
        "Direction" : 3,
        "LandType" : 2,
        "Id" : 20002,
        "Genre" : 10,
        "Name" : "大风上",
        "Speed" : 0.4,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "ElementType" : 31,
        "Pic" : 0,
    },
    20000 : {
        "Direction" : 1,
        "LandType" : 2,
        "Id" : 20000,
        "Genre" : 10,
        "Name" : "大风左",
        "Speed" : 0.4,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "ElementType" : 31,
        "Pic" : 0,
    },
    20003 : {
        "Direction" : 4,
        "LandType" : 2,
        "Id" : 20003,
        "Genre" : 10,
        "Name" : "大风下",
        "Speed" : 0.4,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "ElementType" : 31,
        "Pic" : 0,
    },
    10002 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60070,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10002,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽2",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3212,
    },
    10009 : {
        "Direction" : 0,
        "Effect1" : {
            1 : 60072,
            2 : 100,
            3 : -5,
            4 : 30,
        },
        "Id" : 10009,
        "Genre" : 10,
        "APCostTimes" : 3,
        "Name" : "沼泽9",
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Speed" : 1,
        "ElementType" : 30,
        "LandType" : 1,
        "Pic" : 3219,
    },

};
module.exports = _p;
