/*
Don't modify this file manually!
*/
var _p = {
    1 : {
        "InitPos" : {
            1 : 5,
            2 : 5,
        },
        "InfoFile" : "01.json",
        "MapId" : 1,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "APCost" : 5,
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "UnlockCondition3" : 0,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/01",
        "Area1" : 2,
        "ExitId" : 105,
        "UnlockCondition2" : 0,
    },
    2 : {
        "InitPos" : {
            1 : 10,
            2 : 4,
        },
        "InfoFile" : "02.json",
        "MapId" : 2,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "APCost" : 6,
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_bloodflower.png",
        "BGPic" : 201,
        "UnlockCondition3" : 0,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_02.png",
        "ResPath" : "res/map/02",
        "Area1" : 1447,
        "ExitId" : 816,
        "UnlockCondition2" : 0,
    },
    3 : {
        "InitPos" : {
            1 : 5,
            2 : 20,
        },
        "InfoFile" : "03.json",
        "MapId" : 3,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
        },
        "APCost" : 7,
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_bloodflower.png",
        "BGPic" : 201,
        "UnlockCondition3" : 0,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_03.png",
        "ResPath" : "res/map/03",
        "Area1" : 1359,
        "ExitId" : 1454,
        "UnlockCondition2" : 0,
    },
    4 : {
        "InitPos" : {
            1 : 2,
            2 : 6,
        },
        "InfoFile" : "04.json",
        "MapId" : 4,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 3,
            2 : 4,
            3 : 5,
        },
        "APCost" : 8,
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_waterland.png",
        "BGPic" : 201,
        "UnlockCondition3" : 0,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_04.png",
        "ResPath" : "res/map/04",
        "Area1" : 1483,
        "ExitId" : 1541,
        "UnlockCondition2" : 0,
    },
    100 : {
        "InitPos" : {
            1 : 5,
            2 : 5,
        },
        "InfoFile" : "100.json",
        "MapId" : 100,
        "UnlockCondition1" : 0,
        "MapSign" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "APCost" : 5,
        "ScenePic" : 1,
        "PicMapItem" : "res/ui/16_mapchoose/mapicon/mapicon_woodland.png",
        "BGPic" : 201,
        "UnlockCondition3" : 0,
        "PicMapName" : "res/ui/16_mapchoose/16_txt_map_01.png",
        "ResPath" : "res/map/100",
        "Area1" : 2,
        "ExitId" : 105,
        "UnlockCondition2" : 0,
    },

};
module.exports = _p;
