/*
Don't modify this file manually!
*/
var _p = {
    304072 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2013,
        "id" : 304072,
        "penetrationlevel" : 0,
        "hp" : 600,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪20",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    210019 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210019,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30013,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "天空龙",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2019,
        "tenacitylevel" : 0,
    },
    304073 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2024,
        "id" : 304073,
        "penetrationlevel" : 0,
        "hp" : 600,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪21",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    2101002 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 250,
        "modelid" : 2026,
        "id" : 2101002,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500002,
        "skillid" : {
            1 : 500002,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "血魔花",
    },
    304012 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2024,
        "id" : 304012,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪2",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "桂冠史莱姆",
    },
    304013 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2024,
        "id" : 304013,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪3",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    2202002 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2034,
        "id" : 2202002,
        "penetrationlevel" : 0,
        "hp" : 750,
        "normalattack" : 500007,
        "skillid" : {
            1 : 500007,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化天使",
    },
    210022 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210022,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "恶魔领主",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2022,
        "tenacitylevel" : 0,
    },
    2201002 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2027,
        "id" : 2201002,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500016,
        "skillid" : {
            1 : 500016,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化独角兽",
    },
    900001 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 180,
        "modelid" : 1007,
        "id" : 900001,
        "penetrationlevel" : 0,
        "hp" : 1500,
        "normalattack" : 30001,
        "skillid" : {
            1 : 50012,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "首战小菜鸟1号",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "血腥魔女",
    },
    1304012 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 2013,
        "id" : 1304012,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第四张图挂机点怪2",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "水史莱姆",
    },
    1304013 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 2024,
        "id" : 1304013,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张图挂机点怪3",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    900003 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 1500,
        "modelid" : 1012,
        "id" : 900003,
        "penetrationlevel" : 0,
        "hp" : 1500,
        "normalattack" : 30001,
        "skillid" : {
            1 : 50012,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "首战小菜鸟3号",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "恶魔亲王",
    },
    304082 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2013,
        "id" : 304082,
        "penetrationlevel" : 0,
        "hp" : 600,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪23",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    900004 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 1800,
        "modelid" : 1016,
        "id" : 900004,
        "penetrationlevel" : 0,
        "hp" : 8000,
        "normalattack" : 30001,
        "skillid" : {
            1 : 50009,
            2 : 50010,
            3 : 50011,
            4 : 30001,
        },
        "hitlevel" : 0,
        "name" : "首战大菜鸟1号",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "灭世魔王",
    },
    210024 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210024,
        "penetrationlevel" : 0,
        "hp" : 100,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "史莱姆",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2024,
        "tenacitylevel" : 0,
    },
    303063 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2025,
        "id" : 303063,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪18",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 14,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    1304021 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 2027,
        "id" : 1304021,
        "penetrationlevel" : 0,
        "hp" : 1500,
        "normalattack" : 500018,
        "skillid" : {
            1 : 500018,
        },
        "hitlevel" : 0,
        "name" : "第四张图挂机点怪4",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "狂暴独角兽",
    },
    1304022 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 1010,
        "id" : 1304022,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 30024,
        "skillid" : {
            1 : 30024,
        },
        "hitlevel" : 0,
        "name" : "第四张图挂机点怪5",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "暴走花木兰",
    },
    1304023 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 1015,
        "id" : 1304023,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 30024,
        "skillid" : {
            1 : 30024,
        },
        "hitlevel" : 0,
        "name" : "第四张图挂机点怪6",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "失控大力神",
    },
    304021 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2013,
        "id" : 304021,
        "penetrationlevel" : 0,
        "hp" : 1200,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪4",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    304022 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2013,
        "id" : 304022,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500005,
        "skillid" : {
            1 : 500005,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪5",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    1303012 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2026,
        "id" : 1303012,
        "penetrationlevel" : 0,
        "hp" : 600,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张图挂机点怪2",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "变异血魔花",
    },
    1303013 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2011,
        "id" : 1303013,
        "penetrationlevel" : 0,
        "hp" : 600,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张图挂机点怪3",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "丛林食人花",
    },
    304023 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2013,
        "id" : 304023,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪6",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    2402002 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 850,
        "modelid" : 2003,
        "id" : 2402002,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500016,
        "skillid" : {
            1 : 500016,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "邪法美杜莎",
    },
    1303021 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 2023,
        "id" : 1303021,
        "penetrationlevel" : 0,
        "hp" : 1500,
        "normalattack" : 500017,
        "skillid" : {
            1 : 500017,
        },
        "hitlevel" : 0,
        "name" : "第三张图挂机点怪4",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "光之子",
    },
    1303022 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 2026,
        "id" : 1303022,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张图挂机点怪5",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "变异血魔花",
    },
    210027 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210027,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "独角兽",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2027,
        "tenacitylevel" : 0,
    },
    2401002 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 850,
        "modelid" : 2014,
        "id" : 2401002,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500012,
        "skillid" : {
            1 : 500012,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "疯狂树精卫士",
    },
    210028 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210028,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30013,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "小火龙",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2028,
        "tenacitylevel" : 0,
    },
    304091 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2033,
        "id" : 304091,
        "penetrationlevel" : 0,
        "hp" : 1400,
        "normalattack" : 30027,
        "skillid" : {
            1 : 50013,
            2 : 30027,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪25",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 18,
        "dodgelevel" : 0,
        "None" : "九头龙",
    },
    1302013 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 250,
        "modelid" : 2011,
        "id" : 1302013,
        "penetrationlevel" : 0,
        "hp" : 150,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第二张图挂机点怪3",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 8,
        "dodgelevel" : 0,
        "None" : "低阶食人花",
    },
    302052 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2019,
        "id" : 302052,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500009,
        "skillid" : {
            1 : 500009,
        },
        "hitlevel" : 0,
        "name" : "第二张地图怪6",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 9,
        "dodgelevel" : 0,
        "None" : "天空龙",
    },
    210029 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210029,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "鲛人",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2029,
        "tenacitylevel" : 0,
    },
    302053 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2023,
        "id" : 302053,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第二张地图怪7",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "低阶光灵",
    },
    1302021 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2023,
        "id" : 1302021,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500017,
        "skillid" : {
            1 : 500017,
        },
        "hitlevel" : 0,
        "name" : "第二张图挂机点怪4",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 8,
        "dodgelevel" : 0,
        "None" : "光之子",
    },
    1302022 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2026,
        "id" : 1302022,
        "penetrationlevel" : 0,
        "hp" : 200,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第二张图挂机点怪5",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 8,
        "dodgelevel" : 0,
        "None" : "血魔花",
    },
    1302023 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2023,
        "id" : 1302023,
        "penetrationlevel" : 0,
        "hp" : 200,
        "normalattack" : 500007,
        "skillid" : {
            1 : 500007,
        },
        "hitlevel" : 0,
        "name" : "第二张图挂机点怪6",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 8,
        "dodgelevel" : 0,
        "None" : "低阶光灵",
    },
    210030 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210030,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "光元素",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2030,
        "tenacitylevel" : 0,
    },
    303012 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 350,
        "modelid" : 2003,
        "id" : 303012,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500018,
        "skillid" : {
            1 : 500018,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪2",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "美杜莎",
    },
    1301012 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 120,
        "modelid" : 2006,
        "id" : 1301012,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第一张图挂机点怪2",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 1,
        "dodgelevel" : 0,
        "None" : "嗜血巨虎",
    },
    210031 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210031,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "食尸鬼",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2031,
        "tenacitylevel" : 0,
    },
    210032 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210032,
        "penetrationlevel" : 0,
        "hp" : 100,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "斯芬克斯",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2032,
        "tenacitylevel" : 0,
    },
    210001 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210001,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "狮鹫兽",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2001,
        "tenacitylevel" : 0,
    },
    210033 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210033,
        "penetrationlevel" : 0,
        "hp" : 100,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "九头蛇",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2033,
        "tenacitylevel" : 0,
    },
    1300012 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 100,
        "modelid" : 1007,
        "id" : 1300012,
        "penetrationlevel" : 0,
        "hp" : 260,
        "normalattack" : 500002,
        "skillid" : {
            1 : 500002,
        },
        "hitlevel" : 0,
        "name" : "默认挂机点怪2",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 1,
        "dodgelevel" : 0,
        "None" : "时空恶魔",
    },
    210002 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210002,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "狮鹫兽",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2002,
        "tenacitylevel" : 0,
    },
    210034 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210034,
        "penetrationlevel" : 0,
        "hp" : 100,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30013,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "炽天使",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2034,
        "tenacitylevel" : 0,
    },
    210003 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210003,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30013,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "美杜莎",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2003,
        "tenacitylevel" : 0,
    },
    304041 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2013,
        "id" : 304041,
        "penetrationlevel" : 0,
        "hp" : 1200,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪10",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    304042 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2024,
        "id" : 304042,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500005,
        "skillid" : {
            1 : 500005,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪11",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "史莱姆王",
    },
    2101001 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 250,
        "modelid" : 2007,
        "id" : 2101001,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "蘑菇军团",
    },
    2101003 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 250,
        "modelid" : 2007,
        "id" : 2101003,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "蘑菇军团",
    },
    210005 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210005,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "火蜥蜴",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2005,
        "tenacitylevel" : 0,
    },
    210037 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210037,
        "penetrationlevel" : 0,
        "hp" : 100,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30001,
            2 : 30005,
        },
        "hitlevel" : 0,
        "name" : "古龙",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2037,
        "tenacitylevel" : 0,
    },
    2202001 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2001,
        "id" : 2202001,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化狮鹫",
    },
    2202003 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2001,
        "id" : 2202003,
        "penetrationlevel" : 0,
        "hp" : 750,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化狮鹫",
    },
    210006 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210006,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "巨虎",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2006,
        "tenacitylevel" : 0,
    },
    210038 : {
        "defense" : 50,
        "atk" : 300,
        "reducehurt" : 10,
        "id" : 210038,
        "penetrationlevel" : 0,
        "hp" : 2500,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30001,
            2 : 50009,
            3 : 50010,
            4 : 50011,
        },
        "hitlevel" : 0,
        "name" : "孔明（大王）",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 1009,
        "tenacitylevel" : 0,
    },
    2201001 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2023,
        "id" : 2201001,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "normalattack" : 500007,
        "skillid" : {
            1 : 500007,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "邪光灵",
    },
    2201003 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2023,
        "id" : 2201003,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500007,
        "skillid" : {
            1 : 500007,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "邪光灵",
    },
    210007 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210007,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30013,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "蘑菇军团",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2007,
        "tenacitylevel" : 0,
    },
    2302001 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2001,
        "id" : 2302001,
        "penetrationlevel" : 0,
        "hp" : 1200,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化狮鹫",
    },
    2302003 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2001,
        "id" : 2302003,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化狮鹫",
    },
    210008 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210008,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "火焰虎",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2008,
        "tenacitylevel" : 0,
    },
    302011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 160,
        "modelid" : 2011,
        "id" : 302011,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第二张地图怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 6,
        "dodgelevel" : 0,
        "None" : "丛林食人花",
    },
    304052 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2024,
        "id" : 304052,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500005,
        "skillid" : {
            1 : 500005,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪14",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "史莱姆王",
    },
    2301001 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2023,
        "id" : 2301001,
        "penetrationlevel" : 0,
        "hp" : 1200,
        "normalattack" : 500007,
        "skillid" : {
            1 : 500007,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "邪光灵",
    },
    2301003 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2023,
        "id" : 2301003,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500007,
        "skillid" : {
            1 : 500007,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "邪光灵",
    },
    1300011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 100,
        "modelid" : 2025,
        "id" : 1300011,
        "penetrationlevel" : 0,
        "hp" : 260,
        "normalattack" : 500008,
        "skillid" : {
            1 : 500008,
        },
        "hitlevel" : 0,
        "name" : "默认挂机点怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 1,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    210010 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210010,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "狮人",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2010,
        "tenacitylevel" : 0,
    },
    301011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 150,
        "modelid" : 2011,
        "id" : 301011,
        "penetrationlevel" : 0,
        "hp" : 400,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第一张地图出口怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 1,
        "dodgelevel" : 0,
        "None" : "丛林食人花",
    },
    2402001 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 850,
        "modelid" : 2031,
        "id" : 2402001,
        "penetrationlevel" : 0,
        "hp" : 1500,
        "normalattack" : 500011,
        "skillid" : {
            1 : 500011,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "下位食尸鬼",
    },
    2402003 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 850,
        "modelid" : 2031,
        "id" : 2402003,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500011,
        "skillid" : {
            1 : 500011,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "下位食尸鬼",
    },
    303013 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 350,
        "modelid" : 2007,
        "id" : 303013,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪3",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "蘑菇军团",
    },
    1303023 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 2023,
        "id" : 1303023,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500011,
        "skillid" : {
            1 : 500011,
        },
        "hitlevel" : 0,
        "name" : "第三张图挂机点怪6",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "低阶光灵",
    },
    1304011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 410,
        "modelid" : 2024,
        "id" : 1304011,
        "penetrationlevel" : 0,
        "hp" : 1500,
        "normalattack" : 500005,
        "skillid" : {
            1 : 500005,
        },
        "hitlevel" : 0,
        "name" : "第四张图挂机点怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "史莱姆王",
    },
    304083 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2024,
        "id" : 304083,
        "penetrationlevel" : 0,
        "hp" : 600,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪24",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    210011 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210011,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30013,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "食人花",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2011,
        "tenacitylevel" : 0,
    },
    1302011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 250,
        "modelid" : 2011,
        "id" : 1302011,
        "penetrationlevel" : 0,
        "hp" : 450,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第二张图挂机点怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 8,
        "dodgelevel" : 0,
        "None" : "丛林食人花",
    },
    302031 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 200,
        "modelid" : 2026,
        "id" : 302031,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第二张地图怪3",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 7,
        "dodgelevel" : 0,
        "None" : "变异血魔花",
    },
    302041 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 250,
        "modelid" : 2026,
        "id" : 302041,
        "penetrationlevel" : 0,
        "hp" : 900,
        "normalattack" : 500008,
        "skillid" : {
            1 : 500008,
        },
        "hitlevel" : 0,
        "name" : "第二张地图怪4",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 8,
        "dodgelevel" : 0,
        "None" : "梦魇血魔花",
    },
    2401001 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 850,
        "modelid" : 2011,
        "id" : 2401001,
        "penetrationlevel" : 0,
        "hp" : 1500,
        "normalattack" : 500011,
        "skillid" : {
            1 : 500011,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化食人花",
    },
    2401003 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 850,
        "modelid" : 2011,
        "id" : 2401003,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500011,
        "skillid" : {
            1 : 500011,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化食人花",
    },
    302051 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2023,
        "id" : 302051,
        "penetrationlevel" : 0,
        "hp" : 700,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第二张地图怪5",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 8,
        "dodgelevel" : 0,
        "None" : "低阶光灵",
    },
    303051 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2025,
        "id" : 303051,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪13",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 13,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    210012 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210012,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "火元素",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2012,
        "tenacitylevel" : 0,
    },
    1303011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 300,
        "modelid" : 2011,
        "id" : 1303011,
        "penetrationlevel" : 0,
        "hp" : 900,
        "normalattack" : 500011,
        "skillid" : {
            1 : 500011,
        },
        "hitlevel" : 0,
        "name" : "第三张图挂机点怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "邪魔食人花",
    },
    303042 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2004,
        "id" : 303042,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500002,
        "skillid" : {
            1 : 500002,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪11",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 12,
        "dodgelevel" : 0,
        "None" : "狂暴石像鬼",
    },
    303053 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2025,
        "id" : 303053,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪15",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 13,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    304081 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2024,
        "id" : 304081,
        "penetrationlevel" : 0,
        "hp" : 1300,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪22",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    303022 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 525,
        "modelid" : 2025,
        "id" : 303022,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500002,
        "skillid" : {
            1 : 500002,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪5",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 11,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    900005 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 20,
        "modelid" : 2007,
        "id" : 900005,
        "penetrationlevel" : 0,
        "hp" : 2000,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "把",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 1,
        "dodgelevel" : 0,
        "None" : "把",
    },
    210035 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210035,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30001,
            2 : 30005,
        },
        "hitlevel" : 0,
        "name" : "麒麟",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2035,
        "tenacitylevel" : 0,
    },
    210013 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210013,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "水元素",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2013,
        "tenacitylevel" : 0,
    },
    304061 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2024,
        "id" : 304061,
        "penetrationlevel" : 0,
        "hp" : 1300,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪16",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    2301002 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2027,
        "id" : 2301002,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500016,
        "skillid" : {
            1 : 500016,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化独角兽",
    },
    303021 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 525,
        "modelid" : 2025,
        "id" : 303021,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪4",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 11,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    1302012 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 250,
        "modelid" : 2026,
        "id" : 1302012,
        "penetrationlevel" : 0,
        "hp" : 150,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第二张图挂机点怪2",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 8,
        "dodgelevel" : 0,
        "None" : "变异血魔花",
    },
    304062 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2013,
        "id" : 304062,
        "penetrationlevel" : 0,
        "hp" : 600,
        "normalattack" : 500005,
        "skillid" : {
            1 : 500005,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪17",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    303023 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 525,
        "modelid" : 2025,
        "id" : 303023,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪6",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 11,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    210004 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210004,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "石像鬼",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2004,
        "tenacitylevel" : 0,
    },
    210014 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210014,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "树精卫士",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2014,
        "tenacitylevel" : 0,
    },
    304063 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2024,
        "id" : 304063,
        "penetrationlevel" : 0,
        "hp" : 600,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪18",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    210020 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210020,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "死亡骑士",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2020,
        "tenacitylevel" : 0,
    },
    210036 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210036,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30001,
            2 : 30007,
        },
        "hitlevel" : 0,
        "name" : "比蒙巨兽",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2036,
        "tenacitylevel" : 0,
    },
    303031 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 525,
        "modelid" : 2004,
        "id" : 303031,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪7",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 11,
        "dodgelevel" : 0,
        "None" : "狂暴石像鬼",
    },
    303041 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2025,
        "id" : 303041,
        "penetrationlevel" : 0,
        "hp" : 1000,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪10",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 12,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    210021 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210021,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "凤凰",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2021,
        "tenacitylevel" : 0,
    },
    1301011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 120,
        "modelid" : 2007,
        "id" : 1301011,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第一张图挂机点怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 1,
        "dodgelevel" : 0,
        "None" : "蘑菇群",
    },
    210015 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210015,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30013,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "地狱犬",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2015,
        "tenacitylevel" : 0,
    },
    303061 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2025,
        "id" : 303061,
        "penetrationlevel" : 0,
        "hp" : 1200,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪16",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 14,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    304011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2024,
        "id" : 304011,
        "penetrationlevel" : 0,
        "hp" : 1200,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    303062 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2020,
        "id" : 303062,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500008,
        "skillid" : {
            1 : 500008,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪17",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 14,
        "dodgelevel" : 0,
        "None" : "死亡骑士",
    },
    210023 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210023,
        "penetrationlevel" : 0,
        "hp" : 100,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "光灵",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2023,
        "tenacitylevel" : 0,
    },
    303043 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2025,
        "id" : 303043,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪12",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 12,
        "dodgelevel" : 0,
        "None" : "骷髅",
    },
    303032 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 525,
        "modelid" : 2004,
        "id" : 303032,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500002,
        "skillid" : {
            1 : 500002,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪8",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 11,
        "dodgelevel" : 0,
        "None" : "狂暴石像鬼",
    },
    304051 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2013,
        "id" : 304051,
        "penetrationlevel" : 0,
        "hp" : 1200,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪13",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    210016 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210016,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "熔岩巨人",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2016,
        "tenacitylevel" : 0,
    },
    304031 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2024,
        "id" : 304031,
        "penetrationlevel" : 0,
        "hp" : 1200,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪7",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    304032 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2013,
        "id" : 304032,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪8",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    210009 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210009,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "巨蜥",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2009,
        "tenacitylevel" : 0,
    },
    210025 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210025,
        "penetrationlevel" : 0,
        "hp" : 100,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30013,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "骷髅兵",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2025,
        "tenacitylevel" : 0,
    },
    303052 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 650,
        "modelid" : 2004,
        "id" : 303052,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500002,
        "skillid" : {
            1 : 500002,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪14",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 13,
        "dodgelevel" : 0,
        "None" : "狂怒石像鬼",
    },
    304043 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2013,
        "id" : 304043,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪12",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    210026 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210026,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "血魔花",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2026,
        "tenacitylevel" : 0,
    },
    210017 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210017,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30005,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "伊芙利特",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2017,
        "tenacitylevel" : 0,
    },
    2302002 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 800,
        "modelid" : 2034,
        "id" : 2302002,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500007,
        "skillid" : {
            1 : 500007,
        },
        "hitlevel" : 0,
        "name" : "挂机点挑战怪",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 15,
        "dodgelevel" : 0,
        "None" : "魔化炽天使",
    },
    304053 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2013,
        "id" : 304053,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500014,
        "skillid" : {
            1 : 500014,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪15",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "疯狂水元素",
    },
    303033 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 525,
        "modelid" : 2004,
        "id" : 303033,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪9",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 11,
        "dodgelevel" : 0,
        "None" : "狂暴石像鬼",
    },
    302021 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 160,
        "modelid" : 2031,
        "id" : 302021,
        "penetrationlevel" : 0,
        "hp" : 800,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第二张地图怪2",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 6,
        "dodgelevel" : 0,
        "None" : "沼泽尸鬼",
    },
    301010 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 150,
        "modelid" : 1001,
        "id" : 301010,
        "penetrationlevel" : 0,
        "hp" : 300,
        "normalattack" : 30001,
        "skillid" : {
            1 : 30001,
        },
        "hitlevel" : 0,
        "name" : "第一张地图怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 1,
        "dodgelevel" : 0,
        "None" : "疯狂守桥人",
    },
    900002 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 1800,
        "modelid" : 1014,
        "id" : 900002,
        "penetrationlevel" : 0,
        "hp" : 1800,
        "normalattack" : 30001,
        "skillid" : {
            1 : 50012,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "首战小菜鸟2号",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "魔王仆从",
    },
    303011 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 350,
        "modelid" : 2007,
        "id" : 303011,
        "penetrationlevel" : 0,
        "hp" : 700,
        "normalattack" : 500001,
        "skillid" : {
            1 : 500001,
        },
        "hitlevel" : 0,
        "name" : "第三张地图怪1",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 10,
        "dodgelevel" : 0,
        "None" : "蘑菇军团",
    },
    210018 : {
        "defense" : 40,
        "atk" : 70,
        "reducehurt" : 10,
        "id" : 210018,
        "penetrationlevel" : 0,
        "hp" : 200,
        "dodgelevel" : 0,
        "skillid" : {
            1 : 30007,
            2 : 30001,
        },
        "hitlevel" : 0,
        "name" : "石巨人",
        "critlevel" : 0,
        "normalattack" : 30001,
        "level" : 10,
        "modelid" : 2018,
        "tenacitylevel" : 0,
    },
    304071 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 900,
        "modelid" : 2024,
        "id" : 304071,
        "penetrationlevel" : 0,
        "hp" : 1300,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪19",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 17,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },
    304033 : {
        "reducehurt" : 0,
        "defense" : 0,
        "atk" : 880,
        "modelid" : 2024,
        "id" : 304033,
        "penetrationlevel" : 0,
        "hp" : 500,
        "normalattack" : 500004,
        "skillid" : {
            1 : 500004,
        },
        "hitlevel" : 0,
        "name" : "第四张地图怪9",
        "critlevel" : 0,
        "tenacitylevel" : 0,
        "level" : 16,
        "dodgelevel" : 0,
        "None" : "湖畔史莱姆",
    },

};
module.exports = _p;
