/*
Don't modify this file manually!
*/
var _p = {
    6001 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1004,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6001,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "绿精灵",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10008,
    },
    6005 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1016,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6005,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "怪物2",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6009 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1020,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6009,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "4怪物1",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6021 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3661,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 603,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10201,
        "RestrictLose" : 0,
        "Pic2" : 3661,
        "Id" : 6021,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "食人花",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10141,
    },
    6025 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3645,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 607,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10302,
        "RestrictLose" : 0,
        "Pic2" : 3645,
        "Id" : 6025,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "骷髅",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10147,
    },
    6029 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3659,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 611,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10402,
        "RestrictLose" : 0,
        "Pic2" : 3659,
        "Id" : 6029,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "水元素",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10153,
    },
    6002 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1005,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6002,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "蛇女",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10010,
    },
    6006 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1017,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6006,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "3怪物1",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6010 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1021,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6010,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "4怪物2",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6022 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3621,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 604,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10202,
        "RestrictLose" : 0,
        "Pic2" : 3621,
        "Id" : 6022,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "食尸鬼",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10142,
    },
    6026 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3619,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 608,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10303,
        "RestrictLose" : 0,
        "Pic2" : 3619,
        "Id" : 6026,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "石像鬼",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10148,
    },
    6030 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3659,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 612,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10403,
        "RestrictLose" : 0,
        "Pic2" : 3659,
        "Id" : 6030,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "水元素",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10154,
    },
    6003 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1006,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6003,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "美杜莎",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6007 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1018,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6007,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "3怪物2",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6011 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1022,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6011,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "4怪物3",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6019 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3637,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 601,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10100,
        "RestrictLose" : 0,
        "Pic2" : 3637,
        "Id" : 6019,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "蘑菇军团",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10138,
    },
    6023 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3607,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 605,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10203,
        "RestrictLose" : 0,
        "Pic2" : 3607,
        "Id" : 6023,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "血魔花",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10143,
    },
    6027 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3619,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 609,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10305,
        "RestrictLose" : 0,
        "Pic2" : 3619,
        "Id" : 6027,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "石像鬼",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10150,
    },
    6031 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3649,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 613,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10404,
        "RestrictLose" : 0,
        "Pic2" : 3649,
        "Id" : 6031,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "史莱姆",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10155,
    },
    6004 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1015,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6004,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "怪物1",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6008 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 601,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 600,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 1019,
        "RestrictLose" : 0,
        "Pic2" : 601,
        "Id" : 6008,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "3怪物3",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10009,
    },
    6020 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3661,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 602,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10201,
        "RestrictLose" : 0,
        "Pic2" : 3661,
        "Id" : 6020,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "食人花",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10139,
    },
    6024 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : -30,
                4 : 90,
                5 : 2,
            },
        },
        "ElementType" : 6,
        "Pic1" : 600,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 606,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10301,
        "RestrictLose" : 0,
        "Pic2" : 600,
        "Id" : 6024,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "美杜莎",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10146,
    },
    6028 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3649,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 610,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10401,
        "RestrictLose" : 0,
        "Pic2" : 3649,
        "Id" : 6028,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "史莱姆",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10152,
    },
    6032 : {
        "Effect2" : {
            1 : {
                1 : 60066,
                2 : 100,
                3 : 0,
                4 : 90,
                5 : 1,
            },
        },
        "ElementType" : 6,
        "Pic1" : 3649,
        "Genre" : 3,
        "Effect3" : {
            1 : 60030,
            2 : 100,
            3 : 0,
            4 : 0,
            5 : 2,
        },
        "Desc1" : 614,
        "Value" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10405,
        "RestrictLose" : 0,
        "Pic2" : 3649,
        "Id" : 6032,
        "GetInto" : 0,
        "Effect3AddType" : 1,
        "Resetting" : 0,
        "Name" : "史莱姆",
        "Obstacle" : 1,
        "RestrictStep" : 1,
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 0,
        "Reward" : 10156,
    },

};
module.exports = _p;
