/*
Don't modify this file manually!
*/
var _p = {
    10095 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 3,
            4 : 0,
        },
        "Id" : 10095,
        "ShowItem" : {
            1 : 10001,
            2 : 10002,
        },
        "AP" : 5,
        "Experience" : 40,
        "IfShowR" : 0,
        "Money" : 90,
        "Name" : "4限挂奖励2",
        "Experience2" : 40,
    },
    10096 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 3,
            4 : 0,
        },
        "Id" : 10096,
        "ShowItem" : {
            1 : 10001,
            2 : 10002,
        },
        "AP" : 5,
        "Experience" : 20,
        "IfShowR" : 0,
        "Money" : 200,
        "Name" : "4挂机奖励1",
        "Experience2" : 20,
    },
    10097 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 3,
            4 : 0,
        },
        "Id" : 10097,
        "ShowItem" : {
            1 : 10001,
            2 : 10002,
        },
        "AP" : 5,
        "Experience" : 15,
        "IfShowR" : 0,
        "Money" : 150,
        "Name" : "3挂机奖励1",
        "Experience2" : 15,
    },
    10098 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 3,
            4 : 0,
        },
        "Id" : 10098,
        "ShowItem" : {
            1 : 10001,
            2 : 10002,
            3 : 16002,
        },
        "AP" : 5,
        "Experience" : 90,
        "IfShowR" : 1,
        "Money" : 90,
        "Name" : "1限挂奖励2",
        "Experience2" : 90,
    },
    10099 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 3,
            4 : 0,
        },
        "Id" : 10099,
        "ShowItem" : {
            1 : 10001,
            2 : 10002,
            3 : 16001,
        },
        "AP" : 5,
        "Experience" : 10,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "1挂机奖励1",
        "Experience2" : 10,
    },
    10101 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10101,
        "Experience2" : 100,
        "AP" : 0,
        "Experience" : 100,
        "IfShowR" : 1,
        "Money" : 500,
        "Name" : "1新手宝箱1",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10001,
    },
    10103 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10103,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "2项链3",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10019,
    },
    10104 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10104,
        "Experience2" : 200,
        "AP" : 0,
        "Experience" : 200,
        "IfShowR" : 1,
        "Money" : 500,
        "Name" : "1新手宝箱2",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10001,
    },
    10106 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10106,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "3卡特琳娜碎片",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10004,
    },
    10107 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10107,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "3曹操碎片",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10005,
    },
    10108 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10108,
        "Experience2" : 250,
        "AP" : 0,
        "Experience" : 250,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "2新手宝箱-装备1",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10002,
    },
    10109 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10109,
        "Experience2" : 250,
        "AP" : 0,
        "Experience" : 250,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "2新手宝箱-装备2",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10003,
    },
    10110 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10110,
        "Experience2" : 5,
        "AP" : 0,
        "Experience" : 5,
        "IfShowR" : 1,
        "Money" : 1000,
        "Name" : "3新手宝箱-中",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10007,
    },
    10114 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10114,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "3一阶武器卷轴",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10024,
    },
    10116 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10116,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "3铁矿石（一阶）",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10010,
    },
    10117 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10117,
        "Experience2" : 5,
        "AP" : 0,
        "Experience" : 5,
        "IfShowR" : 1,
        "Money" : 2000,
        "Name" : "3大宝箱",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10025,
    },
    10118 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10118,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "4铁矿石（一阶）",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10010,
    },
    10119 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10119,
        "Experience2" : 0,
        "AP" : 0,
        "Money" : 0,
        "Experience" : 0,
        "Drop" : 10001,
        "Sign" : 3,
        "Name" : "4神秘木箱",
        "ShowItem" : {
            1 : 12005,
        },
        "IfShowR" : 1,
    },
    10120 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10120,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "4一阶项链卷轴",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10009,
    },
    10121 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10121,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "4铁矿石（二阶）",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10009,
    },
    10122 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10122,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "4新手宝箱-中",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10001,
    },
    10123 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10123,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 1000,
        "Name" : "4新手宝箱-中",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10001,
    },
    10124 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10124,
        "Experience2" : 0,
        "AP" : 0,
        "Money" : 3000,
        "Experience" : 0,
        "Drop" : 10001,
        "Sign" : 5,
        "Name" : "4高级宝箱",
        "ShowItem" : {
            1 : 12005,
        },
        "IfShowR" : 1,
    },
    10126 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10126,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "2武器",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10002,
    },
    10127 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10127,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "2戒指",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10018,
    },
    10001 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 3,
            4 : 4,
            5 : 0,
        },
        "Experience2" : 500,
        "Experience" : 500,
        "IfShowR" : 1,
        "Id" : 10001,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 500,
        "AP" : 0,
    },
    10002 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10002,
        "ShowItem" : {
            1 : 12007,
        },
        "AP" : 0,
        "Experience" : 800,
        "IfShowR" : 1,
        "Money" : 800,
        "Name" : "综合奖励",
        "Experience2" : 800,
    },
    10003 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Experience2" : 1000,
        "Experience" : 1000,
        "IfShowR" : 1,
        "Id" : 10003,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 1000,
        "AP" : 0,
    },
    10004 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Experience2" : 115,
        "Experience" : 115,
        "IfShowR" : 1,
        "Id" : 10004,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 85,
        "AP" : 0,
    },
    10005 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Experience2" : 140,
        "Experience" : 140,
        "IfShowR" : 1,
        "Id" : 10005,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 90,
        "AP" : 0,
    },
    10006 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Experience2" : 180,
        "Experience" : 180,
        "IfShowR" : 1,
        "Id" : 10006,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 100,
        "AP" : 0,
    },
    10007 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Experience2" : 200,
        "Experience" : 200,
        "IfShowR" : 1,
        "Id" : 10007,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 200,
        "AP" : 0,
    },
    10008 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Experience2" : 300,
        "Experience" : 300,
        "IfShowR" : 1,
        "Id" : 10008,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 300,
        "AP" : 0,
    },
    10009 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Experience2" : 500,
        "Experience" : 500,
        "IfShowR" : 1,
        "Id" : 10009,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 500,
        "AP" : 0,
    },
    10010 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Experience2" : 400,
        "Experience" : 400,
        "IfShowR" : 1,
        "Id" : 10010,
        "ShowItem" : {
            1 : 12005,
        },
        "Money" : 400,
        "AP" : 0,
    },
    10011 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10011,
        "ShowItem" : {
            1 : 12005,
        },
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 1000,
        "Name" : "1000金币",
        "Experience2" : 0,
    },
    10012 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10012,
        "ShowItem" : {
            1 : 12006,
        },
        "AP" : 0,
        "Experience" : 1000,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "1000经验",
        "Experience2" : 1000,
    },
    10013 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10013,
        "ShowItem" : {
            1 : 12007,
        },
        "AP" : 500,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "500步数",
        "Experience2" : 0,
    },
    10014 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10014,
        "ShowItem" : {
            1 : 12005,
        },
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 5000,
        "Name" : "5000金币",
        "Experience2" : 0,
    },
    10015 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10015,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "初级魔力铲",
        "ShowItem" : {
            1 : 10001,
        },
        "Drop" : 3011,
    },
    10016 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10016,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "暴风指环",
        "ShowItem" : {
            1 : 10151,
        },
        "Drop" : 3012,
    },
    10017 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 3,
            4 : 0,
        },
        "Id" : 10017,
        "Experience2" : 10000,
        "AP" : 100,
        "Experience" : 10000,
        "IfShowR" : 1,
        "Money" : 10000,
        "Name" : "连续挑战奖励",
        "ShowItem" : {
            1 : 10001,
            2 : 10151,
            3 : 17902,
        },
        "Drop" : 3013,
    },
    10018 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 3,
            4 : 0,
        },
        "Id" : 10018,
        "Experience2" : 450,
        "AP" : 210,
        "Experience" : 400,
        "IfShowR" : 1,
        "Sign" : 1,
        "Money" : 350,
        "Name" : "掉落标记的奖励",
        "ShowItem" : {
            1 : 12005,
        },
    },
    10019 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10019,
        "ShowItem" : {
            1 : 12007,
        },
        "AP" : 300,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 0,
        "Name" : "300步数",
        "Experience2" : 0,
    },
    10020 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10020,
        "ShowItem" : {
            1 : 12007,
        },
        "AP" : 400,
        "Experience" : 0,
        "IfShowR" : 0,
        "Money" : 0,
        "Name" : "400步数",
        "Experience2" : 0,
    },
    10021 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10021,
        "ShowItem" : {
            1 : 12005,
        },
        "AP" : 0,
        "Experience" : 5000,
        "IfShowR" : 1,
        "Money" : 5000,
        "Name" : "5000金币",
        "Experience2" : 0,
    },
    10149 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10149,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第三张图未知建筑怪9018",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10150 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10150,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第三张图怪4",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10151 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10151,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第三张图出口怪",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10152 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10152,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图怪1",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10153 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10153,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图怪2",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10154 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10154,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图怪3",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10155 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10155,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图怪4",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10156 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10156,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图怪5",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10157 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10157,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图未知建筑怪9022",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10158 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10158,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图未知建筑怪9024",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10159 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10159,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图未知建筑怪9026",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10160 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10160,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第四张图出口怪",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10182 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 1500,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Id" : 10182,
        "Name" : "1500金币",
        "ShowItem" : {
            1 : 12005,
        },
        "None" : "地图2光灵--2005左边奖励",
    },
    10183 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 3000,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Id" : 10183,
        "Name" : "3000金币",
        "ShowItem" : {
            1 : 12005,
        },
        "None" : "地图2光灵--2005右边奖励",
    },
    10184 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 0,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10184,
        "Experience" : 0,
        "Drop" : 10020,
        "Name" : "皮甲",
        "ShowItem" : {
            1 : 110103,
        },
        "IfShowR" : 1,
        "None" : "地图2聚宝盆--2006左边奖励",
    },
    10185 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 0,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10185,
        "Experience" : 0,
        "Drop" : 10021,
        "Name" : "便鞋",
        "ShowItem" : {
            1 : 110104,
        },
        "IfShowR" : 1,
        "None" : "地图2聚宝盆--2006右边奖励",
    },
    10186 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 0,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10186,
        "Experience" : 0,
        "Drop" : 10029,
        "Name" : "一阶戒指卷",
        "ShowItem" : {
            1 : 16005,
        },
        "IfShowR" : 1,
        "None" : "地图3——2007左边奖励",
    },
    10187 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 0,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10187,
        "Experience" : 0,
        "Drop" : 10010,
        "Name" : "原铁x5",
        "ShowItem" : {
            1 : 15101,
        },
        "IfShowR" : 1,
        "None" : "地图3——2007右边奖励",
    },
    10188 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 0,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10188,
        "Experience" : 0,
        "IfShowR" : 1,
        "Sign" : 2,
        "Name" : "金钥匙",
        "ShowItem" : {
            1 : 19204,
        },
        "None" : "地图3——2008左边奖励",
    },
    10189 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 0,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10189,
        "Experience" : 0,
        "IfShowR" : 1,
        "Sign" : 2,
        "Name" : "铜钥匙",
        "ShowItem" : {
            1 : 19204,
        },
        "None" : "地图3——2008右边奖励",
    },
    10190 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 0,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10190,
        "Experience" : 0,
        "IfShowR" : 1,
        "Sign" : 4,
        "Name" : "《皮克斯》",
        "ShowItem" : {
            1 : 19203,
        },
        "None" : "地图4——2009左边奖励",
    },
    10191 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 0,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10191,
        "Experience" : 0,
        "IfShowR" : 1,
        "Sign" : 4,
        "Name" : "《迪斯尼》",
        "ShowItem" : {
            1 : 19203,
        },
        "None" : "地图4——2009右边奖励",
    },
    10138 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10138,
        "ShowItem" : {
            1 : 12005,
        },
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第一张图怪1",
        "Experience2" : 0,
    },
    10200 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 1500,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10200,
        "Experience" : 0,
        "Drop" : 10020,
        "Name" : "皮甲",
        "ShowItem" : {
            1 : 110103,
        },
        "IfShowR" : 1,
        "None" : "未知建筑纯奖励9015",
    },
    10201 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 1500,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10201,
        "Experience" : 0,
        "Drop" : 10006,
        "Name" : "卡特琳娜碎片",
        "ShowItem" : {
            1 : 19011,
        },
        "IfShowR" : 1,
        "None" : "未知建筑纯奖励9017",
    },
    10140 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10140,
        "ShowItem" : {
            1 : 12005,
        },
        "AP" : 0,
        "Experience" : 500,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第一张图出口怪",
        "Experience2" : 500,
    },
    10203 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 1500,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10203,
        "Experience" : 0,
        "Drop" : 10007,
        "Name" : "一阶武器卷轴",
        "ShowItem" : {
            1 : 16001,
        },
        "IfShowR" : 1,
        "None" : "未知建筑纯奖励9020",
    },
    10204 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 1500,
        "Experience2" : 0,
        "AP" : 0,
        "Id" : 10204,
        "Experience" : 0,
        "Drop" : 10008,
        "Name" : "一阶鞋子卷",
        "ShowItem" : {
            1 : 16004,
        },
        "IfShowR" : 1,
        "None" : "未知建筑纯奖励9021",
    },
    10139 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10139,
        "ShowItem" : {
            1 : 12005,
        },
        "AP" : 0,
        "Experience" : 250,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第二张图怪1",
        "Experience2" : 250,
    },
    10206 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Money" : 1500,
        "Experience2" : 0,
        "AP" : 0,
        "Experience" : 0,
        "IfShowR" : 1,
        "Id" : 10206,
        "Name" : "礼包",
        "ShowItem" : {
            1 : 19202,
        },
        "None" : "未知建筑纯奖励9025",
    },
    10141 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10141,
        "Experience2" : 250,
        "AP" : 0,
        "Experience" : 250,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第二张图怪2",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10022,
    },
    10142 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10142,
        "Experience2" : 500,
        "AP" : 0,
        "Experience" : 500,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第二张图怪3",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10023,
    },
    10143 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10143,
        "Experience2" : 500,
        "AP" : 0,
        "Experience" : 500,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第二张图怪4",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10003,
    },
    10144 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10144,
        "Experience2" : 500,
        "AP" : 0,
        "Experience" : 500,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第二张图未知建筑怪9016",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10145 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10145,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第二张图出口怪",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10147 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10147,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第三张图怪2",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10148 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10148,
        "Experience2" : 600,
        "AP" : 0,
        "Experience" : 600,
        "IfShowR" : 1,
        "Money" : 100,
        "Name" : "第三张图怪3",
        "ShowItem" : {
            1 : 12005,
        },
        "Drop" : 10015,
    },
    10146 : {
        "Enabled" : {
            1 : 1,
            2 : 2,
            3 : 0,
        },
        "Id" : 10146,
        "Experience2" : 600,
        "AP" : 0,
        "Money" : 100,
        "Experience" : 600,
        "Drop" : 10015,
        "Sign" : 1,
        "Name" : "第三张图掉标记怪1",
        "ShowItem" : {
            1 : 12005,
        },
        "IfShowR" : 1,
    },

};
module.exports = _p;
