/*
Don't modify this file manually!
*/
var _p = {
    15003 : {
        "ElementType" : 15,
        "Pic1" : 908,
        "Genre" : 4,
        "Desc1" : 1500,
        "Value" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "RestrictLose" : 0,
        "RestrictStep" : 0,
        "Effect1" : {
            1 : 60056,
            2 : 100,
            3 : 0,
            4 : 104,
        },
        "Id" : 15003,
        "SellGroup" : {
            1 : 4,
            2 : 5,
            3 : 6,
        },
        "GetInto" : 1,
        "Name" : "4黑心商店",
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Pic2" : 908,
    },
    15002 : {
        "ElementType" : 15,
        "Pic1" : 1501,
        "Genre" : 4,
        "Desc1" : 1500,
        "Value" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "RestrictLose" : 0,
        "RestrictStep" : 0,
        "Effect1" : {
            1 : 60048,
            2 : 100,
            3 : -17,
            4 : 109,
        },
        "Id" : 15002,
        "SellGroup" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "GetInto" : 1,
        "Name" : "黑心商店",
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Pic2" : 1501,
    },
    15001 : {
        "ElementType" : 15,
        "Pic1" : 1500,
        "Genre" : 4,
        "Desc1" : 1500,
        "Value" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "RestrictLose" : 0,
        "RestrictStep" : 0,
        "Effect1" : {
            1 : 60048,
            2 : 100,
            3 : -17,
            4 : 109,
        },
        "Id" : 15001,
        "SellGroup" : {
            1 : 1,
            2 : 2,
            3 : 3,
        },
        "GetInto" : 1,
        "Name" : "黑心商店",
        "Obstacle" : 0,
        "Resetting" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Pic2" : 1500,
    },

};
module.exports = _p;
