/*
Don't modify this file manually!
*/
var _p = {
    3030 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3030,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20014,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3062 : {
        "arg2" : 4000,
        "effecttype" : 1,
        "id" : 3062,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3031 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3031,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20015,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3063 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 3063,
        "arg3" : 500,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    1004 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 1004,
        "arg3" : 27,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    1012 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 1012,
        "arg3" : 50,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3032 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3032,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20016,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3064 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3064,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20037,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3001 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 3001,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3033 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3033,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20017,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3065 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3065,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20042,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3002 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3002,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20032,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3034 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3034,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20018,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3003 : {
        "arg2" : 0,
        "effecttype" : 0,
        "id" : 3003,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 0,
        "status" : {
            1 : 60001,
            2 : 9001,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3035 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3035,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20019,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    1005 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 1005,
        "arg3" : 36,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3004 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3004,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20033,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3036 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3036,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20020,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3005 : {
        "arg2" : 0,
        "effecttype" : 4,
        "id" : 3005,
        "arg3" : 1,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 50,
        "arg6" : 60,
        "arg1" : 100,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 100,
        "arg7" : 1,
        "arg8" : 0,
    },
    3037 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3037,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20021,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3006 : {
        "arg2" : 4,
        "effecttype" : 3,
        "id" : 3006,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 3,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3038 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3038,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20022,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3007 : {
        "arg2" : 10,
        "effecttype" : 1,
        "id" : 3007,
        "arg3" : 100,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3039 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3039,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20023,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    1006 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 1006,
        "arg3" : 52,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3008 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3008,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20034,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3040 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3040,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20024,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3009 : {
        "arg2" : 0,
        "effecttype" : 0,
        "id" : 3009,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 0,
        "status" : {
            1 : 60004,
            2 : 9001,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3041 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3041,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20025,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3010 : {
        "arg2" : 60,
        "effecttype" : 1,
        "id" : 3010,
        "arg3" : 150,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3042 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3042,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20026,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3011 : {
        "arg2" : 3,
        "effecttype" : 3,
        "id" : 3011,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 2,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3043 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3043,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20027,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    1007 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 1007,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20043,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3012 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3012,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20038,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3044 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3044,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20028,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3013 : {
        "arg2" : 100,
        "effecttype" : 1,
        "id" : 3013,
        "arg3" : 300,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3045 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3045,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20029,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3014 : {
        "arg2" : 2,
        "effecttype" : 2,
        "id" : 3014,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 150,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3046 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3046,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20030,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3015 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3015,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20040,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3047 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3047,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20031,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    1008 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 1008,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20044,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3016 : {
        "arg2" : 100,
        "effecttype" : 1,
        "id" : 3016,
        "arg3" : 200,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3048 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3048,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20032,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    4001 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 4001,
        "arg3" : 100,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3017 : {
        "arg2" : 100,
        "effecttype" : 1,
        "id" : 3017,
        "arg3" : 200,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3049 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3049,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20033,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    4002 : {
        "arg2" : 0,
        "effecttype" : 0,
        "id" : 4002,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 0,
        "status" : {
            1 : 60002,
            2 : 9001,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 1,
    },
    3018 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 3018,
        "arg3" : 50,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3050 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3050,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20034,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    4003 : {
        "arg2" : 0,
        "effecttype" : 0,
        "id" : 4003,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 0,
        "status" : {
            1 : 60003,
            2 : 9001,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3019 : {
        "arg2" : 0,
        "effecttype" : 0,
        "id" : 3019,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 0,
        "status" : {
            1 : 60006,
            2 : 9001,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3051 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3051,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20035,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    1001 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 1001,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    4004 : {
        "arg2" : 0,
        "effecttype" : 0,
        "id" : 4004,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20005,
        "status" : {
            1 : 60005,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 1,
    },
    3020 : {
        "arg2" : 10,
        "effecttype" : 1,
        "id" : 3020,
        "arg3" : 50,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3052 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3052,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20036,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    4005 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 4005,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3021 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3021,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20002,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3053 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3053,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20037,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3022 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3022,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20006,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3054 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3054,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20038,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3023 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3023,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20007,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3055 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3055,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20039,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    1002 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 1002,
        "arg3" : 10,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    1010 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 1010,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20045,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3024 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3024,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20008,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3056 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3056,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20040,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3025 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3025,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20009,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3057 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3057,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20041,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3026 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3026,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20010,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3058 : {
        "arg2" : 0,
        "effecttype" : 5,
        "id" : 3058,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3027 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3027,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20011,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3059 : {
        "arg2" : 100,
        "effecttype" : 1,
        "id" : 3059,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    1003 : {
        "arg2" : 0,
        "effecttype" : 1,
        "id" : 1003,
        "arg3" : 18,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    1011 : {
        "arg2" : 60,
        "effecttype" : 1,
        "id" : 1011,
        "arg3" : 150,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 1,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    3028 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3028,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20012,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3060 : {
        "arg2" : 5,
        "effecttype" : 3,
        "id" : 3060,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 4,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3029 : {
        "arg2" : 0,
        "effecttype" : 6,
        "id" : 3029,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 20013,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },
    3061 : {
        "arg2" : 2000,
        "effecttype" : 1,
        "id" : 3061,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 1,
        "status" : {
            1 : 0,
            2 : 0,
        },
        "arg4" : 1,
        "arg7" : 0,
        "arg8" : 0,
    },
    1009 : {
        "arg2" : 0,
        "effecttype" : 0,
        "id" : 1009,
        "arg3" : 0,
        "dispel" : {
            1 : 0,
            2 : 0,
        },
        "arg5" : 0,
        "arg6" : 0,
        "arg1" : 0,
        "status" : {
            1 : 60001,
            2 : 9001,
        },
        "arg4" : 0,
        "arg7" : 0,
        "arg8" : 0,
    },

};
module.exports = _p;
