/*
Don't modify this file manually!
*/
var _p = {
    60003 : {
        "triggerresultid" : {
            1 : 0,
            2 : 0,
        },
        "id" : 60003,
        "duration" : 0,
        "staturesultsid" : 6003,
        "desc" : "直接攻击对方英雄",
        "overlapping" : 1,
        "statustype" : 1,
        "name" : "飞行",
        "effectivetimes" : 0,
        "replace" : 0,
        "triggercondition" : 0,
        "icon" : 0,
        "dispel" : 0,
    },
    60005 : {
        "triggerresultid" : {
            1 : 0,
            2 : 0,
        },
        "id" : 60005,
        "duration" : 1,
        "staturesultsid" : 6005,
        "desc" : "无法行动",
        "overlapping" : 1,
        "statustype" : 2,
        "name" : "晕眩",
        "effectivetimes" : 0,
        "replace" : 2,
        "triggercondition" : 0,
        "icon" : 0,
        "dispel" : 1,
    },
    60002 : {
        "triggerresultid" : {
            1 : 0,
            2 : 60006,
        },
        "id" : 60002,
        "duration" : 0,
        "staturesultsid" : 0,
        "desc" : "触发：增加攻击力",
        "overlapping" : 1,
        "statustype" : 1,
        "name" : "增幅",
        "effectivetimes" : 0,
        "replace" : 0,
        "triggercondition" : 9008,
        "icon" : 0,
        "dispel" : 1,
    },
    60004 : {
        "triggerresultid" : {
            1 : 0,
            2 : 0,
        },
        "id" : 60004,
        "duration" : 2,
        "staturesultsid" : 6004,
        "desc" : "攻击力降低",
        "overlapping" : 1,
        "statustype" : 2,
        "name" : "力竭",
        "effectivetimes" : 0,
        "replace" : 1,
        "triggercondition" : 0,
        "icon" : 0,
        "dispel" : 1,
    },
    60006 : {
        "triggerresultid" : {
            1 : 0,
            2 : 0,
        },
        "id" : 60006,
        "duration" : 3,
        "staturesultsid" : 6002,
        "desc" : "攻击力增加",
        "overlapping" : 5,
        "statustype" : 1,
        "name" : "士气",
        "effectivetimes" : 0,
        "replace" : 0,
        "triggercondition" : 0,
        "icon" : 0,
        "dispel" : 1,
    },
    60001 : {
        "triggerresultid" : {
            1 : 0,
            2 : 0,
        },
        "id" : 60001,
        "duration" : 0,
        "staturesultsid" : 6001,
        "desc" : "抵挡少量伤害",
        "overlapping" : 1,
        "statustype" : 1,
        "name" : "大气护盾",
        "effectivetimes" : 0,
        "replace" : 1,
        "triggercondition" : 0,
        "icon" : 0,
        "dispel" : 1,
    },

};
module.exports = _p;
