/*
Don't modify this file manually!
*/
var _p = {
    9018 : {
        "Effect2" : {
            1 : {
                1 : 60050,
                2 : 100,
                3 : -11,
                4 : 110,
                5 : 1,
            },
            2 : {
                1 : 60050,
                2 : 100,
                3 : -11,
                4 : 110,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9028,
        "Desc1" : 9025,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 10304,
        "PickupLived" : 1,
        "Pic2" : 902,
        "Id" : 9018,
        "Pic1" : 902,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "沉睡遗迹",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9026,
            2 : 9027,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10149,
    },
    9026 : {
        "Effect2" : {
            1 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 1,
            },
            2 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9060,
        "Desc1" : 9057,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 10408,
        "PickupLived" : 0,
        "Pic2" : 3605,
        "Pic1" : 3605,
        "Id" : 9026,
        "Resetting" : 0,
        "GetInto" : 0,
        "RestrictStep" : 0,
        "Name" : "思春的巨兽",
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 5,
            },
        },
        "Obstacle" : 1,
        "Desc2" : {
            1 : 9058,
            2 : 9059,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10159,
    },
    9003 : {
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1,
        "RestrictLose" : 0,
        "Pic2" : 1400,
        "Id" : 9003,
        "Pic1" : 1400,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "荒野修道院",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9011 : {
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1005,
        "RestrictLose" : 0,
        "Pic2" : 1701,
        "Id" : 9011,
        "Pic1" : 1701,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "时空之门",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10002,
    },
    9004 : {
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1,
        "RestrictLose" : 0,
        "Pic2" : 800,
        "Id" : 9004,
        "Pic1" : 800,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "废弃哨塔",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9012 : {
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1008,
        "RestrictLose" : 0,
        "Pic2" : 901,
        "Id" : 9012,
        "Pic1" : 901,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "妖树洞",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10002,
    },
    9020 : {
        "Effect2" : {
            1 : {
                1 : 60053,
                2 : 100,
                3 : 0,
                4 : 82,
                5 : 1,
            },
            2 : {
                1 : 60053,
                2 : 100,
                3 : 0,
                4 : 82,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9036,
        "Desc1" : 9033,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 0,
        "PickupLived" : 1,
        "Pic2" : 905,
        "Id" : 9020,
        "Pic1" : 905,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "呜咽洞穴",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9034,
            2 : 9035,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10203,
    },
    9005 : {
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1,
        "RestrictLose" : 0,
        "Pic2" : 1300,
        "Id" : 9005,
        "Pic1" : 1300,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "侏儒要塞",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9013 : {
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1009,
        "RestrictLose" : 0,
        "Pic2" : 1701,
        "Id" : 9013,
        "Pic1" : 1701,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "时空之门",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10003,
    },
    9021 : {
        "Effect2" : {
            1 : {
                1 : 60060,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 1,
            },
            2 : {
                1 : 60060,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9040,
        "Desc1" : 9037,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 0,
        "PickupLived" : 1,
        "Pic2" : 912,
        "Id" : 9021,
        "Pic1" : 912,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "神秘枯井",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9038,
            2 : 9039,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10204,
    },
    9006 : {
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1,
        "RestrictLose" : 0,
        "Pic2" : 900,
        "Id" : 9006,
        "Pic1" : 900,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "龙巢",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9022 : {
        "Effect2" : {
            1 : {
                1 : 60059,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 1,
            },
            2 : {
                1 : 60059,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9044,
        "Desc1" : 9041,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 3,
        },
        "Monster" : 10406,
        "PickupLived" : 1,
        "Pic2" : 911,
        "Id" : 9022,
        "Pic1" : 911,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "水墙洞",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9042,
            2 : 9043,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10157,
    },
    9007 : {
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1,
        "RestrictLose" : 0,
        "Pic2" : 800,
        "Id" : 9007,
        "Pic1" : 800,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "战争遗迹",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9015 : {
        "Effect2" : {
            1 : {
                1 : 60053,
                2 : 100,
                3 : 0,
                4 : 82,
                5 : 1,
            },
            2 : {
                1 : 60053,
                2 : 100,
                3 : 0,
                4 : 82,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9016,
        "Desc1" : 9013,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 0,
        "PickupLived" : 1,
        "Pic2" : 905,
        "Id" : 9015,
        "Pic1" : 905,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "尖啸洞窟",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9014,
            2 : 9015,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10200,
    },
    9008 : {
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1007,
        "RestrictLose" : 0,
        "Pic2" : 1401,
        "Id" : 9008,
        "Pic1" : 1401,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "巫师家宅",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9016 : {
        "Effect2" : {
            1 : {
                1 : 60051,
                2 : 100,
                3 : 0,
                4 : 115,
                5 : 1,
            },
            2 : {
                1 : 60051,
                2 : 100,
                3 : 0,
                4 : 115,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9020,
        "Desc1" : 9017,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 10204,
        "PickupLived" : 1,
        "Pic2" : 903,
        "Id" : 9016,
        "Pic1" : 903,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "幽光之门",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9018,
            2 : 9019,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10144,
    },
    9024 : {
        "Effect2" : {
            1 : {
                1 : 60060,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 1,
            },
            2 : {
                1 : 60060,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9052,
        "Desc1" : 9049,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 10407,
        "PickupLived" : 1,
        "Pic2" : 912,
        "Id" : 9024,
        "Pic1" : 912,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "井下洞窟",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9050,
            2 : 9051,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10158,
    },
    9001 : {
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1,
        "RestrictLose" : 0,
        "Pic2" : 900,
        "Id" : 9001,
        "Pic1" : 900,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "野外洞窟",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9009 : {
        "ElementType" : 9,
        "Probability1" : 0,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 100,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1004,
        "RestrictLose" : 0,
        "Pic2" : 801,
        "Id" : 9009,
        "Pic1" : 801,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "废弃哨塔",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9017 : {
        "Effect2" : {
            1 : {
                1 : 60051,
                2 : 100,
                3 : 0,
                4 : 115,
                5 : 1,
            },
            2 : {
                1 : 60051,
                2 : 100,
                3 : 0,
                4 : 115,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9024,
        "Desc1" : 9021,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 0,
        "PickupLived" : 1,
        "Pic2" : 903,
        "Pic1" : 903,
        "Id" : 9017,
        "Resetting" : 0,
        "GetInto" : 1,
        "RestrictStep" : 0,
        "Name" : "封印洞窟",
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 1,
            },
        },
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9022,
            2 : 9023,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10201,
    },
    9025 : {
        "Effect2" : {
            1 : {
                1 : 60063,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 1,
            },
            2 : {
                1 : 60063,
                2 : 100,
                3 : 0,
                4 : 113,
                5 : 2,
            },
        },
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9056,
        "Desc1" : 9053,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "Monster" : 0,
        "PickupLived" : 0,
        "Pic2" : 3644,
        "Pic1" : 3644,
        "Id" : 9025,
        "Resetting" : 0,
        "GetInto" : 0,
        "RestrictStep" : 0,
        "Name" : "玛林",
        "Precondition" : {
            1 : {
                1 : 3,
                2 : 4,
            },
        },
        "Obstacle" : 1,
        "Desc2" : {
            1 : 9054,
            2 : 9055,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "RestrictLose" : 0,
        "Reward" : 10206,
    },
    9002 : {
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1,
        "RestrictLose" : 0,
        "Pic2" : 500,
        "Id" : 9002,
        "Pic1" : 500,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "魔女之家",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10001,
    },
    9010 : {
        "ElementType" : 9,
        "Probability1" : 100,
        "Genre" : 3,
        "Desc3" : 9012,
        "Desc1" : 9009,
        "Value" : 0,
        "Probability2" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "Monster" : 1007,
        "RestrictLose" : 0,
        "Pic2" : 1701,
        "Id" : 9010,
        "Pic1" : 1701,
        "GetInto" : 1,
        "Resetting" : 0,
        "RestrictStep" : 0,
        "Name" : "时空之门",
        "Obstacle" : 0,
        "Desc2" : {
            1 : 9010,
            2 : 9011,
        },
        "DirTrigger" : 0,
        "RestrictSuc" : 0,
        "PickupLived" : 1,
        "Reward" : 10002,
    },

};
module.exports = _p;
