/*
Don't modify this file manually!
*/
var _p = {
    16004 : {
        "Square" : {
            1 : 6,
            2 : 6,
        },
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : 1602,
        "Genre" : 4,
        "Desc1" : 1600,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : 1602,
        "Id" : 16004,
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "Name" : "3瞭望塔",
        "Desc2" : 1601,
        "RestrictStep" : 0,
        "RestrictSuc" : 0,
        "Direction" : 0,
        "RestrictLose" : 0,
    },
    16001 : {
        "Square" : {
            1 : 5,
            2 : 5,
        },
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : 1600,
        "Genre" : 4,
        "Desc1" : 1600,
        "Anchor" : 0,
        "Area" : {
            1 : 2,
            2 : 2,
        },
        "PickupLived" : 1,
        "Pic2" : 1600,
        "Id" : 16001,
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "Name" : "瞭望塔",
        "Desc2" : 1601,
        "RestrictStep" : 0,
        "RestrictSuc" : 0,
        "Direction" : 0,
        "RestrictLose" : 0,
    },
    16005 : {
        "Square" : {
            1 : 6,
            2 : 6,
        },
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : 1601,
        "Genre" : 4,
        "Desc1" : 1600,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : 1601,
        "Id" : 16005,
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "Name" : "4瞭望塔",
        "Desc2" : 1601,
        "RestrictStep" : 0,
        "RestrictSuc" : 0,
        "Direction" : 0,
        "RestrictLose" : 0,
    },
    16002 : {
        "Square" : {
            1 : 6,
            2 : 6,
        },
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : 1601,
        "Genre" : 4,
        "Desc1" : 1600,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : 1601,
        "Id" : 16002,
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "Name" : "瞭望塔",
        "Desc2" : 1601,
        "RestrictStep" : 0,
        "RestrictSuc" : 0,
        "Direction" : 0,
        "RestrictLose" : 0,
    },
    16006 : {
        "Square" : {
            1 : 1,
            2 : 1,
        },
        "Effect2" : {
            1 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 92,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : 3649,
        "Genre" : 4,
        "Desc1" : 1602,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : 3649,
        "Id" : 16006,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Resetting" : 0,
        "Name" : "史莱姆",
        "Desc2" : 1602,
        "RestrictStep" : 0,
        "RestrictSuc" : 0,
        "Direction" : 0,
        "RestrictLose" : 0,
    },
    16003 : {
        "Square" : {
            1 : 6,
            2 : 6,
        },
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : 1602,
        "Genre" : 4,
        "Desc1" : 1600,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : 1602,
        "Id" : 16003,
        "GetInto" : 1,
        "Obstacle" : 0,
        "Resetting" : 0,
        "Name" : "2瞭望塔",
        "Desc2" : 1601,
        "RestrictStep" : 0,
        "RestrictSuc" : 0,
        "Direction" : 0,
        "RestrictLose" : 0,
    },
    16007 : {
        "Square" : {
            1 : 1,
            2 : 1,
        },
        "Effect2" : {
            1 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 92,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : 3637,
        "Genre" : 4,
        "Desc1" : 1603,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : 3637,
        "Id" : 16007,
        "GetInto" : 0,
        "Obstacle" : 1,
        "Resetting" : 0,
        "Name" : "四大美人",
        "Desc2" : 1603,
        "RestrictStep" : 0,
        "RestrictSuc" : 0,
        "Direction" : 0,
        "RestrictLose" : 0,
    },

};
module.exports = _p;
