/*
Don't modify this file manually!
*/
var _p = {
    16005 : {
        "Square" : {
            1 : 6,
            2 : 6,
        },
        "PickupLived" : 1,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "Direction" : 0,
        "Id" : 16005,
        "Pic1" : 1601,
        "Genre" : 4,
        "GetInto" : 1,
        "Resetting" : 0,
        "Desc1" : 1600,
        "Name" : "4瞭望塔",
        "Desc2" : 1601,
        "Anchor" : 0,
        "Obstacle" : 0,
        "ElementType" : 16,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    16007 : {
        "Square" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Effect2" : {
            1 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 92,
                5 : 1,
            },
        },
        "Direction" : 0,
        "Id" : 16007,
        "Pic1" : 3637,
        "Genre" : 4,
        "GetInto" : 0,
        "Resetting" : 0,
        "Desc1" : 1603,
        "Name" : "四大美人",
        "Desc2" : 1603,
        "Anchor" : 0,
        "Obstacle" : 1,
        "ElementType" : 16,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    600201 : {
        "Direction" : 0,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 200,
                3 : 0,
                4 : 380,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : "b2_1611001",
        "Genre" : 4,
        "Desc1" : 116001011,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : {
            2 : 0,
            3 : 36,
            4 : 2,
        },
        "Id" : 600201,
        "GetInto" : 1,
        "Name" : "瞭望塔",
        "Desc2" : 116001011,
        "Obstacle" : 0,
        "Square" : {
            1 : 9,
            2 : 9,
        },
        "Resetting" : 0,
        "PicClickArea" : {
            1 : {
                1 : 0,
                2 : -79,
                3 : 39,
                4 : 362,
            },
        },
    },
    16002 : {
        "Square" : {
            1 : 6,
            2 : 6,
        },
        "PickupLived" : 1,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "Direction" : 0,
        "Id" : 16002,
        "Pic1" : 1601,
        "Genre" : 4,
        "GetInto" : 1,
        "Resetting" : 0,
        "Desc1" : 1600,
        "Name" : "瞭望塔",
        "Desc2" : 1601,
        "Anchor" : 0,
        "Obstacle" : 0,
        "ElementType" : 16,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    16004 : {
        "Square" : {
            1 : 8,
            2 : 8,
        },
        "PickupLived" : 1,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "Direction" : 0,
        "Id" : 16004,
        "Pic1" : 1602,
        "Genre" : 4,
        "GetInto" : 1,
        "Resetting" : 0,
        "Desc1" : 1600,
        "Name" : "3瞭望塔",
        "Desc2" : 1601,
        "Anchor" : 0,
        "Obstacle" : 0,
        "ElementType" : 16,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    16006 : {
        "Square" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Effect2" : {
            1 : {
                1 : 60064,
                2 : 100,
                3 : 0,
                4 : 92,
                5 : 1,
            },
        },
        "Direction" : 0,
        "Id" : 16006,
        "Pic1" : 3649,
        "Genre" : 4,
        "GetInto" : 0,
        "Resetting" : 0,
        "Desc1" : 1602,
        "Name" : "史莱姆",
        "Desc2" : 1602,
        "Anchor" : 0,
        "Obstacle" : 1,
        "ElementType" : 16,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    400201 : {
        "Direction" : 0,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 200,
                3 : 0,
                4 : 380,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : "b1_1611001",
        "Genre" : 4,
        "Desc1" : 116001011,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : {
            2 : 0,
            3 : 36,
            4 : 2,
        },
        "Id" : 400201,
        "GetInto" : 1,
        "Name" : "瞭望塔",
        "Desc2" : 116001011,
        "Obstacle" : 0,
        "Square" : {
            1 : 8,
            2 : 8,
        },
        "Resetting" : 0,
        "PicClickArea" : {
            1 : {
                1 : 0,
                2 : -79,
                3 : 39,
                4 : 362,
            },
        },
    },
    600101 : {
        "Direction" : 0,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 200,
                3 : 0,
                4 : 380,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : "b2_1611001",
        "Genre" : 4,
        "Desc1" : 116001011,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : {
            2 : 0,
            3 : 36,
            4 : 2,
        },
        "Id" : 600101,
        "GetInto" : 1,
        "Name" : "瞭望塔",
        "Desc2" : 116001011,
        "Obstacle" : 0,
        "Square" : {
            1 : 7,
            2 : 7,
        },
        "Resetting" : 0,
        "PicClickArea" : {
            1 : {
                1 : 0,
                2 : -79,
                3 : 39,
                4 : 362,
            },
        },
    },
    500101 : {
        "Direction" : 0,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 200,
                3 : 0,
                4 : 380,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : "b2_1611001",
        "Genre" : 4,
        "Desc1" : 116001011,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : {
            2 : 0,
            3 : 36,
            4 : 2,
        },
        "Id" : 500101,
        "GetInto" : 1,
        "Name" : "瞭望塔",
        "Desc2" : 116001011,
        "Obstacle" : 0,
        "Square" : {
            1 : 7,
            2 : 7,
        },
        "Resetting" : 0,
        "PicClickArea" : {
            1 : {
                1 : 0,
                2 : -79,
                3 : 39,
                4 : 362,
            },
        },
    },
    16001 : {
        "Square" : {
            1 : 5,
            2 : 5,
        },
        "PickupLived" : 1,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "Direction" : 0,
        "Id" : 16001,
        "Pic1" : 1600,
        "Genre" : 4,
        "GetInto" : 1,
        "Resetting" : 0,
        "Desc1" : 1600,
        "Name" : "瞭望塔",
        "Desc2" : 1601,
        "Anchor" : 0,
        "Obstacle" : 0,
        "ElementType" : 16,
        "Area" : {
            1 : 2,
            2 : 2,
        },
    },
    16003 : {
        "Square" : {
            1 : 6,
            2 : 6,
        },
        "PickupLived" : 1,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 100,
                3 : 0,
                4 : 190,
                5 : 1,
            },
        },
        "Direction" : 0,
        "Id" : 16003,
        "Pic1" : 1602,
        "Genre" : 4,
        "GetInto" : 1,
        "Resetting" : 0,
        "Desc1" : 1600,
        "Name" : "2瞭望塔",
        "Desc2" : 1601,
        "Anchor" : 0,
        "Obstacle" : 0,
        "ElementType" : 16,
        "Area" : {
            1 : 1,
            2 : 1,
        },
    },
    400101 : {
        "Direction" : 0,
        "Effect2" : {
            1 : {
                1 : 60047,
                2 : 200,
                3 : 0,
                4 : 380,
                5 : 1,
            },
        },
        "ElementType" : 16,
        "Pic1" : "b1_1611001",
        "Genre" : 4,
        "Desc1" : 116001011,
        "Anchor" : 0,
        "Area" : {
            1 : 1,
            2 : 1,
        },
        "PickupLived" : 1,
        "Pic2" : {
            2 : 0,
            3 : 36,
            4 : 2,
        },
        "Id" : 400101,
        "GetInto" : 1,
        "Name" : "瞭望塔",
        "Desc2" : 116001011,
        "Obstacle" : 0,
        "Square" : {
            1 : 7,
            2 : 7,
        },
        "Resetting" : 0,
        "PicClickArea" : {
            1 : {
                1 : 0,
                2 : -79,
                3 : 39,
                4 : 362,
            },
        },
    },

};
module.exports = _p;
